### ISSUE TITLE
Types fail to resolve in TypeScript 5.x in ESM 

### ISSUE THREAD

**Issue by AaronFriel** [spencermountain/compromise#1012]
When importing `compromise`, I see this error:

```typescript
import nlp from 'compromise';
```

> Could not find a declaration file for module 'compromise'. '$project/node_modules/compromise/src/three.js' implicitly has an 'any' type.
> There are types at '$project/node_modules/compromise/types/three.d.ts', but this result could not be resolved when respecting package.json "exports". The 'compromise' library may need to update its package.json or typings.ts(7016)

I've not seen this strategy of separating `src` and `types` into separate folders like this, I think that's where the issue might be?

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2022","DOM"],
    "module": "nodenext"
  }
}
```

Setting `moduleResolution` to `bundler` does not seem to help, nor does setting module to `Node16` or `ESNext` or others.

**Comment by AaronFriel** [comment]
If I remove the "exports" section of the package.json, this fixes type resolution:

```

  "exports": {
    ".": {
      "import": "./src/three.js",
      "require": "./builds/three/compromise-three.cjs"
    },
    "./tokenize": {
      "import": "./src/one.js",
      "require": "./builds/one/compromise-one.cjs"
    },
    "./one": {
      "import": "./src/one.js",
      "require": "./builds/one/compromise-one.cjs"
    },
    "./two": {
      "import": "./src/two.js",
      "require": "./builds/two/compromise-two.cjs"
    },
    "./three": {
      "import": "./src/three.js",
      "require": "./builds/three/compromise-three.cjs"
    }
  },
```

Perhaps there is a trick there to enabling types for each of these imports?

**Comment by spencermountain** [comment]
oh, this was fixed by https://github.com/spencermountain/compromise/pull/999
will release it after a few changes tmrw

**Comment by AaronFriel** [comment]
Thanks!

**Comment by spencermountain** [comment]
should work again now in 14.9.0
let me know if you see any other issues
cheers
