### ISSUE TITLE
How to extract medication names from a text using compromise?

### ISSUE THREAD

**Issue by MenaiAla** [spencermountain/compromise#1014]
<i>I'm new in compromise.</i>

### Reproduce

`npm install compromise`

#### code

```javascript

import nlp from 'compromise';

const text = "I need to take paracetamol and ibuprofen for my headache.";
const medicationNames = nlp(text)
  .match('#Medicine+')
  .out('array')
  .map((entity) => entity.text());
console.log(medicationNames); /

```

### Expected

`["paracetamol", "ibuprofen"]`

### Current
`[]`

**Comment by spencermountain** [comment]
hey Menai, `#Medicine` is not a supported tag in compromise. See our list of tags [here](https://observablehq.com/@spencermountain/compromise-tags)

you can add custom tags, as described [here](https://observablehq.com/@spencermountain/compromise-lexicon)
