### ISSUE TITLE
Word Groupings?

### ISSUE THREAD

**Issue by msj121** [spencermountain/compromise#1017]
Is there a way to tell in a sentence when two words belong together, like "did you swim in an olympic pool?" or "do you practice self defense" in both sentences I think those two last words can be "grouped" together. Is there a way to determine this or to have a pretty good guess?

Thanks.

**Comment by spencermountain** [comment]
hey @msj121 - this is a good question, and your results will depend on specifically what you're looking for.

First, you could do `.nouns()` which does some of this already. Alternatively you could do `.match('#Noun+').not('#Pronoun')` for things like olympic pool. Or, `.verbs()` for things like 'throw up'.

there is also cases like 'green olives' which would want `.match('#Adjective? #Noun+')` - maybe you want 'blue hair' but do not want 'soft hair'.

I would play around with different matches and filters. You can see what we do in .nouns() [here](https://github.com/spencermountain/compromise/blob/master/src/3-three/nouns/find.js)
cheers

**Comment by msj121** [comment]
Interesting. I will play around with this. Thank you! It will only improve my user interface by matching likely pairs of adjectives and nouns.
