### ISSUE TITLE
Finding important words?

### ISSUE THREAD

**Issue by msj121** [spencermountain/compromise#1018]
Hi,

I have a sentence like "I would love to travel to Canada", I have a lists of comments. I'd like to find meaningful matches. Currently, I am trying to remove meaningless words like "would" "to" and match on the important words.

I wanted to use compromise to stem and check with "has", but perhaps there is a better way? I noticed compromise doesn't have a function for removing meaningless words, am I going about this wrong? How would you do this?

**Comment by msj121** [comment]
Moved this to chat actually.... not a bug. sorry.

**Comment by spencermountain** [comment]
hey @msj121 - ha, it depends on what you mean by meaningless!
you can always do `.remove('#Adverb')` but that will misunderstand things like 'he barely ate his food'.

You could write a list of different matches, like `I #Modal? (love|like) to travel to #Country` or something like that, and try to catch as many templates as you can.

for stemmed matches, you can do `{love} to` - to match 'he loves to travel to canada' etc.
cheers
