### ISSUE TITLE
.compute() examples notebook is private or deleted

### ISSUE THREAD

**Issue by G07cha** [spencermountain/compromise#1019]
A link from [`.compute()` util](https://github.com/spencermountain/compromise/#utils) in docs leads to https://observablehq.com/@spencermountain/compromise-compute, which is currently unavailable.

**Comment by spencermountain** [comment]
ah, thank you. Please [check it out now](https://observablehq.com/@spencermountain/compromise-compute).
Hope it's helpful - please let me know if you see any other documentation holes
cheers

**Comment by G07cha** [comment]
Thanks, @spencermountain, that was quick and very helpful!
