### ISSUE TITLE
Sentence Boundary Detection and Sentence Segmentation？

### ISSUE THREAD

**Issue by asasas234** [spencermountain/compromise#1021]
I want to implement to determine if 1 sentence has reached the end or if 1 sentence should be split into 2 sentences。
For example: 
```
I am a programmer 
```
How can I tell when the above sentence has reached the end? Or is it 1 complete sentence?

Also given a string that may have multiple English sentences in it, how do I split it up？
For example: 
```
I am a programmer my special language is Java
```
I hope the above statement should be split into 2 sentences, I am a programmer and my special language is Java.

How do I do this, please?

**Comment by spencermountain** [comment]
hi @asasas234 - this is a really hard problem! It may be one of the more difficult problems in the field.

I would start w/ the heuristic that a sentence should contain a verb, and then have end with a noun-phrase. Of course, there are many many examples where this is not the case, like questions, exclamations, conditional phrases, and so forth, and I would study them for patterns.

Depending on your use-case, you may want to develop rules for good-looking sentence structure, or develop patterns for unfinished sentences. This sort of thing could be done using compromise, or without it. 
Good luck!!
cheers

**Comment by MarketingPip** [comment]
@spencermountain - I do think we could achieve this. Check out [here](https://spacy.io/universe/project/python-sentence-boundary-disambiguation) & the [Golden Rule Set](https://s3.amazonaws.com/tm-town-nlp-resources/golden_rules.txt), as well [here](https://github.com/diasks2/pragmatic_segmenter).

Tho I do not think the example given in the issue would be a true example of a sentence with a end.

We could also apply the strategies found on the wiki page [here](https://en.wikipedia.org/wiki/Sentence_boundary_disambiguation#Strategies) after the Golden Rule Set has been applied.
