### ISSUE TITLE
`.lists()` is not a function (same for: `.hash()`)

### ISSUE THREAD

**Issue by TrySpace** [spencermountain/compromise#1024]
On the docs website: https://observablehq.com/@spencermountain/compromise-lists?collection=%40spencermountain%2Fnlp-compromise as well as my local code (version: 14.9.0)

Something is broken in the release.

Also typescript seems incomplete like using `lookBehind`  on a `.match()` says it does not exist on type `View`, yet it does work.

**Comment by spencermountain** [comment]
hey - yep, you're right.  Sorry bout that.
Not sure where `.lists()` went - I don't think it was very well implemented to begin with.

yeah - lookBehind just aliases to `.before()` - which has properly supported types.
PRs welcomed, if you'd like to help clean this up. Is there a clever way to do aliases in typescript? I always feel weird about duplicating things.
thanks

**Comment by TrySpace** [comment]
```ts
interface One extends Two {}
```
should do the trick

And I think something like: 
```ts
type One = Two
```
should also work

**Comment by spencermountain** [comment]
duplicated these types in `14.10.0` - I haven't figured out a smart way to [add the aliases here](https://github.com/spencermountain/compromise/blob/dev/types/view/one.d.ts#L98) - if you wanted to do a PR, that would help, thanks
