### ISSUE TITLE
Issue adding to Lexicon

### ISSUE THREAD

**Issue by MarketingPip** [spencermountain/compromise#1032]
There is an issue when adding lexicon that contain values such as (Prepositions, Noun, Verb) etc.. 

Example: 

This works fine!

```js
let lexicon = {
    "the":["hello", "how", "weird"]
}

nlp(`the`, lexicon)

// Outputs
"tags": [
        "hello",
        "how",
        "weird"
      ]
```

but this does not.

```js
let lexicon = {
    "the":["Adverb","Preposition","Noun","Pronoun","Adjective","Verb","Determiner","Conjunction"]
}

nlp(`the`, lexicon)

// Outputs
 "tags": [
        "Conjunction"
      ]
```

**Comment by spencermountain** [comment]
hey Jared, there are some rules [in the internal tags](https://github.com/spencermountain/compromise/tree/master/src/2-two/preTagger/tagSet) that forbid a word from being two inconsistent tags, such as a Noun and an Adjective.

This is done quietly, so it is sometimes confusing.
You can read a bit about this [here](https://observablehq.com/@spencermountain/compromise-tagger#cell-126)
cheers
