### ISSUE TITLE
[Improvement]: Government of #Country - Rule

### ISSUE THREAD

**Issue by MarketingPip** [spencermountain/compromise#1040]
Again - another rule kit. 

```js
/**
 * Extracts government of country from a given text.
 *
 * @param {string} str - The input text to analyze.
 * @returns {string|false} - The extracted government name or false if no match is found.
 */

function governmentOfRule(str) {
  // Create an NLP document from the input text
  let doc = nlp(str);
  // Check for patterns like "government of Canada" or "government of the united states"
  let match = doc.match("government (of the|of) (#Country+|#Country)");
  if (match.found) {
    return match.out("text");
  }
  

  return false; // Return null if no bank names is found
}


console.log(governmentOfRule("government of india"))
```

**Comment by spencermountain** [comment]
this works for `/postTagger/model/orgs` too - I would write it `government of the? #Country+`
cheers

**Comment by MarketingPip** [comment]
@spencermountain - if you wanna add the changes your more than welcome. If you want me too - also more than welcome. Wanted approval before messing with anything - since I thought I f*cked up kinda with the university rule after seeing where you moved it & you had something commented out similar in it. 

But no hurt feelings if you get to this before me. 👍

**Comment by MarketingPip** [comment]
Closed as seeing you have added this in.
