### ISSUE TITLE
[Improvement]: Better compression algorithm 

### ISSUE THREAD

**Issue by MarketingPip** [spencermountain/compromise#1042]
Do not shoot me if any of this has been done - haven't peaked in all the compression taking place in Compromise. But we need to get the size of this library back down - as that was literally one of the cool things / main features of Compromise. (But it is slowly growing more and more) & will continue when more words are added that need to desperately be in this library. Such as more verbs, places & more. (Which we need to figure out a solution for this too - as we can't just keep stacking the lexicon for the rest of our life's - hence a need for some sort of neural network to help with detection). 

But suggesting we take all tags - "#Places" etc. Assign numbers to them in JSON compression. And when decompressed replace number with the value. Example: ```Toronto":["1"]``` & JSON for compression ```{1:"#Place}```. Reducing the need of a lot of characters. 

And things like ```Toronto Maple Leafs``` - could be again done with something similar. If duplicate single word etc. "Toronto"  could become  ```1 Maple Leafs``` and all instance of "1" lets say if Toronto is assigned to that number is replaced when decompressed. 

And curious if we should be using something else than LZMA for compression.

**Comment by spencermountain** [comment]
Our compression library is here
https://github.com/spencermountain/efrt
Jared, please look at what exists before creating an issue.

**Comment by MarketingPip** [comment]
@spencermountain - I have already seen this. I know it goes through that plus LZMA. But I didn't know if it when further with JSON-Schema Key Compression.

**Comment by MarketingPip** [comment]
@spencermountain - not trying to piss you off. But please see below. 

```js
function compressLexicon(lexicon) {
  const compressedLexicon = {};
  const tagMap = {}; // Map for tracking assigned numbers for each tag
  let tagCounter = 1; // Counter for assigning numbers to tags
  const tagSchema = {}; // JSON schema for tag values

  for (const word in lexicon) {
    const tag = lexicon[word];
    if (Array.isArray(tag)) {
      const compressedTags = [];
      for (const t of tag) {
        if (!tagMap.hasOwnProperty(t)) {
          // Assign a new number to the tag
          tagMap[t] = `Key${tagCounter}`;
          tagSchema[tagMap[t]] = t; // Store original tag value
          tagCounter++;
        }
        compressedTags.push(tagMap[t]);
      }
      compressedLexicon[word] = compressedTags;
    } else {
      if (!tagMap.hasOwnProperty(tag)) {
        // Assign a new number to the tag
        tagMap[tag] = `Key${tagCounter}`;
        tagSchema[tagMap[tag]] = tag; // Store original tag value
        tagCounter++;
      }
      compressedLexicon[word] = tagMap[tag];
    }
  }

  return { compressedLexicon, tagSchema };
}

function decompressLexicon(compressedLexicon, tagSchema) {
  const decompressedLexicon = {};

  for (const word in compressedLexicon) {
    const tag = compressedLexicon[word];
    if (Array.isArray(tag)) {
      const decompressedTags = [];
      for (const t of tag) {
        decompressedTags.push(tagSchema[t] || t);
      }
      decompressedLexicon[word] = decompressedTags;
    } else {
      decompressedLexicon[word] = tagSchema[tag] || tag;
    }
  }

  return decompressedLexicon;
}

// Example lexicon
const originalLexicon = {
  House: ['#Noun'],
  apple: "Fruit",
  toronto: "#Noun",
  "house of": "#Noun",
  
  Hello: ['#Verb'],
};

// Compress the lexicon
const { compressedLexicon, tagSchema } = compressLexicon(originalLexicon);
console.log("Compressed Lexicon:", compressedLexicon);
console.log("Tag Schema:", tagSchema);

// Decompress the lexicon
const decompressedLexicon = decompressLexicon(compressedLexicon, tagSchema);
console.log("Decompressed Lexicon:", decompressedLexicon);
```

Then apply ```efrt``` & ```LZMA```.

**Comment by MarketingPip** [comment]
@spencermountain - don't mean to mention / blow your issues again. But I refered / thought the above might be a good approach for doing / using these [rules](https://github.com/spencermountain/compromise/issues/1033#issuecomment-1986680920)
