### ISSUE TITLE
[Improvement]: Location Disambiguation \ Human Name Matching - Rule

### ISSUE THREAD

**Issue by MarketingPip** [spencermountain/compromise#1045]
This might not be ideal but feel free to address concerns. We will need to check for words after. (Most likely need to drop proper noun at end & expand last name list - or will return things like "Toronto Maple" as person).

```js
function nameRule(str) {
  // Create an NLP document from the input text
  let doc = nlp(str);
  // Check for patterns like  "Orlando Bloom" or "Paris Hilton"
  let match = doc.match("(#Place+|#Place|#ProperNoun|#Noun) (#LastName|#Person|#ProperNoun)");
  if (match.found) {
    return match.out("text");
  }
 

  return false; // Return null if no name is found
}


console.log(nameRule("I went to Orlando today to visit Orlando Bloom")) 
console.log(nameRule("I went to Paris today and seen Paris Hilton")) 
```

This should tag things like "Orlando Bloom" only as a "person" same way compromise handles "Paris Hilton" and does not return a place. 

Now only if we can solve handling names like "North West" ie: Kayne / Kim's kid as a person and not directions without a neural network. 😿

**Comment by spencermountain** [comment]
You're free to do this in your own project!

**Comment by MarketingPip** [comment]
@spencermountain - do you not think this might not be useful for determining if a entity is a name or location properly...? As said tho - the last proper noun should be dropped and the last name list should be expanded.

**Comment by spencermountain** [comment]
That would tag all subsequent Propernouns as people.

**Comment by MarketingPip** [comment]
@spencermountain - I am going to sound stupid (nor trying to sound arrogant) but can I have some examples of some strings so I can see what you mean?
