### ISSUE TITLE
date.parse() in nlp_core

### ISSUE THREAD

**Issue by prashcr** [spencermountain/compromise#105]
I tried all the readme examples, and I got very mixed results. Did something in the library break or am I doing something wrong?

```
nlp.text('She sells seashells').to_past()
// An array containing the object shown below. Object contains text from original string.
```

![screenshot 2016-04-14 14 31 39](https://cloud.githubusercontent.com/assets/7514066/14518881/abb570d8-024d-11e6-8ce1-b663e7c9f3b3.png)

```
nlp.noun("dinosaur").pluralize();
// This works

nlp.verb("speak").conjugate();
// This works

nlp.text('She sells seashells').negate()
// Same issue as above

nlp.sentence('I fed the dog').replace('the [Noun]', 'the cat')
// Same issue as above

nlp.text("Tony Hawk did a kickflip").people();
// This works

nlp.person("Tony Hawk").article();
// "a" instead of "he" 

nlp.value("five hundred and sixty").number;
// This works
```

I'm using Chrome Version 49.0.2623.112 (64-bit) on OS X
I got the same results in Node.js 5.10.1

**Comment by spencermountain** [comment]
hey Prashanth, sorry, i was trying to be slick removing the `.text()` from the examples, thinking it would make for clearer documentation. I'm clearly wrong about that, i'll add em back in.
The first three problems should be fixed by adding `.text()` to return a string.

the tony hawk one is a bug - i'll check it out this weekend.

**Comment by spencermountain** [comment]
hey, think i've fixed them in 4.6.3, though had the thought 'he' is not really an article....
anyways, check it out when you've got a sec
thanks

**Comment by prashcr** [comment]
No worries :stuck_out_tongue: 

Actually, I quite liked that functionality, since it allows for easy chaining.

The only real issue is that adding `text()` to the end isn't enough.

Had to add a `[0]` as well to pull it out of the array.

```
nlp.text('She sells seashells').to_past()[0].text()
```

Will check out the new build soon!
Thanks :smile:

**Comment by prashcr** [comment]
I was trying the negate example, found another issue

```
nlp.text('She sells seashells').negate()[0].text()
// Expected: She didn't sell seashells (According to readme, but I think this should be "doesn't")
// Actual: She sells seashells
```

Let me know if I can help in any way.

**Comment by spencermountain** [comment]
agh, good eyes. This broke when i started realising questions don't have negations ..(do they?) so negation should be on the `statement` class, instead of `sentence`.
ergh. gonna have to think this through. What do you think.
i've updated the readme

**Comment by stanonyime** [comment]
On Chrome, i'm getting errors on:
```javascript
nlp.value("I married April for the 2nd time on June 5th 1998 ").date()
```
The error is:
```javascript
VM235:1 Uncaught TypeError: nlp.value(...).date is not a function
```

**Comment by hjek** [comment]
@stanonyime I'm getting that error as well on **NodeJS**. (All other examples working fine though)
```
> nlp.value("I married April for the 2nd time on June 5th 1998 ").date()
TypeError: nlp.value(...).date is not a function
```

**Comment by spencermountain** [comment]
hey, sorry bout that. it looks like there's some old docs. This is the new api, but still a bit janky.
```javascript
nlp.sentence('I married April for the 2nd time on June 5th 1998 ').dates();
```
this returns the array of date terms, which each have their parsed date information in `term.data`.
(you can see this example isn't working perfectly still, i'll take a look) :sweat_smile: 
thanks for your help!

**Comment by kahwee** [comment]
What's the intended output of 

```
nlp.sentence('I married April for the 2nd time on June 5th 1998 ').dates();
```

I was facing this problem too.

I did this to combine the entries together:

```js
  if (dates.length >= 1) {
    output.dates = dates
      .map((date) => date.data)
      .reduce((prev, curr) => {
        Object.keys(prev).forEach((d) => curr[d] = curr[d] || prev[d])
        return curr
      }, {year: null, month: null, day: null})
    output.dates.year = output.dates.year || (new Date()).getUTCFullYear()
  }
```

Are they supposed to return just one item in the array as follows?
 
```
{
  "year": 1998,
  "month": 5,
  "day": 5
}
```

Thanks!

**Comment by spencermountain** [comment]
hey KahWee, yeah, this is the softest part of nlp_compromise by a long shot. That's a great, (and brutal!) example ;)

So for sure it should remain an array of results, you can mention two independent dates per sentence, but the result format is pretty lame.

My intention with the format was to support strings like `"in june"`, without assuming a particular year, likewise for hour/second/etc information - returning a date object forces choices about which year/second it is, even when you don't have information about it.

The second thing is date intervals, like `"june 5th to 6th"`, which i originally supported but stepped-back from.

The third thing is repeating dates, like `"every tuesday"`, which needs some kind of result format that respects wonky the calendar-systems, leap-years etc.

So you can see how limp-wristed the date-parsing method, and result-format is in current form.
What it is good at though, is identifying which part of a text is a date. 
Maybe date.parse() should be removed completely, or created as a plugin, or something like this.

Anybody with ideas or ambitious with this, that'd be great
cheers!

**Comment by kahwee** [comment]
Oh, that's an interesting use case -- didn't think about date ranges. I can see why this is tricky. I'm interested to tackle dates and duration for a bot project I'm working on.

**Comment by focusdigital** [comment]
Might be worth taking a look at https://github.com/wanasit/chrono and/or the "builtin.datetime" section of https://www.luis.ai/Help/#PreBuiltEntities for some inspiration.

**Comment by spencermountain** [comment]
😍  points to the first person to make a plugin

**Comment by mhsjlw** [comment]
Does this still work?

**Comment by spencermountain** [comment]
just cleaning up issues - date parsing documentation now lives here - https://compromise.cool/three/dates/
cheers!
