### ISSUE TITLE
compromise-dates: types unavailable

### ISSUE THREAD

**Issue by mufeez-amjad** [spencermountain/compromise#1054]
When using version 3.4.1 (latest) of `compromise-dates` the types are not available.

I saw that a PR was merged to add the types but the NPM package version number was not bumped: https://github.com/spencermountain/compromise/pull/990/files

Would it be possible to add a new release so that the types are included?

**Comment by spencermountain** [comment]
hey Mufeez - good catch. 
Released as 3.4.2 - please let me know if you have any other issues.
cheers
