### ISSUE TITLE
Property 'normalize' does not exist on type 'People'.

### ISSUE THREAD

**Issue by ionutpopa** [spencermountain/compromise#1058]
As the title says, trying to use people in a Node.js project and following the documentation you should use normalize() after calling people() but it returns the type error Property 'normalize' does not exist on type 'People'.

I have checked People types and indeed it does not exists so maybe it just needs to be added?
![Screenshot 2023-11-01 at 13 18 30](https://github.com/spencermountain/compromise/assets/6348422/4a4f0728-877b-412f-a5a1-cb3acce296a0)

**Comment by ionutpopa** [comment]
Thank toy Spencer, where the announces for new releases are done? Just so I know

**Comment by spencermountain** [comment]
I can let you know here - next week's release is stuck behind a few small things that I hope to get to this weekend.
cheers

**Comment by spencermountain** [comment]
released in `14.10.1`
cheers
