### ISSUE TITLE
Feature Request: Add data to a term

### ISSUE THREAD

**Issue by thegoatherder** [spencermountain/compromise#1066]
I'm looking for some kind of method on a View which will enable me to attach some data to words, the same way that I can attach tags.
Does anything like this already exist?

**Here's a rough sketch:**

```javascript
const doc = nlp('Simon says see you next September')
const match = doc.match('#Month')
const someObj = doSomethingComplexWithMyMatch(match)
match.tag('SomeTag')
// we add some custom data to our Compromise View instance
match.addData(someObj)

// ... somewhere else in the app

const match2 = doc.match('#SomeTag')
// recall the data somehow
const myData = match2.out('data')
```

I think this could be an extremely powerful feature for our project and I'm sure many others...! 

**Example Use Case:**

- An app that extracts all dates from a doc in various formats and maps them to standard JS date objects (e.g. using `spacetime` or some lib)
- Given some base date, calculates all the relative durations pre- and post- that date in the dates found across the document
- Stores the durations in an object against the terms in the document
- That data is now recallable anywhere else in the app with access to the nlp doc, without recalculating.

**Comment by spencermountain** [comment]
ya, really cool idea.
Agree that tags are limited as data, and have taken us really far - (probably too far).
I also like the idea for storing captured metadata, like date metadata, within reach of compromise somehow. 

Imagine if we could do something in match queries with the json like:
```js
let doc=nlp('paul, john lennon and ringo starr')
doc.match('ringo starr').payload({roles:['drummer', 'singer'], hair:'long'})

//then later...
doc.match('and {roles:'drummer'}') //or something
```

Been stuck, forever, on this same dilemma - where to store information about groups of words.
The good news is that they are just javascript objects, and we can stick stuff anywhere.

`View` objects are transient. Every method returns a new one, and would need to marshal any data payload around, with every interaction. Old views would have stale payloads. I don't think it's the right place for this.
Putting paylods in `Term` objects would also be the wrong place - 'ringo' and 'star' would need dangled or duped data between them.

Open to it, just haven't got it clear yet.

**Comment by spencermountain** [comment]
check out the [compromise-payload](https://github.com/spencermountain/compromise/tree/master/plugins/payload) plugin
⚡
