### ISSUE TITLE
Get .terms() but keep hyphenated strings (similar to .hyphenated() )

### ISSUE THREAD

**Issue by PuneetKohli** [spencermountain/compromise#1076]
Is there a way to achieve this?

**Comment by spencermountain** [comment]
hey Puneet, good question:
Little weird, but you could do `.splitAfter('!@hasHyphen')`, like this:
https://runkit.com/spencermountain/659822ebdfb7e500085838fd

Alternatively, you could shim-in a custom tokenizer, like:
```js
nlp.world().methods.one.tokenize.splitTerms = function (str) {
  return str.split(/ /)
}
nlp('one two-three four five').debug()
// one, two-three, four, five
```
that one is obviously [simplified](https://github.com/spencermountain/compromise/blob/master/src/1-one/tokenize/methods/02-terms/index.js), but let me know if you'd like some more help.
cheers
