### ISSUE TITLE
Geedy tag matching and punctuation 

### ISSUE THREAD

**Issue by amorfee** [spencermountain/compromise#1103]
Hello,

I've come across an issue with greedy tag matching and comma separation. The comma is included as part of the match so that multiple tags are combined into one match. 

![Screenshot 2024-04-09 at 11 08 39](https://github.com/spencermountain/compromise/assets/164059904/04d2f189-3d3c-4b63-b660-8853ab76904e)

This is likely expected behaviour for a tag such as #Place but is there a way to force the comma as a word separator? Using .normalize() doesn't seem to help it just removes the comma from the match.

Thank you

**Comment by spencermountain** [comment]
hey, yeah good question. There are a few ways you could do this.

You could split by whatever, then filter then down:
```
let parts = doc.splitAfter('@hasComma');
parts = parts.if('#Place')
```
I sometimes do a aggressive split and then join em up, which is probably a weirder process:
```js
let parts = doc.split('#Place')
parts= parts.joinIf('#Place && @hasComma', '#Place')
```
dunno!
cheers

**Comment by amorfee** [comment]
Thank you, .splitAfter() seems to do what we need.
