### ISSUE TITLE
Determiner mistook for adjective

### ISSUE THREAD

**Issue by NikhilVerma** [spencermountain/compromise#1122]
**Steps to reproduce**

Parse the following sentence: "All information and data must be classified for criticality and sensitivity"

Result from compromise: All is classified as an adjective

Result from CodeNLP (which uses Stanford parser): All is classified as determiner

**Comment by spencermountain** [comment]
hey Nikhil - you're right that this is a tricky case, and we differ from the stanford parser slightly here.
I dunno - I do think that `all information` is describing the information, just like it would be in `all the information`.

You're free ofcourse, to change it - `doc.match('[all] #Noun', 0).tag('Determiner')`
let me know if you feel strongly against the current tagging.
cheers
