### ISSUE TITLE
Contraction not expanded properly for "Somebody's"

### ISSUE THREAD

**Issue by roschler** [spencermountain/compromise#1130]
The library does not expand "Somebody's" properly as in:

```
  ┌─────────
  │ 'Somebody's'  - Noun, Actor, Singular, Possessive
  │ 'talking'  - Noun, Singular
```

Like it does for "Everybody's":

  ┌─────────
  │ '[everybody]'  - Noun, Uncountable
  │ '[is]'     - Verb, Copula, Auxiliary
  │ 'talking'  - Verb, PresentTense, Gerund

**Comment by spencermountain** [comment]
hey Robert, I believe this is a case that is sometimes-possessive and sometimes a contraction:
```js
  doc = nlp(`Somebody's going to see`).debug() // somebody is
  doc = nlp(`Somebody's hat`).debug() // somebody's
```
let me know if you feel like the behaviour should change - perhaps the bare word should default to a contraction, i'm not sure.
cheers
