### ISSUE TITLE
Compromise-dates plugin: Does not project dates followed by a conjunction

### ISSUE THREAD

**Issue by Fdawgs** [spencermountain/compromise#1138]
Node version: 20.16.0
Compromise version: 14.14.0
Compromise-dates version: 3.6.0

Using the compromise-dates plugin, dates are not projected correctly when followed by a Conjunction unless it is ["before", "ago", "hence", or "back"](https://github.com/spencermountain/compromise/blob/8565e74288053ab08711d3074235ecac874c457d/plugins/dates/src/api/parse/one/01-tokenize/01-shift.js#L51).

[The bug is caused by this line](https://github.com/spencermountain/compromise/blob/8565e74288053ab08711d3074235ecac874c457d/plugins/dates/src/compute/matches.js#L46), where any Conjunction  following a Date is tagged as a Date.
Suggested fix: swap out `#Value #Duration #Conjunction` in the line mentioned above to `#Value #Duration (before|ago|hence|back)`.
Happy to do this myself if wanted!

Example of bug:
```js
'use strict'

/** @type {import('compromise').default} */
const nlp = require('compromise')
const nlpDates = require('compromise-dates')
nlp.plugin(nlpDates)

const doc = nlp('I will see him in 2 weeks, but he is a jerk')  // "but" is the Conjunction here

const context = {
  today: '2023-01-01',
}

const datesViews = doc.dates(context)
const dateList = datesViews.json()

console.log(doc.out('tags'))

console.log(dateList[0]?.dates)
/*
Prints:
{
  start: '2023-01-01T00:00:00.000Z',
  end: '2023-01-01T00:00:00.000Z',
  timezone: 'Europe/London',
  duration: { years: 0, months: 0, days: 0, hours: 0, minutes: 0 }
}

Expected it to print the following due to "in 2 weeks":
{
  start: '2023-01-15T00:00:00.000Z',
  end: '2023-01-15T23:59:59.999Z',
  timezone: 'Europe/London',
  duration: { years: 0, months: 0, days: 1, hours: 0, minutes: 0 }
}
*/
```

**Comment by spencermountain** [comment]
released in compromise-dates 3.7.0
thanks!
