### ISSUE TITLE
Treating all dash-separated words as single words

### ISSUE THREAD

**Issue by retorquere** [spencermountain/compromise#1143]
Given the text

```
The multi-part  formulae-as-types notion of construction
```

compromise/one tokenizes `multi-part` as one term and `formulae-as-types` as 3. Can I make compromise tokenize all dash-separated words as it does `multi-part`? Or can I reconstruct that from the terms?

**Comment by retorquere** [comment]
Alternately, is there a way to distinguish between `Grain-Based` (to be treated as one term) and `formulae-as-types` (sensibly treated as 3)?

**Comment by spencermountain** [comment]
hey Emiliano, you're right. this is opaque, and should be made a lot clearer.
There are [a handful of prefixes](https://github.com/spencermountain/compromise/blob/8565e74288053ab08711d3074235ecac874c457d/src/1-one/tokenize/model/prefixes.js#L4) that the tokenizer treats as single-word. These are mostly just made-up, and you can kill them off like this:

```js
nlp.world().model.one.prefixes = {}
nlp(`The multi-part  formulae-as-types notion of construction`).debug()
// [the, multi, part, formulae, as ...]
```
I will try to add these to [the docs](https://observablehq.com/@spencermountain/compromise-tokenization) now
cheers

**Comment by retorquere** [comment]
And the reverse? If I want each hyphen-separated words as one unit?

**Comment by spencermountain** [comment]
you can add anything to the prefix model - it's just a key-value object:
```js
 nlp.world().model.one.prefixes.myprefix = true
 ```
cheers

**Comment by retorquere** [comment]
The issue is I have no control over the input text, so the list of possible prefixes is infinite.
