### ISSUE TITLE
Unable to import this into an ESM project

### ISSUE THREAD

**Issue by Stono** [spencermountain/compromise#1153]
Hey, 
My app is ESM for starters (yay, the pain) and i'm trying to import the module.
It fails, however:

<img width="992" alt="Screenshot 2024-10-15 at 19 45 04" src="https://github.com/user-attachments/assets/fdef8024-cdf0-47e1-9c4a-55e2fc58d1f7">

>   There are types at '/Users/karl.stoney/git/autotrader/ai-gateway/node_modules/compromise-speech/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'compromise-speech' library may need to update its package.json or typings.

I believe all it needs is for types to be added to the exports:

```
  "exports": {
    ".": {
      "import": "./src/plugin.js",
      "require": "./builds/compromise-speech.cjs",
      "types": "./index.d.ts"
    }
  },
```

**Comment by Stono** [comment]
Apologies i wasn't clear, this was for `compromise-speech`

**Comment by spencermountain** [comment]
hey Karl - thanks for the heads up. The esm build should work - happy to make a change
https://github.com/spencermountain/compromise/blob/master/plugins/speech/package.json
maybe my eyes are going blurry, but isn't that the same exports info, as you suggested?
PR welcome, if you can spot a change
cheers

**Comment by Stono** [comment]
That is so odd.... this is the content of it in my node_modules folder!: 

<img width="819" alt="Screenshot 2024-10-15 at 20 19 49" src="https://github.com/user-attachments/assets/ea9796b9-b0d6-4974-a1a2-d06502cc5c5a">

**Comment by Stono** [comment]
Not here either: https://www.npmjs.com/package/compromise-speech/v/0.1.0?activeTab=code

**Comment by Stono** [comment]
👍 Thanks for the quick replies!

**Comment by spencermountain** [comment]
looks like it was my bad, and they appear to be there now in `0.1.1`
thanks for the help
cheers
