### ISSUE TITLE
people() doesn't extract anything

### ISSUE THREAD

**Issue by vickyRathee** [spencermountain/compromise#1156]
Am I doing something wrong? Or the model unable to find the name?

```
const nlp = require('compromise');

let text = 'Contact Tennille Haddock for more details #0405 123 456;
let doc = nlp(text);

// Extract person names
let people = doc.people().text();

console.log(people); // Output should be "Tennille Haddock"
```

https://stackblitz.com/edit/extract-person-name?file=index.js

**Comment by spencermountain** [comment]
hey Vikash - you're right about this - tennille is not in our [name dictionary](https://github.com/spencermountain/compromise/blob/master/data/lexicon/people/femaleNames.js) - but you're free to add it as a custom lexicon:
```js
nlp('Contact Tennille Haddock', {tennille:'FirstName'}).people()
```
cheers
