### ISSUE TITLE
Use units from js-quantities

### ISSUE THREAD

**Issue by michaelmesser** [spencermountain/compromise#176]
Is it possible to use the units from js-quantities?
https://github.com/gentooboontoo/js-quantities/blob/master/src/quantities.js

**Comment by spencermountain** [comment]
yeah, that's pretty-cool. nice find!
that'd be a pretty neat direction for us to go in. 
In a perfect word, we have a Term class called `Mass`, with it's conversions, a term class called `Radiation` with it's conversions, etc - instead of just a generic `Value` class, you know?

**Comment by nilooy** [comment]
has few limitations, IMO it's possible to overcome in `compromise.js` 
as eg:
```js
Qty('1 Liter');
```
is not a recognized unit, 

#### instead these are valid: `1l, 1L, 1 liter`

**Comment by nilooy** [comment]
One question on the tag's usage, what is the proper way to capture no spaced words with or without regex
`/^([0-9])/ #Units` - works fine but `/^([0-9])/#Units` doesn't work, is there any existing method to do that ?
