### ISSUE TITLE
conjugation fixes

### ISSUE THREAD

**Issue by sajjad-shirazy** [spencermountain/compromise#369]
hi
when i conjugate 'dies':
`var conjugate = nlp('dies').verbs().conjugate()[0];`
i got:
`{PastTense: "died", PresentTense: "dies", Infinitive: "dy", FutureTense:"will dy", ...}` 
how can i fix it?

**Comment by sajjad-shirazy** [comment]
also for 'lied' i got `Infinitive: "ly"`

**Comment by spencermountain** [comment]
hey Sajjad, thanks! that's a good find.
i'll take a look at this today
cheers

**Comment by spencermountain** [comment]
oh wow, this is an incredibly useful list.
almost got it fixed
thanks for doing this.

**Comment by sajjad-shirazy** [comment]
Thanks Spencer,
all are fixed. awesome ...

**Comment by spencermountain** [comment]
hey, just published *v10.4.0*, which has a couple more edge-cases I found digging-though your examples
cheers

**Comment by sajjad-shirazy** [comment]
seems there are some other issues. conjugate of 'comming':
{  
   "PastTense":"commed",
   "PresentTense":"coms",
   "Infinitive":"com",
   "Gerund":"coming",
   "Actor":"commer",
   "FutureTense":"will com"
}

and also:

coming => com 
moving => mov 
joking => jok 
poking => pok 
naming => nam 
aching => ach
tuning => tun 
bling => ble  
hazing => haz 
oozing => ooz 
gazing => gaz  
easing => eas 
dozing => doz 
raring => rar  
honing => hon 
gluing => glu
fuming => fum 
baling => bal 
muling => mul 
lazing => laz 
juking => juk 
zigging => zig 
razing => raz 
rewing => rew

**Comment by sajjad-shirazy** [comment]
conjugate of `planned`:
`{PastTense: "planned", PresentTense: "plannes", Infinitive: "planne", …}`

**Comment by spencermountain** [comment]
hey @sajjad-shirazy , I haven't gotten around to fixes these examples yet, but as of v11, there's now support in the api for defining custom irregular conjugations:
https://runkit.com/spencermountain/59f34c4fce71dc00133b8eee
cheers

**Comment by spencermountain** [comment]
holy, this is a really useful list. Going through some more for `12.3.0`
thanks again.

**Comment by spencermountain** [comment]
remaining:
```
nlp('the test message').debug()
```

**Comment by spencermountain** [comment]
think I got em all, let me know if you see any others
thanks
