### ISSUE TITLE
How to detect "Proper Nouns" ?

### ISSUE THREAD

**Issue by sebilasse** [spencermountain/compromise#398]
How about adding the tag "Proper" to the Noun‘s tagset ?

In my opinion it could be for the `Nouns`
`Uncountable | Organization | Name | Person | Place`

but perhaps should also be 
`Acronym`

and for `Uncountable` only if it follows a `Determiner` or `Possessive`

**Comment by spencermountain** [comment]
👍

**Comment by chrisdothtml** [comment]
👍 for this. Would be nice to be able to transform all proper nouns `toTitleCase`

**Comment by gagan-bansal** [comment]
Can we consider the noun that is not in dictionary is proper noun?

**Comment by gagan-bansal** [comment]
Thanks Spencer, I got your point.

**Comment by spencermountain** [comment]
hey, I've added support for `#ProperNoun` tag in `11.5.0`. It basically just runs-through the `people|places|orgs` after the tagger has run, and tags things as a ProperNoun.

it gets a little harder when you change the word, the tag should disappear.
i think i've mostly guarded against this, but who really knows.
lemme know if you see anything funny.
thanks.
