### ISSUE TITLE
BestTag is returning ClauseEnd for simple CSV inputs

### ISSUE THREAD

**Issue by IntegerMan** [spencermountain/compromise#432]
I ran into this last night. I believe I was doing something like:

`nlp('street, front, frontyard').terms().data()` and the output I was getting was the three nouns as expected, but my code was getting thrown off as BestTag on at least a few of them was being set as ClauseEnd despite them having the Noun or Adjective tag on them.

This is an odd input to give the algorithm, and my original plan was to do a split on comma, trim, then nlp call on each one to get the part of speech (I'm using the results as aliases for named objects in my system, but want to track adjectives and nouns separately).

It's not an insurmountable difficulty. In my case, I simply realized that since I'm relying on NLP for token parsing, I could just replace all commas with an empty string prior to invoking NLP, but I also easily could have just looked for the tag I wanted in the Tags collection instead of relying on BestTag. Still, ideally, these would not have BestTag of ClauseEnd despite the punctuation.

**Comment by IntegerMan** [comment]
I should also note that this was encountered on 11.1.0

**Comment by spencermountain** [comment]
hey Matt, got this fixed, but this bestTag method is still weird, can you find any other issues?
cheers
