### ISSUE TITLE
Invalid verbs

### ISSUE THREAD

**Issue by KevinGrandon** [spencermountain/compromise#448]
The following words, which in some cases are also nouns, are not considered to be valid verbs:
```
configure
enforce
implement
pin
reset
```

**Comment by spencermountain** [comment]
nice. thanks kevin

**Comment by spencermountain** [comment]
hey Kevin, added these to the lexicon of verbs, with the exception of 'pin', which will be caught by 'will pin, did pin, etc.' 
you can coerce it if you want, like this:
https://runkit.com/spencermountain/5a78a056af44fe0012df6789
Will be in `11.3.0`, this afternoon.
cheers!
