### ISSUE TITLE
Lexicon isn't resilient to inflections as given in Wiki

### ISSUE THREAD

**Issue by srikumarks** [spencermountain/compromise#449]
The [wiki example][ex] says the following -

```
var myWords={
  'university of toronto':'Organization',
  'girble':'CuteThing'
}
var r = nlp('he studied girbles at the University-of-Toronto', myWords)
r.match('#CuteThing').found
//true
r.organizations().length
//1
```

... which doesn't work. (installed version = 11.2.3)

`r.debug()` simply prints the following -

```
====
   --
   'he'                       - Pronoun, Noun, Singular
   'studied'                  - PastTense, Verb, VerbPhrase
   'girbles'                  - Noun, Plural
   'at'                       - Preposition
   'the'                      - Determiner
   'University'                - TitleCase, Hyphenated, Noun, Organization, Singular
   'of'                       - Hyphenated, Organization, Singular, Noun
   'Toronto'                  - Hyphenated, TitleCase, Singular, Noun, Organization
```

[ex]: https://github.com/spencermountain/compromise/wiki/Lexicon

**Comment by spencermountain** [comment]
oh hey, that's a good point. I think i muddled a few things in that example, didn't i.

...in order to know that it should inflect `girble`, it needs to know it's a noun, in addition to its given tag. I mean, how about this example...
```js
var words={
  nice: 'Foo'
}
```
that probably shouldn't inflect nice->"nices". hmm

we should at least, change that example ;)
thanks!

**Comment by spencermountain** [comment]
ya, this automated expansion of the lexicon has been completely rolled-back now in v12, and the docs have been update. Thanks for spotting the error.
cheers
