### ISSUE TITLE
people() fails to find common female names

### ISSUE THREAD

**Issue by sandro-pasquali** [spencermountain/compromise#450]
Hi, 

Node 9.5
npm 5.6
OSX 10.13

Using the "Will Smith demo" at http://compromise.cool/ ... I cleared the input and entered this text: `Mary is in the boat. Nancy is in the boat. Fred is in the boat. Jack is too.`

Only `fred` and `jack` were matched. I tried (unscientifically!) with various m/f combinations and the male names were almost always caught it seems, while female names were often not.

Thanks for the great library.

**Comment by spencermountain** [comment]
hey Sandro! Weird! looks like Mary and Nancy are both missing.
I'll add em in.
Lemme know if you can find others. Seems really weird to miss those two.

**Comment by sandro-pasquali** [comment]
I ran the list of female names here: https://github.com/AlessandroMinoccheri/human-names/blob/master/data/female-human-names-en.json

```
let results = [
    "Aaliyah",
    "Aarushi",
    "Abagail",

    ... ~2000 names ...

    "Zoey",
    "Zola",
    "Zora",
    "Zoya",
    "Zula",
    "Zuri",
    "Zyana"
].reduce((acc, fname) => {
    let match = nlp(`Can you ask ${fname} to join us?`).people().data();
    match.length ? acc.found.push(fname) : acc.notfound.push(fname);
    return acc;
}, {
    found: [],
    notfound: []
});

console.log(`Found: ${results.found.length} : NotFound: ${results.notfound.length}`);

// Found: 597 : NotFound: 1418

```
FWIW. 

https://gist.github.com/sandro-pasquali/6e95f7434e2609482473387a6b4a4221

**Comment by spencermountain** [comment]
hey! this is great!
i say we include all of these, minus the ambiguous ones like 'sky' and 'liberty'
lemme take a crack at this...
thank you!

**Comment by spencermountain** [comment]
hey Sandro, i've added a bunch of new names. I'm not sure how we developed those weird holes for names like mary and nancy, but I've nearly-doubled the name-list, using that human-names dataset, as well as [this one](https://names.mongabay.com/female_names_alpha.htm) and [this one](http://deron.meranda.us/data/census-derived-all-first.txt).
using our compression, it adds only about 3k to the total filesize.
it'll land in `11.3.0` this afternoon
cheers!

**Comment by spencermountain** [comment]
oh, now your script returns this:
`Found: 1324 : NotFound: 691`
📈

**Comment by sandro-pasquali** [comment]
Sweet! This is an important improvement. Thanks!
