### ISSUE TITLE
Using matched capture groups in replace?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [spencermountain/compromise#455]
Is it possible to take a capture group from a match, look up something and use it in the replace?

My attempts replace weirdly, and drop the last part of the sentence off.

```js
var items = { 2: { name: 'Simple Test Item' } }
var doc = nlp('Look at item 2.')
var match = doc.match('item #value')
match.replace(items[match.values(0).toNumber().out().trim()].name)
doc.out('html')
```
What is output.
```html
<span> 
  <span>
    <span class="nl-TitleCase nl-Infinitive nl-PresentTense nl-Verb nl-VerbPhrase">Look</span>
    &nbsp;<span class="nl-Preposition">at</span>
    &nbsp;<span class="nl-TitleCase nl-Comparable nl-Adjective">Simple</span>
    &nbsp;<span class="nl-TitleCase nl-Noun nl-Singular">Test</span>
    &nbsp;<span class="nl-TitleCase nl-Noun nl-Singular">Item</span>
    &nbsp;<span class="nl-NumericValue nl-Value nl-Cardinal">2</span>
  </span>
</span>
```

Expected HTML
```html
<span> 
  <span>
    <span class="nl-TitleCase nl-Infinitive nl-PresentTense nl-Verb nl-VerbPhrase">Look</span>
    &nbsp;<span class="nl-Preposition">at</span>
    &nbsp;<span class="nl-TitleCase nl-Comparable nl-Noun">Simple Test Item</span>
    <span>.</span>
  </span>
</span>
```

Similar problem when not using the value.

```js
var doc = nlp('Look at item 2.')
var match = doc.match('item 2')
match.replace('Simple Test Item')
doc.out()
```
The . should not be removed as it is not part of the match.

```js
var items = { 2: { name: 'Simple Test Item' } }
var doc = nlp('Look at item 2.')
var match = doc.match('item #value')
match.replace('Simple Test Item')
doc.out()
```

Ah it seems toNumber does something that interferes with the replace on the match.
Also it tokenizes the . as part of the term its next to.

This comes closer.
```js
var items = { 2: { name: 'Simple Test Item' } }
var doc = nlp('Look at item 2.')
var match = doc.match('item 2')
var id = match.term(1).normalize().out()
var item = items[id]
var name = item ? item.name : 'Unknown Item '+id
match.replace(name)
doc.out()
```

**Comment by spencermountain** [comment]
hey Liam, thanks for the issue.

yeah, i agree the period at the end of the sentence should remain, even after the last word has been replaced. Is that the primary issue?

this may be an easier way to do things:
```js
var doc = nlp('Look at item 2.');
doc.replace('item #value', 'Simple Test Item');
doc.debug();
```
what is your top-level goal? perhaps I can help clear things up.

**Comment by LiamKarlMitchell** [comment]
Hi Spencer,

The `.` being chomped is not the only issue.

I'm wanting to capture a value from a match, then use the captured value to look up the text to replace the term with.

I was initially wanting to do it like item:2 or item:3 with ```"item:#value"``` but it seems to tokenism on space.

And also when wanting to generate out the HTML output, is there a way to group terms into same tag in a span?


I could probably do it as just using regex but was interested with using a library like this to classify intent and meaning behind words, to have more engaging text based NPC interaction or something further down the line.

Perhaps using the library in this way is the wrong tool for this kind of task?

**Comment by spencermountain** [comment]
hey Liam, if you want to group two terms together, you can use `.lump()`.

if i understand correctly, this should do the trick?
```js
//parse full document
let doc = nlp(myText)
//grab your section, 'item x'
let captured = doc.match('item #Value').out('normal')
//replace it with something else?
doc = doc.replace(captured, 'item 10')
//lump those words together
doc.match('item 10').lump()
//output as html
doc.out('html')
```

**Comment by spencermountain** [comment]
lemme know if there's any other issues
