### ISSUE TITLE
Dates within words

### ISSUE THREAD

**Issue by jeffreyflynt** [spencermountain/compromise#456]
Hello,

Thanks for providing this library!

I am using the date parser and it recognizes Maycomb as a date of May.  Is there a way to only return dates for if it matches the whole word and not within a word?

Thanks

**Comment by spencermountain** [comment]
hey Jeffrey, whoa that should definitely not happen, i wasn't able to reproduce this though.
https://runkit.com/spencermountain/5a808631ac0ed40013fd1a18
is that word in a particular context, where you got it to get tagged as a date?
cheers

**Comment by jeffreyflynt** [comment]
Hey Spencer,

That was totally my fault.  My regex that highlights words was the issue, not the library.  It was matching strings within strings and not solely whole words.

Thanks
