### ISSUE TITLE
Add more LastNames

### ISSUE THREAD

**Issue by Garcia107** [spencermountain/compromise#459]
Hi there,
 I really love this repo but I was wondering, is there a way to 'import' a file like the one you have here
compromise/data/words/people/lastnames.js and add more lastnames, malenames and femalenames?

I now that I can add more using lexicon https://runkit.com/583f2a3dc534df0014136221/58d5d0e469bd5800151ed584 but what if I want to add like 1000 new names or something like that?

Can I just import a js file?

Thank's in advance

**Comment by scagood** [comment]
You could use a compromise's awesome plugin system (See: https://github.com/nlp-compromise/compromise-plugin).

Basic usage would be as follows:

Lets say your `index.js` files looked like so:
```js
const path = require('path');
const nlp = require('compromise');

nlp.plugin(require(path.resolve(__dirname, 'names.json')));

const tags = nlp('Has anyone seen Reid?').out('tags');

console.log(JSON.stringify(tags, null, 4));
```

Your `names.json` file could look like so:
```json
{
    "name": "Additional Names",
    "words": {
        "Reid": "FemaleName",
        ...More_names...
    }
}
```

The output when run would look something like so:
```json
[
    {
        "text": "Has",
        "normal": "has",
        "tags": [
            "TitleCase",
            "Verb",
            "VerbPhrase"
        ]
    },
    {
        "text": "anyone",
        "normal": "anyone",
        "tags": [
            "Possessive",
            "Noun"
        ]
    },
    {
        "text": "seen",
        "normal": "seen",
        "tags": [
            "Noun"
        ]
    },
    {
        "text": "Reid?",
        "normal": "reid",
        "tags": [
            "FemaleName",
            "FirstName",
            "Person",
            "Singular",
            "Noun"
        ]
    }
]
```

**Comment by Garcia107** [comment]
@scagood Thank you so much good sir. 🥇
