### ISSUE TITLE
First person conjugation problems

### ISSUE THREAD

**Issue by clabe45** [spencermountain/compromise#465]
The following code
`console.log(nlp('i am cool').sentences().toPresentTense().out());`

yields 
`i is cool`

I would expect the 'is' to be 'am'. This also happens with 'you'.
Also, `console.log(nlp('i be cool').sentences().toPresentTense().out());`
yields `i be cool`, but it conjugates fine if I change 'i' to 'he', for instance.

My version is 11.5.3

**Comment by spencermountain** [comment]
agh, nice one. Thanks Caleb, will look at this in the next release

**Comment by clabe45** [comment]
yep no problem
besides that, it is very impressive

**Comment by spencermountain** [comment]
hey Caleb, this is fixed on 11.6.0
cheers
