### ISSUE TITLE
Can't match pronouns in the sentence.

### ISSUE THREAD

**Issue by mateosilguero** [spencermountain/compromise#466]
Is there a way to get pronouns in a sentence ? 
"I am home" is no returning 'i' as a subject, or no another field.

**Comment by scagood** [comment]
Yes, there is!

You can use the [match function and syntax](https://github.com/spencermountain/compromise/wiki/Match-Syntax).

As an example:
```js
var nlp = require('compromise')
var pronouns = nlp('I am home')
    .match('#Pronoun')
    .out('array');
console.log(pronouns);
```

This will log the array:
```js
[
  'i'
]
```
Can I recommend trying some of the demos found on the website [compromise.cool](http://compromise.cool/) or on the one hosted here on git [nlp-compromise.github.io](http://nlp-compromise.github.io/website/) (I will note this last one is a tad out of date)

Other things of interest and/or note would be the [Wiki](https://github.com/spencermountain/compromise/wiki), this information, and a whole lot more can be found there!
[github.com/spencermountain/compromise/wiki](https://github.com/spencermountain/compromise/wiki).

Good luck in whatever project you have planned!

**Comment by mateosilguero** [comment]
Thanks !
