### ISSUE TITLE
sentences().isQuestion() is not a function?

### ISSUE THREAD

**Issue by warhost** [spencermountain/compromise#470]
Hey,
I would like to use the `isQuestion()` feature. I can see it is defined in compromise/src/subset/sentences/isQuestion.js, however I am getting 

> doc.sentences(...).isQuestion is not a function

Any ideas?

**Comment by spencermountain** [comment]
hey felix, ah sorry about that.
i will look at adding it in the next version
cheers

**Comment by spencermountain** [comment]
hey felix, this is fixed now in `11.7.0`
```js
nlp('Dogs are funny. Are they funny? Yes they are.').sentences().isQuestion().out('array')
//['are they funny']
```
cheers

**Comment by jhonnathanH** [comment]
In version  compromise@13.7.0 fail again
`Uncaught TypeError: Object(...)(...).sentences(...).isQuestion is not a function`

**Comment by spencermountain** [comment]
hey @jhonnathanH make sure you have installed [the sentences plugin](https://github.com/spencermountain/compromise/tree/master/plugins/sentences)
cheers
