### ISSUE TITLE
Error in Plugin example

### ISSUE THREAD

**Issue by differentsmoke** [spencermountain/compromise#471]
Hi,

I believe there is an error with the first pattern defined in the [plugin example](https://beta.observablehq.com/@spencermountain/compromise-plugins) in the docs.

I believe this line
```
        "the $TitleCase (era|epoch)": "TimePeriod", //'the Jurassic era'
```
should be
```
        "the #TitleCase (era|epoch)": "TimePeriod", //'the Jurassic era'
```

Right? (with a **#** not with a **$**)

This had me confused about what patterns were for, for a while.

**Comment by spencermountain** [comment]
hey Pablo, thanks. I almost went cross-eyed looking at that example.
Fixed it.
cheers.
