### ISSUE TITLE
Tagging and Plugin not working.

### ISSUE THREAD

**Issue by leninworld** [spencermountain/compromise#473]
Hi,

I could not get tagging and plugin working for me. Please find below examples.

(1) I find tagging is not working:

It is returning empty for doc11.match('#sayingthanks').out('tags'):

var nlp = require('compromise');
var doc11 = nlp('thanks');
var word11 = doc11.match('thanks').out('array');
    console.log("found: word11:" + word11 );
    doc11.match('thanks').tag("sayingthanks");
    console.log("found:" + doc11.match('#sayingthanks').out('tags'));

(2) I find plugin is not working:
Variables extract_words8, extract_words9, and extract_words10 are coming empty.

var nlp = require('compromise');
    var plugin3 = {
        tags:{
            'helpword':{
                isA: 'help'
            }
        },
        words:{
            'help': 'help',
            'help me': 'help'
        }
    };
   var plugin2 = {
        tags:{
            'RequestingQuestionword':{
                isA: 'Requestingword'
            }
        },
        words:{
            'could': 'Requestingword',
            'would': 'Requestingword',
            'will': 'Requestingword',
            'could you' : 'Requestingword',
            'would you' : 'Requestingword',
            'will you' : 'Requestingword'
        }
    };
nlp.plugin(plugin2);
nlp.plugin(plugin3);

    var extract_words8 = nlp("help me now").match("#help").out('array');
    console.log("extract_words8:" + JSON.stringify(extract_words8) );

    var extract_words10 = nlp("help me now").match("#helpword").out('array');
    console.log("extract_words10:" + JSON.stringify(extract_words10) );

    var extract_words9 = nlp("could you help").match("#RequestingQuestionword").out('text');
    console.log("extract_words9:" + extract_words9);

**Comment by scagood** [comment]
Hey @leninworld, 
Thanks for using compromise!

In your first example the way to get this working would be to use `SayingThanks` as opposed to `sayingthanks`, I'm not sure why this is, though, it may be worth investigating.

Here is a version (using capitals):
```js
const nlp = require('compromise');
const doc = nlp('thanks');

// Do the tagging
doc
    .match('thanks')
    // Note the capitals
    .tag("SayingThanks");

// Here is your output.
console.log(
    doc
        // Note the capitals
        .match('#SayingThanks')
        .out('tags')
);

// Output:
//  [ { text: 'thanks',
//      normal: 'thanks',
//      tags: [ 'PresentTense', 'Verb', 'VerbPhrase', 'SayingThanks' ] } ]
```

There are two issues in your second example, the first is that capital issue again, where `help` should be `Help` and `helpword` should be `Helpword`. The second issue is the way you cascade your tags in the plugins, in your example `'helpword': {isA: 'help'}` you're saying the tag `helpword` is a subset of `help`, when I assume you're actually meaning `help` is a subset of `helpword`.

Here is a patched version:
```js
const nlp = require('compromise');
const doc = nlp('thanks');

const plugin3 = {
    tags:{
     // 'Helpword': {isA: 'Help'},
        'Help': {isA: 'Helpword'}
    },
    words:{
        'help': 'Help',
        'help me': 'Help'
    }
};

const plugin2 = {
    tags:{
     // 'RequestingQuestionword': {isA: 'Requestingword'},
        'Requestingword': {isA: 'RequestingQuestionword'}
    },
    words:{
        'could': 'Requestingword',
        'would': 'Requestingword',
        'will': 'Requestingword',
        'could you' : 'Requestingword',
        'would you' : 'Requestingword',
        'will you' : 'Requestingword'
    }
};

nlp.plugin(plugin2);
nlp.plugin(plugin3);

const extract_words8 = nlp("help me now")
    .match("#Help")
    .out('array');

console.log(
    "extract_words8:" + JSON.stringify(extract_words8)
);
//extract_words8:["help","me"]

const extract_words10 = nlp("help me now")
    .match("#Helpword")
    .out('array');

console.log(
    "extract_words10:" + JSON.stringify(extract_words10)
);
//extract_words10:["help","me"]

const extract_words9 = nlp("could you help")
    .match("#RequestingQuestionword")
    .out('text');

console.log(
    "extract_words9:" + extract_words9
);
//extract_words9:could you
```

Hope this helps,
Seb.

**Comment by scagood** [comment]
@leninworld did this solve the problem?

**Comment by leninworld** [comment]
Got it. Thank you!
