### ISSUE TITLE
Bug: tag.replace is not a function

### ISSUE THREAD

**Issue by iq-dot** [spencermountain/compromise#474]
I am repeatedly getting tag.replace is not a function using this piece of text as the input:

_Iran's President Mocks 'Tradesman' Trump In National Speech "How can a tradesman, a merchant, a building constructor, make judgments about international affairs?"
That's how Iranian President Hassan Rouhani dismissed US President Donald Trump.
His jibes came amid U.S. threats to abandon the landmark nuclear deal with Tehran.
Rouhani unleashed a series of insults during a national televised speech.
In May, Trump will once again have to decide whether to recertify the Iran deal to Congress.
If he doesn't, he could begin the process to reversing the deal._

Any help on this matter?

**Comment by spencermountain** [comment]
hi Iqbal, happy to help. I don't see this error when I parse that text, can you give me more information?

**Comment by iq-dot** [comment]
Hi Spencer, sorry seemed to have missed this response.

So I am using the Core NLP server which runs in a docker container and I run it with 4 threads.

The exact distribution I am using is: stanford-corenlp-full-2018-02-27

This is the Java command I use to start the server up:

java -cp "*" -mx4g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port $PORT -timeout 15000 -annotators "tokenize" -preload  "tokenize,ssplit,pos,lemma,ner" -threads 4

**Comment by spencermountain** [comment]
hi Iqbal, are you using stanford-corenlp? this is the wrong repository, this is a javascript library.
Yeah, i'd need more information before being able to help
cheers!

**Comment by scagood** [comment]
Do you think you could give us a small snippet of your code as that would be the only way (that I can see) to move this issue forward :smile:

**Comment by iq-dot** [comment]
Sure, it's nothing complicated, I can't actually replicate the error, so I am suspecting it maybe related to some encoding issue, the text data was being pulled from a message queue.

Here is the snippet:

```
    const nlpText = nlp(text);
    const singular = nlpText.nouns().data().map(k => k.singular)
```

Feel free to close this issue until I can replicate it again.
