### ISSUE TITLE
Ngram counts are sometimes wrong

### ISSUE THREAD

**Issue by firemuzzy** [spencermountain/compromise#476]
I have noticed that for some phrases the ngram counts are greater than the number of occurrences in the text. 

Here is a an example https://runkit.com/firemuzzy/5af1d67875914d001263570c

If you look at the phrase `free for`, the provided text has 2 occurrences, but nlp-compromise returns a count of 3. Coincidentally the phrase `free` occurs 3 times, I wonder if something is messing up in the normalization.

At the same time the phrase `just not user friendly` only occurs 1 time, but nlp-compromise reports it with a count of 2. That discrepancy completely puzzles me.

Am I missing something with how ngrams works?

**Comment by spencermountain** [comment]
hey Michael, nice find.
I'll take a look at fixing this this week.
thanks

**Comment by spencermountain** [comment]
ha! oh wow, it's the contraction - `It's free for`.
it's creating the gram `[is] free for`.
this is a great bug, will fix it today.
cheers

**Comment by spencermountain** [comment]
fixed in `11.8.0`
thanks!
