### ISSUE TITLE
lemmatization

### ISSUE THREAD

**Issue by findli** [spencermountain/compromise#480]
Example from [wiki usage](https://github.com/spencermountain/compromise/wiki/Usage) 

nlp.text('He ate the eggs.').out('root')
// 'he eat the egg'

but real output is 'he ate the eggs'
so the 'ate' doesn't became 'eat'.

**Comment by spencermountain** [comment]
(handled in slack chat)
```js
var doc=nlp(myText)
doc.verbs().toInfinitive()
doc.nouns().toSingular()
doc.out('text')
```
