### ISSUE TITLE
POS Tagging performance data?

### ISSUE THREAD

**Issue by giorgio79** [spencermountain/compromise#485]
Do you have data on POS tagging performance?

- en-pos for example is 96.43% https://github.com/FinNLP/en-pos
- Stanford POS is around 97% https://nlp.stanford.edu/~manning/papers/CICLing2011-manning-tagging.pdf

**Comment by spencermountain** [comment]
hey György, yeah a little bit.

https://beta.observablehq.com/@spencermountain/compromise-accuracy
https://github.com/spencermountain/compromise/wiki/Accuracy

**Comment by giorgio79** [comment]
Oh wow! Really cool. Loving the pragmatism... :)
