### ISSUE TITLE
chinese version

### ISSUE THREAD

**Issue by ahkimkoo** [spencermountain/compromise#487]
期待中文版本

**Comment by spencermountain** [comment]
你好！ 是的，这是个好主意。 我不是中国的专家，但这是一个令人兴奋的想法!

**Comment by linonetwo** [comment]
Hi, I've made a Chinese POS tagger in pure JS, will that help?
https://github.com/linonetwo/segmentit

**Comment by spencermountain** [comment]
@linonetwo neat!!
very cool library.
