### ISSUE TITLE
noun-phrase article

### ISSUE THREAD

**Issue by aviv** [spencermountain/compromise#488]
It's currently possible to get articles for a noun, but it doesn't seem possible to get the correct article/s for a phrase like "open door" or an adjective on its own. Is this something that would be easy to add, or is there currently a way to do this that I'm missing?

**Comment by spencermountain** [comment]
oh hey, this is correct. I never thought about this.

hmmm, yeah, i can't think of a clever way to run-around this right now.

we had support for notions of 'noun phrases' in previous versions, which is probably something we should return to. 

this is a great example, let me think about it for a bit.

**Comment by aviv** [comment]
thanks for the quick response, and for taking a look!

**Comment by spencermountain** [comment]
hey Aviv, this is not a good solution, but something you can use until this is handled in a better way:
```js
let doc = nlp('the open door');
doc.match('#Adjective #Noun').lump(); 
console.log(doc.nouns().data());
```
will leave this open, to handle this better
cheers

**Comment by owendall** [comment]
Yes, the noun phrase thing would be VERY useful...

**Comment by spencermountain** [comment]
hey, this is now possible in `12.2.0`, would love some eyes on it
https://runkit.com/spencermountain/5de8231a937ebe00199b3069
let me know if you see any issues!

**Comment by aviv** [comment]
thanks @spencermountain !
