### ISSUE TITLE
strip Honorifics in .people()

### ISSUE THREAD

**Issue by josiahbryan** [spencermountain/compromise#491]
Minor bug report here, but it seem's to be making "Lady" part of the noun phrase for "Melania Trump", as shown in this example:

* Code: `console.log(nlp("First lady Melania Trump").nouns().out('array'));`
* Prints: `[ 'lady melania trump' ]`
* Should print: `[ 'melania trump' ]`

**Comment by spencermountain** [comment]
hey, added an `honorifics` method in normalize, here's how you can do that now:
https://runkit.com/spencermountain/5b281b292744f80012c4be21
lemme know if you see anything weird,  `v11.10.1`
cheers
