### ISSUE TITLE
Bug: [space]... breaks normalize();

### ISSUE THREAD

**Issue by vin-ni** [spencermountain/compromise#492]
Hi, 
I found a bug in the normalize function. When I type:

`let string = nlp("Let's do something about this ...").normalize().out("text");
console.log(string);`

It returns 
` Let us do something aboutundefinedthisundefined` 
instead of `Let us do something about this ...`

Anyone has an idea why this is caused?

**Comment by spencermountain** [comment]
whoa, nice find!
that's a good one.

fixed the main bug, but found another one with the ellipses like that. Will leave this open until i fix it, then will publish the fix

sansho looks fun!
cheers

**Comment by vin-ni** [comment]
thanks man :)
hit us up if you're ever in Berlin

**Comment by spencermountain** [comment]
hey, fixed in `11.10.0`, lemme know if you see anything funny.
cheers
