### ISSUE TITLE
Clear plugin

### ISSUE THREAD

**Issue by lukeyt** [spencermountain/compromise#493]
There does not seem to be any way to clear a previously loaded plugin.  For instance if I use the example:

`let plugin = {
    words: {
      'trex': 'Dinosaur'
    },
    tags: {
      Dinosaur: {
        isA: 'Animal'
      }
    }
  };
 nlp.plugin(plugin);
 let doc = nlp('i saw a HUUUUGE trex');

doc.match('#Dinosaur').out('normal')// 'trex'`

There doesn't seem to be any way to unload 'plugin', so that 

doc.match('#Dinosaur').out('normal')

Will always return 'trex'.  Am I missing something?  I want to be able to switch out a plugin and load another one without reloading the browser window.

**Comment by spencermountain** [comment]
hey @lukeyt yeah, you can do this with `.clone()`, but it's a little awkward.

```js
let nlp2 = nlp.clone();
nlp.plugin({
  words: {
    trex: 'plugin'
  }
});
nlp('trex').debug();
nlp2('trex').debug();
```
cheers

**Comment by lukeyt** [comment]
Great - thank you @spencermountain - I will give it a go!

**Comment by lukeyt** [comment]
I have tried this - however its not quite working as I expected after all -

var nlp2 = nlp.clone();

nlp2.plugin({
  words: {
    trex: 'plugin'
  }
});

will error with nlp2.plugin is not a function.  What I had hoped was that I could use the approach above to clone nlp each time I wanted to load a different plugin, discarding the clone each time.  But it seems clone does not clone the methods (or at least the plugin method)?

**Comment by spencermountain** [comment]
yeah, rats. i was afraid of that.

check out [this issue](https://github.com/spencermountain/compromise/issues/257), where someone reloads the library using require-reload.

i can look at cleaning up the library clone stuff, but it's behind a backlog right now.

**Comment by playground** [comment]
Is there a solution to clear nlp plugin?

**Comment by spencermountain** [comment]
hey @playground yes, `.clone()` should work as expected now:
https://observablehq.com/@spencermountain/compromise-constructor-methods
cheers

**Comment by playground** [comment]
so how would you do this?
nlp.plugin(plugin1) has the origin content, would like to clear it and reload it with new content such as nlp.plugin(plugin2)

**Comment by spencermountain** [comment]
yes, please read the [v12 release notes](https://github.com/spencermountain/compromise/wiki/v12-Release-Notes) and the documentation for [.clone()](https://observablehq.com/@spencermountain/compromise-constructor-methods)
