### ISSUE TITLE
How to get Part-Of-Speech tags 

### ISSUE THREAD

**Issue by Isaacroyal** [spencermountain/compromise#498]
Hi there, am new to compromise js
i need some help on how I can get POS tags from a sentence.
Thanks.

**Comment by spencermountain** [comment]
hi @Isaacroyal try `nlp('this is a sentence').out('tags')`
cheers

**Comment by Isaacroyal** [comment]
I have tried it but it outputs alot stuff I don't need...
Is there a way I can get a basic output 
For example something like;
Can - verb
I - pronoun
Have - verb 
Some - Determiner 
Gum - noun
Lets say If my sentence is "Can I have some gum"

**Comment by spencermountain** [comment]
yeah, if you just want on tag, this should do the trick
https://runkit.com/spencermountain/5b29579882fcec00123e80ed

**Comment by Isaacroyal** [comment]
@spencermountain thank you very much, this works perfectly.
