### ISSUE TITLE
continent-support in .places()

### ISSUE THREAD

**Issue by monbro** [spencermountain/compromise#501]
I am processing this sentence (tested on http://compromise.cool/)

> This morning I discovered this awesome documentary about the real politics in nicaragua in namibia in Africa in Germany in south africa.

Unfortunately when extracting places it is not extracing 'africa' as a country / place. Is there any reason for this? The topics I get:

> south africa germany namibia nicaragua

**Comment by spencermountain** [comment]
hey Micheal, I agree that africa should be a place, and south africa should be a country.

seems like south africa is working, but perhaps continents are missing
https://runkit.com/spencermountain/5b4f4fade59e320012db2fef

i'll add em in, thanks.

**Comment by spencermountain** [comment]
hey, added them in 11.12.0.
thanks.
