### ISSUE TITLE
.adjectives() missing on the website

### ISSUE THREAD

**Issue by monbro** [spencermountain/compromise#502]
Hey first I was a bit confused, on http://compromise.cool/ I see adjectives() in the tree diagram, but not within the examples for testing. As you want to demonstrate functionality on the website / doc, I think it would be good to add this one to the texting text box too.

**Comment by spencermountain** [comment]
hey Micheal, yeah i guess so.
you can also try things out [like this](https://runkit.com/spencermountain/5b4f50ab2356bf00125254dc)

(i think `.adjectives()` simply runs `.match('#Adjective')`)
cheers

**Comment by spencermountain** [comment]
hey Michael, i've updated the website and docs.
thanks/
