### ISSUE TITLE
nlp().verbs().to... doesn't persist

### ISSUE THREAD

**Issue by alexluong** [spencermountain/compromise#507]
Hi,

So I'm trying to manipulate a text to change all verbs to infinitive forms and all nouns to singular. Here's my code:

```javascript
const sentence = nlp(sentenceContent).normalize()

sentence.nouns().toSingular()
sentence.verbs().toInfinitive()

const words = sentence.words().out("array")
console.log(words)
```

The result I got was that all nouns were indeed changed to singular form. However, the verbs form didn't.

With a little more inspection:

```javascript
console.log(sentence.nouns().out("array")
sentence.nouns().toSingular()
console.log(sentence.nouns().out("array")

// The 2 results are different
```

and

```javascript
console.log(sentence.verbs().out("array")
sentence.verbs().toInifinitive()
console.log(sentence.verbs().out("array")

// The 2 results are the same
```

confirm my notion.

I wonder if this is the intended behaviour. Would love to hear your opinions on how I can achieve my end result. Regardless, I really enjoy using `compromise` so far. It's an awesome library. Great works guys!! Thanks.

**Comment by spencermountain** [comment]
yeah, you know, I had a test failing where this exact thing was happening.
This is a (bad) bug.

it's something about how the subclasses carry-around mutated objects. It's a real mess. 
I have some [big-ideas](https://github.com/spencermountain/compromise/tree/new-terms-object/src) about handling this in a smarter way, but it is a big change and needs some time.
in the mean-time, it appears this ordering works:
```js
let doc = nlp('i walked to the stores')

doc.verbs().toInfinitive();
doc.nouns().toSingular();

doc.debug();
```

and worst-case scenario, you can flatten it back into text, and lose all the dangling pointer stuff:
```js
let doc = nlp('i walked to the stores')
doc.doFirstThing()
let doc2=nlp(doc.out('text'))
doc2.doSecondThing()
```
 ¯\_(ツ)_/¯

**Comment by alexluong** [comment]
Thank you for your response. That's quite odd that the order of actions made such a difference.

Anyway, I'll check to see if that order works. Thanks again for your help.
