### ISSUE TITLE
Documentation - Link to 'as part of the unit tests' is broken in README.md

### ISSUE THREAD

**Issue by thelordoftheboards** [spencermountain/compromise#509]
Readme:

https://github.com/spencermountain/compromise/blob/master/docs/README.md

The link labelled 'as part of the unit tests' points to:

https://github.com/spencermountain/compromise/blob/master/tests/unit/docs/docs.test.js

But that location does not seem to exist.

**Comment by spencermountain** [comment]
fixed on dev branch, thanks
