### ISSUE TITLE
nlp('posts').nouns().out() returns undefined

### ISSUE THREAD

**Issue by HristoKolev** [spencermountain/compromise#510]
Is this a bug?

Package version: "compromise": "^11.12.0",
Node version: v10.2.1

**Comment by spencermountain** [comment]
hey Hristo, if you run `nlp('posts').debug()`, (or `.out('tags')`) you can see it's tagging that word alone as a verb. you can co-erce it as a noun like this:
```js
let lexicon={post:'Singular'}
nlp('posts',lexicon).nouns().out()
```
cheers

**Comment by HristoKolev** [comment]
Thank you. It was my fault for not understanding how the API works.
