### ISSUE TITLE
added words are not detected when pluralised

### ISSUE THREAD

**Issue by 7ammer** [spencermountain/compromise#513]
Below I have added `trex`. A match is found for 'trex' but when I search for `trexes` no match is found.
Is this by design? If so, to include these scenarios will I need to add the plural words to the words object or is there some magic that I don't know about that checks for the plurals for me.

Cheers :)

```
let nlp = require('compromise');

var plugin = {
  words: {
    brontosaurus:'Dinosaur',
    trex: 'Dinosaur'
  },
  tags: {
    Dinosaur: {
      isA: 'Animal'
    },
    Animal: {
      isA: 'Noun'
    }
  }
};
nlp.plugin(plugin);
nlp('trex').match('#Dinosaur').data() // match found
nlp('trexes').match('#Dinosaur').data() // no match

```

**Comment by spencermountain** [comment]
hi James, yeah this is a little awkward. With custom tags, like Dinosaur, there's no way to know if a dinosaur is a Singular Noun.. 
It does, however, inflect words in the lexicon automatically if they have the `Singular` tag - i know this is a little-bit weird.
```js
let lexicon={post:'Singular'}
nlp('posts',lexicon).nouns().out()
```

either way, you could always run your lexicon through compromise's `toPlural()` manually, before entering them in, like

```js
let myDiosaurs=['trex', 'brontosaursus']
myDinosaurs.map(d=>nlp(d).tag('Sigular').nouns().toPlural().out())
//['trexes','brontosauri']
```
¯\_(ツ)_/¯

**Comment by 7ammer** [comment]
Brilliant! This solves my issue.
Thanks! 👍
