### ISSUE TITLE
Verb identified as noun when there is &nbsp;

### ISSUE THREAD

**Issue by damianof** [spencermountain/compromise#514]
nlp(`I was flying&nbsp;`).nouns().out('array')

Maybe need to parse html entities.

Also, seems outputting lowercase:
nlp(`I was flying to Rome`).nouns().out('array')

will return ['rome'] instead of ['Rome']

**Comment by spencermountain** [comment]
hello, yeah. compromise does not parse html entities, and expects text to be pre-formatted.

the .out('array') is expected behaviour, it is outputting normalized versions of the text. for different outputs, please consult https://beta.observablehq.com/@spencermountain/compromise-output
cheers
