### ISSUE TITLE
Difference between topics and nouns ?

### ISSUE THREAD

**Issue by gg4u** [spencermountain/compromise#516]
WOW! First of all, my congratulation @spencermountain . And also, I like it a lot your CV presentation page, it sounds funny and bring some color!

I've got a question for a use case of library:

I would like to parse topics out of blogs. I  tried with some texts, in some cases topics return an empty array, while nouns() works its way.

How are topics defined? 

Best ideal case for me, it would be to attempt "wikification" of topics - so attempt that a topic matches a topic in wikipedia. 

But since it runs in a client, not sure how it could make a match. Neverthless, I'd like to better understand how to carve out topics, or if possible to set up own rules (or train own rules).

Maybe you can share hints since I 've found out you're behind wtf_wikipedia project, too!

Thank you!

**Comment by spencermountain** [comment]
hey, thank you Luigi.

yeah, .topics is just `people()+places()+organizations()`. you can read a bit more about it [here](https://beta.observablehq.com/@spencermountain/topics-named-entity-recognition). That would be what i'd use for the wikification idea. Nouns has too much stuff like pronouns, or whatever.

yeah, wtf_wikipedia may be helpful. that follows redirects and things.

this should get you started:
https://runkit.com/spencermountain/5b8ae5d5856f980012293cdd

cheers
