### ISSUE TITLE
Bear interpreted as verb instead of noun  

### ISSUE THREAD

**Issue by bikibird** [spencermountain/compromise#517]
nlp("Alice was eaten by a bear.").out("terms")

Tags bear as a verb instead of as a noun. 

compromise v11.12.0

**Comment by spencermountain** [comment]
thanks, good find. It should recognise the `a + foo'` pattern
please bear with me while I change it (sorry)

**Comment by bikibird** [comment]
Bear in mind that I'm very appreciative of this library.

**Comment by spencermountain** [comment]
fixed in `11.12.2`
