### ISSUE TITLE
Unrecognised/incorrect verbs

### ISSUE THREAD

**Issue by cmann1** [spencermountain/compromise#520]
**adapted** - isn't recognised as a verb.
**attempted** - returns incorrect forms:
Actor: "attempter"
FutureTense: "will attempte"
Gerund: "attempting"
Infinitive: "attempte"
PastTense: "attempted"
PresentTense: "attemptes"

**Comment by spencermountain** [comment]
thanks @cmann1 will check it out

**Comment by spencermountain** [comment]
fixed in `11.12.1`
