### ISSUE TITLE
Prevent copying methods

### ISSUE THREAD

**Issue by andeanfog** [spencermountain/compromise#525]
1) Copying methods individually is slow

Extending objects one property at a time is resource intensive, because it results in many redundant hidden classes being created behind the scenes.

`Object.defineProperties` and `Object.assign` can be used as an alternative to copying methods individually. You can polyfill those functions for users of older versions of JS.

2) Copying methods is not necessary

It is not required to copy methods to implement inheritance. This can be achieved by making an object a parent of the other in the [prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain). By doing this, one object can access the methods of its parent without having to copy them.

**Comment by spencermountain** [comment]
thanks @andeanfog i agree.
is compromise doing this? Where? 
somewhere in `.clone()`?
cheers

**Comment by andeanfog** [comment]
Code including but not limited to:

https://github.com/spencermountain/compromise/blob/de152cb78fa6b17d86a2e32d6d3cdfddfa59944d/src/subset/nouns/noun.js#L89-L91

https://github.com/spencermountain/compromise/blob/de152cb78fa6b17d86a2e32d6d3cdfddfa59944d/src/terms/methods/split.js#L110-L112

https://github.com/spencermountain/compromise/blob/de152cb78fa6b17d86a2e32d6d3cdfddfa59944d/src/terms/methods/tag.js#L51-L53

**Comment by spencermountain** [comment]
oh hey! Yeah I could use some help with this. Thanks.
I started doing this when I saw all the stuff babel created when I used `class`. It was a huge amount of boilerplate each time. 
Then i thought i'd save some bytes by not repeating `.prototype` each time, so I looped it around at the end of the file.I thought i was being clever.

do you recommend this instead?
```js
const myClass=function(){}
myClass.prototype.foo=function(){}
myClass.prototype.bar=function(){}
```
i have no idea what is happening under the hood, ever.
thanks for your help

**Comment by andeanfog** [comment]
The idea is to make sure that methods are defined for once per type definition rather than once per instance.

In order to do that, the idea is to define a type that contains all the desired methods, and then create instances of that.

**Comment by spencermountain** [comment]
hey, can I get your advice on something?
how would you impliment this?
```js
class Parent {
  children(){
    return new Children(this)
  }
}

class Child extends Parent {
  childFn(){}
}
```
you can see `Parent` needs to have a method that returns a sublassed object.

This is the pattern we use for `Doc.nouns()` and so forth, it was a real head-scratcher

**Comment by spencermountain** [comment]
using `Object.assign(Doc.prototype, methods)` pattern in v12
cheers
