### ISSUE TITLE
nlp.text is not a function

### ISSUE THREAD

**Issue by maimike** [spencermountain/compromise#529]
var nlp = require('compromise')

nlp.text('He ate the eggs.').out('root')

error: 

> 
> TypeError: nlp.text is not a function
>     at Object.<anonymous> (/Users//backend/server/abc.js:3:5)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (

**Comment by spencermountain** [comment]
oh, this is the old api. looks like some old docs. sorry bout that.
working call:
```
nlp('he ate the eggs').out('root')
```
cheers
