### ISSUE TITLE
Normalization: verbs option not working

### ISSUE THREAD

**Issue by BPreisner** [spencermountain/compromise#530]
const nlp = require('compromise')

settings = {
   whitespace: true,
   case: true,
   numbers: true,
   punctuation: true,
   unicode: true,
   contractions: true,
   acronyms: true,
   parentheses: true,
   possessives: true,
   plurals: true,
   verbs: true,
   honorifics: true
};

let output = nlp('He ate the eggs because he wanted to do this.').normalize(settings).out('normal');

console.log(output);

//he ate the egg because he wanted to do this.

**Comment by spencermountain** [comment]
hi, yeah sorry. this is a really weird bug. it's the same as #507 .
gonna look at supporting this much better in v12, but for now, you can do this:
```js
settings = {
  whitespace: true,
  case: true,
  numbers: true,
  punctuation: true,
  unicode: true,
  contractions: true,
  acronyms: true,
  parentheses: true,
  possessives: true,
  plurals: true,
  honorifics: true,
};

let doc = nlp('He ate the eggs because he wanted to do this.').normalize();
doc.verbs().toInfinitive();
doc.nouns().toSingular();
let output = doc.out('normal');
console.log(output);
//he eat the egg because he want to do this.
```
cheers
