### ISSUE TITLE
Is it possible to extract all questions from a piece of text?

### ISSUE THREAD

**Issue by shamoons** [spencermountain/compromise#532]
I tried:

```
  let document = nlp(transcript);
  let normalText = document.questions().out();
  console.log(normalText);
```

but that yields `undefined`.

**Comment by spencermountain** [comment]
hi Shamoon, yeah this should work, it seems to work here:
https://runkit.com/spencermountain/5bce2b093b24aa0012be439d

can you find an example of a question it's missing?
cheers
