### ISSUE TITLE
False positive when detecting questions

### ISSUE THREAD

**Issue by shamoons** [spencermountain/compromise#533]
https://runkit.com/shamoons/false-positive-compromise

```
const nlp = require('compromise')

let res = nlp('Let me run get a price take about 5-10  minutes to process and then I\'ll send you what I got.').sentences().isQuestion().out('array')

console.log(res)
```

This is being detected as a question, when it is evidently not.

**Comment by spencermountain** [comment]
nice find!
Relevant code is [here](https://github.com/spencermountain/compromise/blob/master/src/subset/sentences/isQuestion.js) if anyone wants to jump on this. Otherwise, happy to take a look

**Comment by shamoons** [comment]
I'm on it

**Comment by shamoons** [comment]
@spencermountain - when I `console.log` to debug, nothing prints out when running `yarn test`. Any tips?

**Comment by spencermountain** [comment]
@shamoons oh right, i think that test-reporter disables them, you can see console logs if you do
 `yarn test:spec`
i should fix that...
