### ISSUE TITLE
extra space in contraction

### ISSUE THREAD

**Issue by shamoons** [spencermountain/compromise#536]
https://runkit.com/shamoons/compromise-arbitrary-space

```
const nlp = require('compromise');
let text = `It doesn't matter if I spoke at 4:40 p.m. Or or if you submit well we're going to do the processing.`

let sentenceDoc = nlp(text).normalize({ contractions: false }).out();

console.log(sentenceDoc)
```

This results in `it doesn't  matter if i spoke at 4:40 p.m. or or if you submit well we're  going to do the processing.`

See the extra space added after `doesn't`

**Comment by spencermountain** [comment]
good find!

**Comment by spencermountain** [comment]
got it, `11.12.2`.
