### ISSUE TITLE
Debug() broken?

### ISSUE THREAD

**Issue by SankarshanDudhate** [spencermountain/compromise#541]
Hi there,
   The latest build seems to have broken the debug() function. It gives all sorts of errors like "TypeError: Cannot read property 'TitleCase' of undefined" and other things related to tags. It definitely worked in some really old build (probably dated back to last year ;) but the new one just throws errors.

It doesn't seem to work on https://beta.observablehq.com/@spencermountain/compromise-tutorial-2 either (sorry for hijacking the live code). Here's a screenshot:
![screenshot 71](https://user-images.githubusercontent.com/18144503/47949686-858f7200-df6d-11e8-8d92-73b1a0f7018e.png)

Any thoughts?

**Comment by spencermountain** [comment]
hi Sankarshan, thanks for the issue.
I think there may be some confusion with that 'live editor'. It moves data around in some weird ways.
here's `.debug()` working as normal. It is not very useful on the client-side, right now ;(
https://runkit.com/spencermountain/5be055cd7fe3b10012e618d9

but the titlecase error is just an implementation of that observablehq.com demo
cheers!
