### ISSUE TITLE
'length' as Noun

### ISSUE THREAD

**Issue by SankarshanDudhate** [spencermountain/compromise#542]
Hi again,
    Here's an example:

        var r = nlp( "It's length is good" );
        
        console.log( JSON.stringify( r.match("length").verbs().conjugate() ));

    It outputs: 

[{"PastTense":"lengthed","PresentTense":"lengths","Infinitive":"length","Gerund":"lengthing","Ac...        

    which is not correct. Also, the conjugates list should also include the noun form, don't you think?

   Regards,
Sankarshan

**Comment by spencermountain** [comment]
hi Sankarshan, yes I think you're correct.
In my opinion, `length` should be a noun, and shouldn't appear in `.verbs()` at all.
Does that make sense?

**Comment by SankarshanDudhate** [comment]
Yes that sounds okay to me... It'd also be great if  `conjuagte()` shows the Noun Form of the verb. But it's not a necessary thing.

**Comment by spencermountain** [comment]
yeah, good idea.
i'll keep this open for the 'length' tagging issue
cheers

**Comment by spencermountain** [comment]
hey Sankarshan, we have a more reasonable response for this in v12, but it is still not perfect. `It's` is meant to be `its`, and the tagger is looking for a contraction `it is length is good`

this version works as expected:
```
var r = nlp("Its length is good")
console.log(r.verbs().conjugate())
```
cheers
