### ISSUE TITLE
False positives for questions

### ISSUE THREAD

**Issue by shamoons** [spencermountain/compromise#544]
`I have one two, three, four five six properties, which came on the market in the month.`
`Probably the renovation right away from the amount of work, which has been done to the property.`
`I think that the number one quite comfortable looking at the two properties, which I'm working on now.`

https://runkit.com/shamoons/5be45bbe8a3ee40012f35943

**Comment by spencermountain** [comment]
thanks, good find.

**Comment by shamoons** [comment]
I can work on fixing these @spencermountain

**Comment by spencermountain** [comment]
got it fixed in `11.12.4`
