### ISSUE TITLE
toPositive() bug ? 

### ISSUE THREAD

**Issue by compromizer** [spencermountain/compromise#545]
https://runkit.com/5bc948b3e9763f001279afdf/5bfe12a017db5c0012d9d14e

require("compromise") //11.12.3
nlp('Dear Miss Hoover, you do not have Lyme disease').verbs().toPositive().out()

// " do not have"

**Comment by spencermountain** [comment]
oh yeah, this one is another case of transitive `.replace`. 
will be addressed in version 12.

**Comment by spencermountain** [comment]
hey @compromizer - this works now in `v12.2.0`

https://runkit.com/spencermountain/5de8240a6bec1a001a8b5904
cheers
