### ISSUE TITLE
nlp() collapses number sentences. 

### ISSUE THREAD

**Issue by juheeuu** [spencermountain/compromise#547]
Hello, I have some problem,
Here's an example:

    var testText = nlp( "hello. 1234." );
    
    console.log(testText.terms().data());

I want to get `["hello.", "1234."]`, 
But I the result is just `["hello."]`.

How can I resolve this problem? 
I'm very happy if you resolved this problem :) 

Thank you!
Juheeuu

**Comment by spencermountain** [comment]
hi juhee! Yes, good find. 
I am happy to look at this problem.
thanks

**Comment by spencermountain** [comment]
hi, this should be fixed in `11.12.4`
thank you
