### ISSUE TITLE
out('tag') multi word nouns

### ISSUE THREAD

**Issue by themaincharacter** [spencermountain/compromise#549]
Having trouble getting compromise to output the tags of a multi word noun.
EX:
```
let plugin = { 
  words: { red sea : ["Noun"] } ,
  tags: {}
}
...
console.log(nlp('red sea is a noun.').nouns().out('tags'));
```
yields: 
```
{text: "red", normal: "red", tags: Array(2)}normal: "red"tags: (2) ["Noun", "Singular"]text: "red"...
{text: "sea", normal: "sea", tags: Array(2)}normal: "sea"tags: (2) ["Noun", "Singular"]text: "sea" ...
{text: "noun.", normal: "noun", tags: Array(2)}normal: "noun"tags: (2) ["Noun", "Singular"]text: "noun."...
```
expected:
```
{text: "red sea", normal: "red sea", tags: Array(2)}normal: "red sea"tags: (2) ["Noun", "Singular"]text: "red sea"...
{text: "noun.", normal: "noun", tags: Array(2)}normal: "noun"tags: (2) ["Noun", "Singular"]text: "noun."...
```

I realize this may be a strange use case but I am in a situation where I need to get the other tags from all nouns in a given sentence.
Like this:
```
nlp(text)
        .nouns()
            .toSingular()
            .toLowerCase()
            .out('tags')
            .map((noun: any) => {
                return [noun.text]
                    .concat(noun.tags)
                    .filter(posNoun => !this.nounTypeFilters.includes(posNoun));
            })
```

**Comment by spencermountain** [comment]
hi @themaincharacter yeah, this is a awkward situation. I'm trying to redesign the `.out()` methods in a future version that would improve this.

The good news is the information is there, and you can shape it manually with `.map`:
```js
let plugin = {
  words: {
    'red sea' : ['Noun']
  },
  tags: {}
};
nlp.plugin(plugin);
let arr = nlp('red sea is a noun.').nouns().map((ts) => ts.out());
console.log(arr);
//[ 'red sea', ' noun.' ]
```
this is sneaky because it's reaching into the internal api, but that's how i'd do it.
cheers

**Comment by themaincharacter** [comment]
@spencermountain Thanks for your response!

Sorry to bring this up after its been closed but I just wanted to clarify. Currently, there is no way to get metadata associated with multi-word nouns.

Meaning, using our previous example, there is no way where I can give it "red sea" and it will return noun or any other tag I may enter for it. It will always break red sea into "red" and "sea" and give me the metadata for those individual words.

Also, it seems that what you listed above is similar to out I would get if I were to do:
```
nlp('red sea is a noun.').nouns().out('array');
```

**Comment by spencermountain** [comment]
hey @themaincharacter yeah, you can get all the metadata from the various output methods, which are documented [here](https://beta.observablehq.com/@spencermountain/compromise-output).

if there isn't a good fit for your purposes, you can always do a `.nouns().map(m=> m.metafoobar)` and grab whatever you want
cheers
