### ISSUE TITLE
output of `.nouns` different when the `nlp` call is assigned to a variable

### ISSUE THREAD

**Issue by kwhitaker** [spencermountain/compromise#551]
compromise version: `11.12.3`
node version: `8.11.3`

The following code behaves oddly, or I don't understand the API:

```
const nlp = require("compromise");
const str = "a man and 3 cat";
const doc = nlp(str);
const finalStr = doc.nouns().toPlural().out("normal");
console.log(finalStr); // "man cats"
```

`finalStr` returns `man cats` instead of `a man and 3 cats`.

However, if I just do:

```
console.log(doc.nouns().toPlural().out("normal")) // "a man and 3 cats"
```

It works like I need it to.

Thanks

**Comment by kwhitaker** [comment]
To be clear, I'm looking for a way to accomplish the "a man and 3 cats" output, so if there's a different thing I should be doing, I'm happy to do so :)

**Comment by spencermountain** [comment]
yeah, i think this is behaving as expected, apologies if it's unclear.

`.nouns()` grabs a specifc section of the document, in this case `['man', 'cats']`
using `.out('normal')` concatenates both results into a string, which is awkward in this case.

am working on a new version of this output api, any recommendations welcome.
