### ISSUE TITLE
fn is not a function

### ISSUE THREAD

**Issue by Blitz3r123** [spencermountain/compromise#552]
When trying to implement the following code:
```
       var doc = nlp(data);
	var nouns = doc.nouns().normalize().toLowerCase();
	var verbs = doc.verbs().normalize().toLowerCase();
	var nounA = [];
	nounA = nouns.map();
```
I get the following error:

```
node_modules\compromise\builds\compromise.js:12775
      return fn(text, i);
                ^

TypeError: fn is not a function
```

I am using version 11.12.4.

**Comment by spencermountain** [comment]
hey @Blitz3r123 yeah, you need to pass a function into map.
I guess we could guard against it, but it is a required param
cheers

**Comment by Blitz3r123** [comment]
Hey @spencermountain, what kind of function do I have to pass? With what parameters? Where can I find the documentation for this function if possible please?
Thanks

**Comment by spencermountain** [comment]
it's the same as the javascript [Array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map). it looks through each result, and returns the value.

**Comment by Blitz3r123** [comment]
Makes sense. Thanks a lot for the help!
