### ISSUE TITLE
Tokenization  - does not show punctuation as separate token

### ISSUE THREAD

**Issue by giorgio79** [spencermountain/compromise#553]
Noticed that Compromise does not add punctuation to tokens after tokenization. Example at https://runkit.com/giorgio79/5c0fb8f56120e10016f0c2aa
Most tokenizers show them as separate tokens.

![image](https://user-images.githubusercontent.com/283347/49803668-c179dc00-fd50-11e8-9d8d-db4d7329bdcd.png)

**Comment by spencermountain** [comment]
yeah, that was a design decision. 
Upcoming versions have a different understanding of whitespace/punctuation, but for now you can call `.whitespace()` on any result to get the punctuation, etc.

I like that example because `10 : 00 a.m.?` should be merged together into maybe one token.
cheers

**Comment by spencermountain** [comment]
hey, it's pretty weird, but this is how i'd parse-out all whitespace/punctuation in compromise right now.
```js
let doc = nlp(`we released, "Square Up".`);

let arr = doc.terms().map((t) => {
  let term = t.list[0].terms[0];
  return [term.whitespace.before, term._text, term.whitespace.after];
});
console.log(arr);
/* 
[ [ '', 'we', '' ],
  [ ' ', 'released,', '' ],
  [ ' "', 'Square', '' ],
  [ ' ', 'Up', '".' ]
 ]
*/
```
I know that's not ideal. You can do any kind of ad-hoc work on the information like that.

i'm tempted to improve this, but it's getting a big overhaul [in the next major](https://github.com/spencermountain/compromise/tree/linked-list).

thanks

**Comment by lauralampariello** [comment]
Hi everyone, I would like to know if there is a tokenization function in this library. 
Thanks in advance.

**Comment by spencermountain** [comment]
hey @lauralampariello i think this should help you 
https://runkit.com/spencermountain/5d80e3953b6228001a95d2ab
