### ISSUE TITLE
client-side debug() error

### ISSUE THREAD

**Issue by spencermountain** [spencermountain/compromise#554]
from slack:

Hi, I notice that whenever I use the debug function like `doc.debug();` I get an undefined error. I download the uncompressed library (working from the web) and it said `TypeError: tagset is undefined`

I tried it with both using my plugin and without.

**Comment by SankarshanDudhate** [comment]
I have the same problem... Can you please look into it?

**Comment by spencermountain** [comment]
yeah, for the time-being, you can run `console.log(doc.out('tags'))` for similar functionality.
may not get a compromise release out before christmas.

**Comment by spencermountain** [comment]
fixed in 11.12.6, cheers
