### ISSUE TITLE
String part of speech error

### ISSUE THREAD

**Issue by zzj0402** [spencermountain/compromise#555]
I am a deep learning specialist developing a chrome extension with PoS tagging. The string "string" is mistakenly categorized as verb. I would love to contribute on it if it just an neural network error. 
![image](https://user-images.githubusercontent.com/15345547/50432114-9a073f80-090a-11e9-9f5a-45ace83b9e4f.png)

**Comment by spencermountain** [comment]
hey 张梓径, fixed this in `11.12.5`
cheers

**Comment by zzj0402** [comment]
Now it returns:
```js
['<det> This</det>', '<undefined> is</undefined>', '<det> a</det>', '<noun> test</noun>', '<noun> string!</noun>']
```

**Comment by spencermountain** [comment]
hey @zzj0402 i'm not sure what that output is,
this looks good to me https://runkit.com/spencermountain/5c9251c1e7e3bc0014a2881d
