### ISSUE TITLE
tag cheered/guarded

### ISSUE THREAD

**Issue by chengxianga2008** [spencermountain/compromise#556]
Jack talked for his achievement
"talked" detect as verb
Jack cheered for his achievement
"cheered" detect as person name
Jack guarded for his achievement
"guarded" detect as adjective

Why this happen
How should I fix that?
In desperate need your help.
Thx

**Comment by spencermountain** [comment]
hey Jack, 'talked' is supposed to be a verb in that sentence, in my opinion.

cheered and guarded have both been mis-tagged, you can [add a custom lexicon](https://github.com/spencermountain/compromise/wiki/Lexicon) to fix it.

cheers

**Comment by chengxianga2008** [comment]
thx for the reply, i have added custom verb

**Comment by spencermountain** [comment]
fixed in `11.12.5`
cheers
