### ISSUE TITLE
Capturing plural and singular words

### ISSUE THREAD

**Issue by Berkmann18** [spencermountain/compromise#560]
# What I'm a trying to do?
Parsing comments like `@AllContributorsBot please add Berkmann18 for docs, tests and code` and getting something like this:
```js
{
  action: 'add',
  who: 'Berkmann18',
  contributions: ['docs', 'tests', 'code']
}
```

Here's the code for the for the comment parser which uses `compromise`:
```js
const nlp = require('compromise')

const validContributionTypes = [
    'blog',
    'bug',
    'code',
    'design',
    'doc',
    'eventOrganizing',
    'example',
    'financial',
    'fundingFinding',
    'ideas',
    'infra',
    'platform',
    'plugin',
    'question',
    'review',
    'security',
    'talk',
    'test',
    'tool',
    'translation',
    'tutorial',
    'userTesting',
    'video'
]

const contributionTypeMappings = {
    'event organizing': 'eventOrganizing',
    'funding finding': 'fundingFinding',
    'user testing': 'userTesting',
    documentation: 'doc',
    infrastructure: 'infra',
}

const Contributions = {}

validContributionTypes.forEach(type => {
    Contributions[type] = 'Contribution'
})

Object.keys(contributionTypeMappings).forEach(type => {
    Contributions[`${type}`] = 'Contribution'
})

const plugin = {
    words: {
        ...Contributions,
        add: 'Action',
    },
    patterns: {
        // 'add #person for #Contribution': 'AddContributor',
        // "i can't (log|sign|get) in to my? #Software": 'LoginIssue'
    },
}
nlp.plugin(plugin)

function parseAddComment(doc, action) {
    const who = doc
        .match(`${action} [.]`)
        .normalize({
            whitespace: true, // remove hyphens, newlines, and force one space between words
            case: false, // keep only first-word, and 'entity' titlecasing
            numbers: false, // turn 'seven' to '7'
            punctuation: true, // remove commas, semicolons - but keep sentence-ending punctuation
            unicode: false, // visually romanize/anglicize 'Björk' into 'Bjork'.
            contractions: false, // turn "isn't" to "is not"
            acronyms: false, //remove periods from acronyms, like 'F.B.I.'
            parentheses: false, //remove words inside brackets (like these)
            possessives: false, // turn "Google's tax return" to "Google tax return"
            plurals: false, // turn "batmobiles" into "batmobile"
            verbs: false, // turn all verbs into Infinitive form - "I walked" → "I walk"
            honorifics: false, //turn 'Vice Admiral John Smith' to 'John Smith'
        })
        .data()[0].text

    let contributions = doc
        .match('#Contribution')
        .data()
        .map(data => {
            // This removes whitespace, commas etc
            return data.normal
        })

    contributions = contributions.map(type => {
        if (contributionTypeMappings[type])
            return contributionTypeMappings[type]
        return type
    })

    return {
        action: 'add',
        who,
        contributions,
    }
}

function parseComment(message) {
    const doc = nlp(message)

    const action = doc
        .match('#Action')
        .normalize()
        .out('string')

    if (action === 'add') {
        return parseAddComment(doc, action)
    }

    return {
        action: false,
    }
}

module.exports = parseComment
```

# What is the issue?
Sometimes people might write a `#Contribution` in plural form (e.g: `docs`, `usersTesting`, `tests`) and so far none of the approaches I took involving `toPlural()` and such seems to work (and words like `test` aren't nouns so I can't really use `nouns()`).
So I was wondering if there were an efficient and maintenaible way to do this without having to use regex or add the plural forms to the `validContributionTypes`?

Help would be much appreciated.

**Comment by Berkmann18** [comment]
Also, words like `tests` aren't changed when normalised to singular (possibly because it's only considered as a verb when it's also a noun).

**Comment by spencermountain** [comment]
hey @Berkmann18 yeah, i would just add the plural forms to the contribution types. You figure it's faster to inflect each of those once, than to inflect every noun in your document.

if tests, etc doesn't inflect, it's probably because it's being tagged as a verb. you can co-erce each term by doing `nlp(word).tag('Singular').nouns().toPlural()`
cheers

**Comment by Berkmann18** [comment]
Hey @spencermountain, thank you for your reply, so there's *no way* to do this using `compromise` without manually using a RegExp `match` & `replace` or an `Array.map` based approach like I mentioned [here](https://github.com/all-contributors/all-contributors-bot/issues/15#issuecomment-453505986)?

**Comment by spencermountain** [comment]
in earlier versions we inflected and conjugated all the words to heavily-normalized forms, (like contribution -> contribute) but it was too slow (understandably). 

it's much easier to decide what you're looking for first, then find it. I'd blast-out all forms of contribute that you want, then do a .match()

no regex should be needed!

**Comment by Berkmann18** [comment]
Okay, because the projects I'm working might need to handle a flexible way in which someone would associate a person with a set of contribution types (some who may write it entirely or partially, in plural or in singular).
