### ISSUE TITLE
fix lump() docs 

### ISSUE THREAD

**Issue by h3rald** [spencermountain/compromise#570]
I tried to use the lump method to group together terms with the same tag, but I can't get it to work.

I even tried to run just the example in the wiki and on the site, and they don't seem to do anything. What am I missing?

**Comment by spencermountain** [comment]
hi @h3rald i'm not sure i understand, can you provide an example?
Lump is really just meant to combine two neighbouring words into one. If you want a string with all nouns or something, I suggest doing `doc.match('#Noun').out('array').join(' ')`

**Comment by h3rald** [comment]
I tried running something similar to the example you have on compromise.cool:

```
nlp('Keanu Reeves said whoa').match('#Person').lump().all().out('terms')
//['Keanu Reeves', 'said', 'whoa']
```

And it just didn't work as expected... didn't do anything in fact.

**Comment by spencermountain** [comment]
good point, that looks like a bug.
thanks

**Comment by h3rald** [comment]
Actually it looks like a documentation issue: I had a look at the tests and the method works perfectly, then I noticed that you need to specify a + (match one or more #Person)... so the example should actually be this:

```js
nlp('Keanu Reeves said whoa').match('#Person+').lump().all().out('terms')
//['Keanu Reeves', 'said', 'whoa']
```

**Comment by spencermountain** [comment]
ah, thank you!
will leave this open so I fix the docs.
cheers

**Comment by spencermountain** [comment]
fixed in docs on dev
thanks
