### ISSUE TITLE
replace() function doesn't replace specified text

### ISSUE THREAD

**Issue by moberemk** [spencermountain/compromise#571]
As a continuation of the project I referenced in #568 I've been trying to improve handling for certain input types. For the current case, I'm trying to convert nouns that can also be verbs into past tense verbs, but the replace() function doesn't seem to work in this case when I would expect it to.

```typescript
const nlp = require('compromise'); // tslint:disable-line

const examples = [
  ['eat a cookie', 'Have you eaten a cookie today?'],
  ['take a shower', 'Have you taken a shower today?'],
  ['watch the movie', 'Have you watched a movie today?'],
  ['smell a flower', 'Have you smelled a flower today?'],
  ['beat an egg', 'Have you beaten an egg today?'], //participle working
  ['shower', 'Have you showered today?'],
];

function toParticiple(action: string): string {
  const doc = nlp(action);
  let verb = doc.verbs(0);

  if (verb.length === 0) {
    // If there's only a noun, convert it to a verb gerund form
    doc.nouns(0).tag('Verb');
    verb = doc.verbs(0);
  }

  // If there's a verb, conjugate it
  const conjugations = verb.conjugate()[0]; //use the Participle, or the PastTense
  if (conjugations) {
    const form = conjugations.Participle || conjugations.PastTense;
    doc.match(verb).replace(form);
  }

  const parsed = doc
    .sentences()
    .prepend('Have you')
    .append('today')
    .toQuestion()
    .normalize();

  const outText: string = parsed.out();
  return outText.charAt(0).toUpperCase() + outText.slice(1);
}

function runParticipleTest(input: string, expectation: string): void {
  console.log('Test case');
  console.log(`\tE: ${expectation}`);
  console.log(`\tO: ${toParticiple(input)}`);
}

examples.map(([input, expectation]) => runParticipleTest(input, expectation));
```

The current code that I've been using to test looks like this; not all examples are working 100% perfectly yet, but generally replacement does work except in the last case where the input is exclusively "shower". Not sure what's happening here, exactly, but it's possible that I'm misusing the API--some clarification would be great if possible.

**Comment by spencermountain** [comment]
hey Mark, sorry, I've got a cold this week, and haven't had a chance to look through this issue.

if I understand, the only problem is `shower -> showered`?

can you simplify the issue for me?

`.replace()` is pretty buggy. That's part of the reason i've started a large v12 re-write.
sometimes I have better luck using `.replaceWith(match, string)`, or using the returned value.
cheers

**Comment by moberemk** [comment]
No worries about the delay man, I always appreciate your answers--no rush.

The core issue I'm running in to is that shower doesn't get replaced with "showered" in the text. You can run this script to test it; shower is the only case where it breaks, which is why I was focusing on it.

I'll give it a try with `replaceWith` after I get back from lunch, see if that makes a difference!

**Comment by moberemk** [comment]
So I made the following edits to the code:

```ts
if (conjugations) {
    const form = conjugations.Participle || conjugations.PastTense;
    doc
      .match(verb)
      .replaceWith(form, true)
      .debug();
  }

  const parsed = doc
    .debug()
    .sentences()
    .prepend('Have you')
    .append('today')
    .toQuestion()
    .normalize();
```

and those debug calls, strangely, return the following:

```
====
   --
   'showered'                 - PastTense, Verb, VerbPhrase
====
   --
   'shower'                   - Verb, VerbPhrase
```

am I using the `replaceWith` function wrong here?

**Comment by spencermountain** [comment]
oh hey, it's much simpler than i had suggested - 'shower' is being tagged as a noun, in the last example, that's why it isn't being replaced.

You can add it as a lexicon like this `nlp(action, {shower:'Infinitive'})`
and that will get the example working - but mistag the 'take a shower' example.

this is a gross solution, that I can't believe I just wrote:
```js
const nlp = require("./src");
const examples = [
  ["eat a cookie", "Have you eaten a cookie today?"],
  ["take a shower", "Have you taken a shower today?"],
  ["watch the movie", "Have you watched a movie today?"],
  ["smell a flower", "Have you smelled a flower today?"],
  ["beat an egg", "Have you beaten an egg today?"], //participle working
  ["shower", "Have you showered today?"]
];

//fix-up any ad-hoc tagging issues
const postTag = function(doc) {
  doc
    .if("shower")
    .ifNo("#Determiner shower")
    .match("shower")
    .tag("Infinitive");
  return doc;
};

function toParticiple(action) {
  let doc = nlp(action);
  doc = postTag(doc);
  let verb = doc.verbs(0);

  if (verb.length === 0) {
    // If there's only a noun, convert it to a verb gerund form
    doc.nouns(0).tag("Verb");
    verb = doc.verbs(0);
  }

  // If there's a verb, conjugate it
  const conjugations = verb.conjugate()[0]; //use the Participle, or the PastTense
  if (conjugations) {
    const form = conjugations.Participle || conjugations.PastTense;
    doc.match(verb).replace(form);
  }

  const parsed = doc
    .sentences()
    .prepend("Have you")
    .append("today")
    .toQuestion()
    .normalize();

  const outText = parsed.out();
  return outText.charAt(0).toUpperCase() + outText.slice(1);
}

function runParticipleTest(input, expectation) {
  console.log("Test case");
  console.log(`\tE: ${expectation}`);
  console.log(`\tO: ${toParticiple(input)}`);
}

examples.map(([input, expectation]) => runParticipleTest(input, expectation));
```
cheers

**Comment by moberemk** [comment]
Oh, interesting; that does raise two questions for me though.

1. I'm still not clear on why it changes between `debug()` calls, since it seems to modify the the word but then suddenly it changes in the next call. Does the `replaceWith` call not mutate the original object?
2. Instead of writing that `posttag` function, couldn't I change the bit where it tags the first noun of the sentence as a verb to tag it as an infinitive?

**Comment by spencermountain** [comment]
yeah, there's a serious issue with mutability, that effects `.replace`. I wouldn't be surprised if you've run into it. 

2) yeah, of course you can tag things however you'd like!

gonna close this for now, am working on this replace issue for v12, but it's a while out, still
thanks

**Comment by moberemk** [comment]
Sounds good; if there's any way I could help improve the `replace()` function to speed along that release (maybe written up in an issue somewhere?) I'd be happy to take a look!
