### ISSUE TITLE
3 Tagging issues for .topics()

### ISSUE THREAD

**Issue by lawrencenull** [spencermountain/compromise#572]
I discovered this library Friday and have been playing with it over the weekend. It is a fantastic piece of programming, I have been trying it using Wikipedia snippets for entity parsing and noticed something.

_Example 1_
Elizabeth Woolridge Grant (born June 21, 1985), known professionally as Lana Del Rey, is an American singer, songwriter, record producer, poet, model, and ...

Lana Del Rey - Wikipedia

matched entities: ELIZABETH WOOLRIDGE GRANT, LANA

Example 2
YouTube is an American video-sharing website headquartered in San Bruno, California. Three former PayPal employees—Chad Hurley, Steve Chen, and ...

YouTube - Wikipedia

matched entities:YOUTUBE, BRUN, CALIFORNIA, CHAD HURLEY, STEVE CHEN

If entity matching took into account capitalization and assumed any word grouping that was all capitalized or a word is capitalized, excluding sentence first words it would probably greatly increase accuracy.

**Comment by spencermountain** [comment]
whoa, yeah, good examples. we should definitely catch those issues:

1) `san bruno, california` - 'bruno' catches MaleName
2) missed `PayPal` as Organization
3) `Lana Del Ray` - should be #first, #last #last.

if you're playing around, and want to change the results, you can also add something like this:
```js
let doc=nlp(str)
let topics=doc.topics()
let capitals=doc.clauses().match('#TitleCase+')
topics=topics.concat(capitals).unique().sort('chron')
topics.debug()
// [ 'elizabeth woolridge grant', 'june',  'lana del rey',  'american' ]
```
