### ISSUE TITLE
Root output does not work

### ISSUE THREAD

**Issue by baraklevy20** [spencermountain/compromise#576]
It seems like root output isn't working.
`nlp('He ate the eggs.').out('root')` prints `he ate the eggs`.

**Comment by spencermountain** [comment]
hi @baraklevy20, what were you expecting?
thanks

**Comment by georgelemental** [comment]
I'm having this problem as well. Verbs are not being changed to infinitive, and nouns are not being made singular. According to [the docs](https://observablehq.com/@spencermountain/compromise-output), @baraklevy20's example should output `he eat the egg` (`ate` to infinitive, `eggs` to singular), but this does not happen.

**Comment by spencermountain** [comment]
thanks @georgelemental 
i suggest using `nlp('he ate the eggs.').normalize().out('root')`.
i should probably update those docs. I think i've flipped and flopped a few times about what `.out('root')` should do.
cheers

**Comment by spencermountain** [comment]
thanks @georgelemental looks like normalize isn't working as expected.
this should work, as you intended.

https://runkit.com/spencermountain/5ced4227a6784e001a835794
a fix for this should land in v12.
thanks

**Comment by spencermountain** [comment]
hey, this works now in v12:
```js
console.log(nlp('He ate the eggs.').text('root'))
```
(note the change to [.text()](https://observablehq.com/@spencermountain/compromise-text) )
thanks.
