### ISSUE TITLE
How to get tense of a sentence 

### ISSUE THREAD

**Issue by ismailismail** [spencermountain/compromise#577]
How can I get tense of given sentence? is it possible?

Examples:
I work in a bank
I don't work in a bank
["present","simple"]

Examples:
She's cooking
She's not cooking
Is she working
["present","progressive"] 

Examples:
I cooked
I didn't cook
What did you cook?
["past","simple"]

**Comment by spencermountain** [comment]
hey @ismailismail yeah you should be able to do this with a bit of work and some patience.
It's not a buiilt-in feature of compromise, but we can identify the tense of verbs, and you could figure-out the 'main verb' of a sentence, without too much trouble.
this should get you started:
https://runkit.com/spencermountain/5c9b83a5fed9150012f510b4
cheers
