### ISSUE TITLE
Regex replace part of a match

### ISSUE THREAD

**Issue by raibosome** [spencermountain/compromise#580]
Hi, I'd like to remove part of a regex match. For the sentence `I am happy`, I hope to be able to do

```javascript
doc.replace("#Copula #Adjective", "#Adjective");
```

keeping the adjective and removing the 'is' to get `I happy`. Is this possible, or is there a workaround? 

For reference:

```python
I       Pronoun,Noun,Singular
am      Copula,Verb,VerbPhrase
happy   Comparable,Adjective
```

**Comment by spencermountain** [comment]
hey remy, yes this is possible
https://runkit.com/spencermountain/5c9e5e04b47db80012544ad7

please read the documentation!
