### ISSUE TITLE
Appending words to questions

### ISSUE THREAD

**Issue by remykarem** [spencermountain/compromise#582]
I am trying to do append words using `.append()` to sentences which are questions but I couldn't find anywhere in the docs or API that can do this.

Using `.insertAt()` works, but this does not move the question mark correctly.

**Comment by spencermountain** [comment]
hi Remy, yes you're right - the `Sentence` class overwrites the `.append()/insert` methods with some extra love. I don't remember how well it does though.

```
let doc = nlp('can i append a word?')
  .sentences(0)
  .append('to a sentence')
console.log(doc.text())
```

**Comment by raibosome** [comment]
Hey @spencermountain I figured a workaround for this.

```javascript
doc = nlp("Hey there. Can I append a word?")
doc.sentences(1).getPunctuation()[0] === "?"
for (var i = 0; i < doc.sentences().length; i++) {
    if (doc.sentences(i).getPunctuation()[0] === "?") {
        doc.sentences(i).append("to a question")
    }
}
doc.out()

// Hey there. Can I append a word to a question?
```

Not so elegant but works for me for now.

**Comment by scagood** [comment]
I'd guess that this works:
```js
nlp('Hey there. Can I append a word?')
  .sentences()
  .isQuestion()
  .append('to a question')
  .out()
```

From https://observablehq.com/@spencermountain/compromise-api
(I'll note I have not tried this 👀)

**Comment by raibosome** [comment]
Hi @scagood. This throws an error:

```
nlp(...).sentences(...).isQuestion(...).append is not a function
    at <anonymous>:4:4
```

**Comment by scagood** [comment]
[Somethings have been commented](https://github.com/spencermountain/compromise/commit/14d3bba2cf336cc678bb93b841745b390b07f069) out, I'll need to do some more investigation to work this out 🤔

**Comment by spencermountain** [comment]
yeah, sorry. `isQuestion` returns a generic object, and not a Sentence object.
I think you'll have to call `sentences()` again afterwards (not a big deal) 

`doc.sentences().isQuestion().sentences().append()`.

**Comment by scagood** [comment]
@spencermountain that returns `Hey there to a question. Can I append a word to a question?`

I just did some testing and found this to work 🤔 but it's not to elegant
```js
const doc = nlp('Hey there. Can I append a word?');
doc.sentences().isQuestion()
    .list.forEach(term => term.append('to a question'))

console.log(doc.out())
```

**Comment by spencermountain** [comment]
hey, this seems to work now, in `v12.2.0`. You'll have to import the [compromise-sentences](https://observablehq.com/@spencermountain/compromise-sentences) lib, to do it properly.

Here's a demo
https://runkit.com/spencermountain/5de82834937ebe00199b35ab
cheers
