### ISSUE TITLE
Support for slashed verbs

### ISSUE THREAD

**Issue by elliot-nelson** [spencermountain/compromise#583]
I've noticed that something funny happens with slashed (choice) verbs like "approve/deny" or "open/close".

For example: `nlp("The manager will approve/deny your request").debug()` returns the verbs I'd expect, but following up with `.verbs().toPresentTense().all().out()` returns the truncated string `The manager denies your request.`.  What I would hope to get back is `The manager approves/denies your request.`.

In contrast, `nlp("The manager will approve or deny your request").verbs().toPresentTense().all().out()` returns `The manager approves or denies your request.`, which is what I expect.

Perhaps a slashed verb could be treated as a (Verb SpecialConjunction Verb) phrase?

**Comment by spencermountain** [comment]
hey Elliot, this is a great point. Thank you.

Yeah, the issue is in the verb-phrase grouping. Phrases like `would not walk` are grouped together as one verb, when they're conjugated and things. 
When there is a slash, they shouldn't be grouped together.
```js
nlp('approve/deny').verbs().length()
// 1
```
This should make the conjugation work properly, when fixed.

the verb-grouping stuff is [here](https://github.com/spencermountain/compromise/blob/master/src/subset/verbs/index.js#L101) if anyone wants to go for this.

**Comment by charlesLoder** [comment]
I just discovered compromise and love the idea! I haven't contributed to open-source before so it may take me a bit, but I would to grab this if anyone isn't working on it.

**Comment by spencermountain** [comment]
welcome @charlesLoder ! go for it!

yeah, this can be solved by adding some kind of check for a slash in that `find` method there.
Calling `.split()` in the right place there should do the trick just fine.

We don't have a clean way to search the whitespace-characters right now (i don't think!) - so I'd do something like this:
```js
let doc = nlp('approve/deny')

//each match
doc.list.forEach(ts => {
  //each term
  ts.terms.forEach(t => {
    //does it have a slash in the whitespace?
    if (t.whitespace.before.match('/')) {
      //pull it apart.
      doc = doc.splitOn(t.normal)
    }
  })
})
doc.debug()
```

¯\_(ツ)_/¯

I've written a first-pr thing [here](https://github.com/spencermountain/compromise/wiki/Contributing), if it's helpful.
cheers

**Comment by charlesLoder** [comment]
awesome. I'll get to it

**Comment by charlesLoder** [comment]
I added your suggested code:

```javascript
// src/subset/verbs/index.js

const find = function(r, n) {
  r = r.match('(#Adverb|#Auxiliary|#Verb|#Negative|#Particle)+');
  r = r.splitAfter('#Comma');
  r.list.forEach(ts => {
    ts.terms.forEach( t => {
      if(t.whitespace.before.match('/')){
        r.splitOn(t.normal)
      }
    })
  })
...
```

But if I ran:

```javascript
let x = `she sells/gets sea shells`;

console.log(nlp(x).verbs().data());
```

I got this error:

```
/Users/Admin/Documents/coding/Projs/compromise/src/subset/verbs/methods/toInfinitive/index.js:7
const irregulars = world.cache.toInfinitive || {}; //verb_mapping(world.conjugations); //TODO: do this at world cache
                                 ^

TypeError: Cannot read property 'toInfinitive' of undefined
    at toInfinitive (/Users/Admin/Documents/coding/Projs/compromise/src/subset/verbs/methods/toInfinitive/index.js:7:34)
    at conjugate (/Users/Admin/Documents/coding/Projs/compromise/src/subset/verbs/methods/conjugate/conjugate.js:34:25)
    at multiWordConjugate (/Users/Admin/Documents/coding/Projs/compromise/src/subset/verbs/methods/conjugate/index.js:34:13)
    at Verb.conjugate (/Users/Admin/Documents/coding/Projs/compromise/src/subset/verbs/verb.js:64:12)
    at Verb.data (/Users/Admin/Documents/coding/Projs/compromise/src/subset/verbs/verb.js:48:26)
    at list.map.ts (/Users/Admin/Documents/coding/Projs/compromise/src/text/methods/misc.js:16:37)
    at Array.map (<anonymous>)
    at Subset.data (/Users/Admin/Documents/coding/Projs/compromise/src/text/methods/misc.js:16:24)
    at Object.<anonymous> (/Users/Admin/Documents/coding/Projs/compromise/scratch.js:6:36)
    at Module._compile (module.js:635:30)
```

The problem seemed to be occurring at

```javascript
// src/terms/methods/split.js`

splitOn: function(reg, verbose) {
...
    all = all.map(ts => new Terms(ts, ts.world, ts.refText, this.refTerms));
    return all;
}
```

When passing in `ts.world` the resulting `all[0].world` became `{reBuild: func(), w: World}` instead of just `{World}`. Passing in `this.world` instead of `ts.world` like `splitAfter()` remedies the issue, but I'm not sure if it may create more issues. The tests still pass, but they did without changing to `this.world` too.
