### ISSUE TITLE
Do you have an example usage of downward?

### ISSUE THREAD

**Issue by playground** [spencermountain/compromise#587]
```
Tags: {
  Food: {
    isA: "Information",
    notA: [ ],
   downward: [ ],
 },
}
```

**Comment by spencermountain** [comment]
downward is a collection of all `isA` values. its just an array of strings.

you can see it collects all nested relations from [here](https://github.com/spencermountain/compromise/blob/master/src/tags/tags/nouns.js) 
i'm not sure it's meant to be used externally.  You should just specify `isA` if you are creating a plugin
cheers

**Comment by playground** [comment]
Thanks.
