### ISSUE TITLE
Create custom entities / intent and extract it

### ISSUE THREAD

**Issue by jechazelle** [spencermountain/compromise#591]
I discovered this library and read the doc : awesome ! 👍 

I would like to know if it's possible to create a custom intent and custom entities, to extract it from the text please ?

For example, I would like to create a custom intent and custom entity : 
> "I read the %BOOK% today", "Read %BOOK%" => custom intent "read_book"
> "BOOK" => custom entity

After I create different value attach on the custom entity (BOOK) : 
> "Book name 1", "Book name 2", etc...

With the synonyms to each value : 
>"Book name 1", ["Book name1", "Bookname1", "BokNam1"]
>"Book name 2", ["Book name2", "Bookname2", "BokNam2"]

Finaly, I search this entities on the text : 
> "I read the Bookname1 today !" :

I would like to have a result close enough to that (extract custom intent and entity)
`result = {intent: "read_book", entities: [{name:"BOOK", value:"Book name 1", text:"Bookname1"}}]`

Thank you for your help !

**Comment by scagood** [comment]
You could try using a plugin:
https://observablehq.com/@spencermountain/compromise-plugins

Then create custom tags for each of the expected 'intent strings' and Books.

If you're looking for something along the lines of machine learning:
You may want to consider looking into `Multi-Label Classifiers` for identifying the intent
And then implementing a `fuzzy search` style algorithm into the classified string if have a complete list of books to search for.
