### ISSUE TITLE
Out('array') should output original text

### ISSUE THREAD

**Issue by track0x1** [spencermountain/compromise#606]
I am calling `out('array')` but the text is being stripped of important characters.

Should we update:
https://github.com/spencermountain/compromise/blob/3c0e8ee697cc25d26685b698bd90d84b39d6d1f1/src/text/methods/out/index.js#L64
To be `ts.out('text')` instead of `ts.out('normal')`?

For example:
```js
nlp('hello (secret) world').out('array')
// returns: ['hello secret world']
// notice stripped parentheses

nlp('hello (secret) world').out('text')
// returns: 'hello (secret) world'
```

**Comment by spencermountain** [comment]
hey tom, yeah, `.out('array')` is weird, and the .out() methods are all being improved in v12.
for now, you can use `.data()` or any of the other [out methods](https://observablehq.com/@spencermountain/compromise-output?collection=@spencermountain/nlp-compromise)
cheers
