### ISSUE TITLE
NumberRange has extra whitespace

### ISSUE THREAD

**Issue by track0x1** [spencermountain/compromise#607]
```
nlp('4-5 shoes').debug()
```

is splitting out into

```
   '4-5'      [4]             - Value, NumberRange, Contraction, NumericValue, Cardinal
   '-'        [to]            - Contraction, NumberRange, Preposition
   '-'        [5]             - Contraction, NumberRange, NumericValue, Value
   'shoes'                  - Noun, Plural, Unit
```

Where you see the output is showing `4-5` as one unit, followed by two hyphen characters, where the last should be showing `5`.

**Comment by spencermountain** [comment]
hey Tom, thanks. I think this is just a confusion with the output of `.debug()`. The '-' just means no-text, and the expected behaviour of numberRanges is that they produce terms with implicit text, like contractions do.
I think it should still work as expected, with `.out('text')` and so-forth.
If I'm wrong, feel free to re-open this.
cheers

**Comment by track0x1** [comment]
hi @spencermountain 
yes, when outputting a value like that it ends up distorting the format.

for example:
```

**Comment by spencermountain** [comment]
thanks

**Comment by seinwave** [comment]
Hey @track0x1 —

I had trouble reproducing this bug on my machine. 

My output with `.debug()`:

```
   |   '[4]'      - Number, Cardinal, NumberRange, Contraction
  ｜ '[to]'     - Conjunction, NumberRange, Contraction
  ｜ '[5]'      - Number, Cardinal, NumberRange, Contraction
  ｜ 'shoes'    - Plural, Noun
```
And with `.out('text')`:

```
> nlp('4-5 shoes').out('text')
'4-5 shoes'
```
No extra whitespace.

@spencermountain did you fix this?

**Comment by spencermountain** [comment]
yup, this looks fixed to me too. 
Thanks @seinwave I love your bot.

**Comment by seinwave** [comment]
Hey thanks @spencermountain ! I appreciate it! It wouldn't be possible without Compromise!
