### ISSUE TITLE
`nlp(x).nouns().articles()` does not support `.out`

### ISSUE THREAD

**Issue by daedalus28** [spencermountain/compromise#610]
I'm the process of putting together an example of what a functional `compromise-fp` API could look like (followup from #407) here: https://runkit.com/daedalus28/compromise-fp and I've noticed an inconsistency in the API.

All other noun methods seem to support `out`, e.g.

```js
nlp(someString)
  .nouns()
  .toSingular()
  .out()

nlp(someString)
  .nouns()
  .toPlural()
  .out()
```

`articles` behaves differently, so you need to do this:

```js
nlp(someString)
  .nouns()
  .articles()
  .map(x => x.article)
  .join(' ')
```

instead of just:

```js
nlp(someString)
  .nouns()
  .articles()
  .out()
```

**Comment by daedalus28** [comment]
Side note - my hope is that the `nlpTransform` approach in that runkit might be a simple, clean way we could have a compromise-fp set up with a configuration blob similar to how lodash/fp works :smile:

**Comment by spencermountain** [comment]
hey Samuel! This is really neat.
Is this the model, you'd like to see?
```js
nlpTransform(['sentences', 'toPastTense'])
```
i think I understand the proposal more now. 
Is the idea that it avoids all state dangling around, at all times? That sounds pretty clean.
I think the reason I've favoured having a big object being passed-around is that parsing/tokenizing/tagging is so labourious, and I've tried to require doing it only once per input.

oh, and ofcourse - that `.articles()` thing is trash. I am working (hard!) on cleaning this up in [v12](https://github.com/spencermountain/compromise/tree/linked-list).

another thing that may interest you in v12 is that it's getting a generic `.data()` method - not perfect yet, but the goal is that you can easily export/import a compromise object, and throw them around a bit easier. If you're thinking about i/o for each `chainMethod`, and wanted to avoid class-stuff, that could be a way to go.

anyways, i think it's cool, and would love to hear more.
cheers

**Comment by spencermountain** [comment]
oh, if you haven't seen it yet, [api.json](https://github.com/spencermountain/compromise/blob/master/docs/api.json) describes each method, and (should!) tell you whether they return a 'Text' object, or not. That may help.

**Comment by daedalus28** [comment]
That's great - so it sounds like v12 will fix the issue here 👍 

The idea for a functional API would still be actual methods but they can hopefully just be curried versions of `nlpTransform`. I imagine the library itself would look something more like this, modeled after how it's done by [lodash/fp](https://github.com/lodash/lodash/blob/4.17.5-post/fp/_mapping.js):

`compromise-fp/config.js`
This could potentially be driven by that API.json file you linked 🤔 
```js
export default {
  articles: ['nouns', 'articles'],
  pastTense: ['sentences', 'toPastTense'],
  titleCase: ['toTitleCase'],
  singular: ['nouns', 'toSingular'],
  plural: ['nouns', 'toPlural'],
  //... then all the rest of the stuff
}
```

`compromise-fp/index.js`

```js
import config from './config'
import _ from 'lodash/fp'
import nlpTransform from './transform'

export default _.mapValues(nlpTransform, config)
```

`compromise-fp/transform.js`

```js
import nlp from 'compromise'

let chainMethods = (methods, x) =>
  methods.reduce((result, method) => result[method](), x)
let nlpTransform = methods => (x, y) => chainMethods(methods, nlp(x)).out(y)

export default nlpTransform
```

**Comment by spencermountain** [comment]
hey Samuel, `.articles()` has been removed from v12, as you're right they were odd.
article information can now be found in `.nouns().json()`, which seems like a better place.
cheers
