### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by zzj0402** [spencermountain/compromise#611]
```typescript
import { nlp } from "compromise";
```
support importing feature.

```
Could not find a declaration file for module 'compromise'. 'c:/Users/xoxo/projects/xoxo/node_modules/compromise/builds/compromise.js' implicitly has an 'any' type.
  Try `npm install @types/compromise` if it exists or add a new declaration (.d.ts) file containing `declare module 'compromise';`ts(7016)
```

**Comment by spencermountain** [comment]
hi 张梓径, this will be available in v12.
it should be a few weeks.
cheers

**Comment by juliandm** [comment]
Yes please!

**Comment by spencermountain** [comment]
hey, this should work now, in `^12.0.0`. I'm not a typescript-pro, but I've got a typefile [here](https://github.com/spencermountain/compromise/blob/master/types/index.d.ts) and it is linked in the package.json. I've tried it out in a cursory way, but I'd love some help, or some confirmation that it works.
Plz lemme know how it goes!
thanks
