### ISSUE TITLE
Custom bundling to reduce size

### ISSUE THREAD

**Issue by tommy-dev** [spencermountain/compromise#612]
Thanks for this library, it is amazing. However, a big blocker to use it is the bundle size. You can see here https://bundlephobia.com/result?p=compromise@11.14.2 it still takes a long time to load on 3G. 

I assume most devs use only a small selection of the features. For example, I just want to use the pluralize and gerund features (e.g. pause -> pausing).

Suggestion is to add a custom bundling ability with es6 modules. A great famous library that does this is math.js, detailed here https://mathjs.org/docs/custom_bundling.html

**Comment by spencermountain** [comment]
hey tommy, i agree! v12 is 30% smaller, and publishes esmodules.
it's about a month away still.

compromise doesn't tree-shake well, because the tagger is the bulk of it, and must run before we can do anything else.
working on it!
will let you know when v12 is released
cheers

**Comment by spencermountain** [comment]
![image](https://user-images.githubusercontent.com/399657/69969746-feebf200-14ea-11ea-9f13-632ae9e6de6e.png)
v12 is also marked as `sideEffects:false`, which as I understand, will help webpack et al rip more parts off of it. 
let me know how it goes
