### ISSUE TITLE
captures adjacent to start/end anchors do not work

### ISSUE THREAD

**Issue by JaredReisinger** [spencermountain/compromise#615]
Just ran across this and wanted to get it documented before I try to track down the source of the problem.  In a nutshell, a capturing match (`[]`) that's adjacent to a start (`^`) or end (`$`) anchor does not seem to work.  Here's a simple test case:

```js
const nlp = require('compromise');
const doc = nlp('one two three');

// non-anchored, expected matching
doc.match('[one] two three').data();    // returns [{ text: 'one', normal: 'one' }]
doc.match('one [two] three').data();    // returns [{ text: ' two', normal: 'two' }]
doc.match('one two [three]').data();    // returns [{ text: ' three', normal: 'three' }]

// anchored, adjacent matching fails
doc.match('^[one] two three$').data();  // returns []
doc.match('^one [two] three$').data();  // returns [{ text: ' two', normal: 'two' }]
doc.match('^one two [three]$').data();  // returns []

// variations
doc.match('[one] two three$').data();   // returns [{ text: 'one', normal: 'one' }]
doc.match('^one two [three]').data();   // returns [{ text: ' three', normal: 'three' }]
```

Given the last two variations, it's pretty clear that it's the adjacency of the anchor to the capture that's causing the problem, not the mere existence of "an" anchor.

I'll see if I can track down where in the code this is happening.

**Comment by JaredReisinger** [comment]
Heh... after digging into https://github.com/spencermountain/compromise/blob/master/src/terms/match/lib/syntax.js, I see what's going on... the capturing syntax (`[]`) is handled _before_ the anchors... so while `^[one]...` doesn't work, `[^one]...` does.  Not quite what I'd expect, but I can make that work.

So, for the record, the corrected (and working) matches are:

```js
doc.match('[^one] two three$').data();  // returns [{ text: 'one', normal: 'one' }]
doc.match('^one two [three$]').data();  // returns [{ text: ' three', normal: 'three' }]
``

**Comment by spencermountain** [comment]
thanks @JaredReisinger yep, this, and a bunch of similar gotchas, are fixed already in [v12](https://github.com/spencermountain/compromise/tree/linked-list).

thanks for taking the time to dig into this. It should be documented in more detail somewhere.
I was thinking of breaking it, to make things more regex-aligned, so it would all become more intuitive, then got scared-off by this idea. If you have any ideas or suggestions about improving the syntax, now is an excellent time
cheers!
