### ISSUE TITLE
Is it possible to add sentiment analysis?

### ISSUE THREAD

**Issue by DaiZack** [spencermountain/compromise#620]
Is it possible to add sentiment analysis?

**Comment by spencermountain** [comment]
hi Zack, it would be possible, but is not on [the roadmap](https://medium.com/@spencermountain/compromise-in-2019-e7d0ca703320) for this year.
You could integrate compromise with another tool, with this functionality, in a cool way.
If you figure out a good solution, let me know.
cheers
