### ISSUE TITLE
How to get all tags in compromise + plugin?

### ISSUE THREAD

**Issue by thegoatherder** [spencermountain/compromise#623]
I want to list all tags: #Verb, #Noun, #Preposition, etc etc etc
Plus, all tags introduced by plugin

To get an output like:
```
['Verb','Noun','Preposition','MyCustomTag']
```  
Have searched API but can't find the method or property that outputs this. Any ideas?

**Comment by spencermountain** [comment]
hey Adam, in v12 you can accomplish this like so:
```js
nlp.extend((Doc, world) => {
  world.addTags({ CoolTag: {} })
})

console.log(nlp().world.tags)
```
i've added this to [the docs](https://observablehq.com/@spencermountain/compromise-tags)
cheers
