### ISSUE TITLE
Plugin that doesn't override defaults?

### ISSUE THREAD

**Issue by GuySartorelli** [spencermountain/compromise#626]
Hey,

At the moment if I add an existing word in a plugin, it will always override the default tags. If I want to keep them, I have to go and find out what nlp already tags it as, then add my new tag to that list and THEN add it to the plugin.

Is there a way (maybe a second parameter to `nlp.plugin()` e.g. `nlp.plugin(thePlugin, false)` ) to keep the existing tags whilst adding new tags through a plugin?

**Comment by spencermountain** [comment]
hey @GuySartorelli you're right, there's no way to diff the current words, without doing it manually.
you can get the current words of the lexicon like this:
```js
var words = nlp('').world().words;
console.log(words);
```
cheers
