### ISSUE TITLE
replacements don't keep case information

### ISSUE THREAD

**Issue by kwasimensah** [spencermountain/compromise#628]
compromise("Apple is a very famous company.").match("apple").replaceWith("peach").all().out()

Returns:
"peach is a very famous company."

Ideally it returns:
"Peach is a very famous company."

Compromise version: 11.14.3

**Comment by spencermountain** [comment]
hi kwasimensah, yeah you're right about this. it simply inserts the given text.
it would be cool to transfer case information. Remember that either string could be multiple-terms, and titlecase means different things at different times.

will have to think about this some more.
cheers

**Comment by spencermountain** [comment]
hey @kwasimensah , this is the default behaviour now in `12.1.0`:
```js
let doc = nlp('Apple is a very famous company.')
doc.match('apple').replaceWith('peach')
console.log(doc.text())
// 'Peach is a very famous company.'
```

you can configure this as an options param, as detailed [here](https://observablehq.com/@spencermountain/compromise-insert)

thanks for your patience, cheers
