### ISSUE TITLE
All elements returned by splitOn return true from found

### ISSUE THREAD

**Issue by kwasimensah** [spencermountain/compromise#629]
var compromise = require("compromise")

var apples_match = compromise("Apples are the best apples you can eat with apples.").splitOn("apples")

for(var i = 0; i < apples_match.length; ++i){
console.log(apples_match.get(i).found)
}

What Happens:
All elements return true.

Ideally:
Parts that don't have "apples" return false

Version: 11.14.3

I'm up for taking a stab at these bugs if they're not running into fundamental issues

**Comment by spencermountain** [comment]
ya, you can do this:
```js
.splitOn('apples').not(''apples)
```
cheers
