### ISSUE TITLE
Not es5 compatible since 11.14.0

### ISSUE THREAD

**Issue by SammyJoeOsborne** [spencermountain/compromise#631]
With 11.14.0 through 11.14.3, dist/compromise.js and dist/compromise.min.js contain the use of const and the fat arrow syntax which is not compatible with es5.

For those needing a working copy, it appears the last es5 compatible build was 11.13.2

**Comment by spencermountain** [comment]
ah, thanks @SammyJoeOsborne .  Sorry about that. 

[Version 12](https://github.com/spencermountain/compromise/tree/linked-list) is getting released in a few days, and has a proper babel-rollup workflow. That should be the quickest solution.

**Comment by spencermountain** [comment]
i can hotfix before sunday, if anyone needs it.

**Comment by spencermountain** [comment]
fixed in v12, thanks for your patience.
