### ISSUE TITLE
Give percent = NAN and count as string on the constructor word in the file.

### ISSUE THREAD

**Issue by Komal1101** [spencermountain/compromise#633]
Run the code 
var compromise = require("compromise");
                let doc = compromise(`if  constructor !  null 
      {
        ViewBase currentObject    ViewBase  constructor.Invoke new object 2 `).nouns().out('topk');
                console.log(doc);

**Comment by spencermountain** [comment]
hey Komal, I'll admit, i'm very confused by this issue. Are you trying to parse the code as a string?
are you trying to change the compromise constructor?
Your example doesn't seem to be syntactically valid. I'm pretty lost
cheers
