### ISSUE TITLE
Where is compromise-entities?

### ISSUE THREAD

**Issue by fmacpro** [spencermountain/compromise#635]
Hey,

first off just wanted to say wow what a release. Impressed with the amount of work thats gone into this. Maybe i'm jumping the gun a bit here but I thought I'd give the new version a try and it seems compromise-entities plugin hasn't been published yet?

**Comment by spencermountain** [comment]
thanks Frank! Yeah, it's a relief to merge that branch in.
compromise-entities was combined into the main lib last-minute. You can run people, organizations, places and topics from the main import.
i've updated the readme on dev, will release later today.
cheers
