### ISSUE TITLE
Normalize Numbers not turning seven to 7

### ISSUE THREAD

**Issue by Jun711** [spencermountain/compromise#636]
I noticed that normalize function doesn't turn `seven` to `7` on [demo page](https://observablehq.com/@spencermountain/compromise-normalization) 

<img width="1007" alt="Screen Shot 2019-11-28 at 12 27 46 PM" src="https://user-images.githubusercontent.com/6880939/69830621-8af3d600-11da-11ea-9479-487c11e01807.png">
<img width="1009" alt="Screen Shot 2019-11-28 at 12 27 13 PM" src="https://user-images.githubusercontent.com/6880939/69830622-8af3d600-11da-11ea-9d09-9ea05e120728.png">

**Comment by spencermountain** [comment]
thanks @Jun711 you're right. 
I'll update the doc, and the changelog. 
Number-parsing has been moved into it's own [separate plugin](https://observablehq.com/@spencermountain/compromise-numbers) to save some filesize.

after installing, you can get the same effect with a `.numbers().toNumber()` command.
cheers
