### ISSUE TITLE
[Bug] Compromise library hangs indefinitely when initialized on this particular text below

### ISSUE THREAD

**Issue by Coord** [spencermountain/compromise#640]
The below text seems to hit a particular edge case in the library. It hangs indefinitely, and eventually cause the Node process to seg fault with bus error: 10.

Here is the repro:

const nlp = require('compromise');
nlp("Tasoulas, Evangelos; Hammer, Hugo Lewi; Haugerud, Hårek; Yazidi, Anis; Bratterud, Alfred; Feng, Boning\n\n(2017).                  The Concept of Workload Delay as a Quality-of-Service Metric for Consolidated Cloud Environments with Deadline Requirements.                                               Gkoulalas-Divanis, Aris (Ed.).                          2017 IEEE 16th International Symposium on Network Computing and Applications (NCA).         1.         p. 1-5.                      IEEE conference proceedings.\n\nHammer, Hugo Lewi; Yazidi, Anis; Bratterud, Alfred; Haugerud, Hårek; Feng, Boning\n\n(2017).                  A Queue Model for Reliable Forecasting of Future CPU Consumption.\n\nJournal on spesial topics in mobile networks and applications\n\nHammer, Hugo Lewi; Yazidi, Anis; Bratterud, Alfred; Haugerud, Hårek; Feng, Boning\n\n(2017).                  Recovering Request Patterns to a CPU Processor from Observed CPU Consumption Data.                                               Maglaras, Leandros (Ed.).                          Industrial Networks and Intelligent Systems.         2.         p. 14-28.                      Springer.\n\nBratterud, Alfred; Walla, Alf-André; Haugerud, Hårek; Engelstad, Paal E.; Begnum, Kyrre\n\n(2015).                  IncludeOS: A minimal, resource efficient unikernel for cloud services.\n\nIEEE International Conference on Cloud Computing Technology and Science\n\nhttp://2015.cloudcom.org/\n\nKvadsheim, Reidar; Haugerud, Hårek; Hammer, Hugo Lewi; Bratterud, Alfred; Habib, Laurence\n\n(2015).                  Does Clicker Use Improve Exam Scores? A Controlled Randomized Experiment in a Bachelor-Level Course in Software Engineering.\n\nInternational Journal of Engineering Education\n\n.                                                    Vol. 31.\n\nhttp://www.ijee.ie/latestissues/Vol31-2/08_ijee299...\n\nBratterud, Alfred; Haugeru)d, Hårek\n\n(2013).                  Maximizing hypervisor scalability using minimal virtual machines.                                               Society, IEEE (Ed.).                          2013 IEEE International Conference on Cloud Computing Technology and Science.         Artikkel.         p. 218-223.                      IEEE.\n\nhttp://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arn...\n\nHammer, Hugo Lewi; Bratterud, Alfred; Fagernes, Siri\n\n(2013).                  Crawling JavaScript websites using WebKit - with application to analysis of hate speech in online discussions.\n\nNIK: Norsk Informatikkonferanse\n\nhttp://www.nik.no/2013/1-3-HammerBratterudFagernes..."

**Comment by spencermountain** [comment]
hi Andy, thanks for this issue. 
I haven't been able to reproduce the time-out, you can see it running here:
https://runkit.com/spencermountain/5de51aacb0402b001a4635ff
can you help me isolate it?
thanks

**Comment by Coord** [comment]
Thanks for the fast response. Something in the text seems to get lost when the text is pasted on Github or Runkit, and it ends up working. Here is the raw text to try: https://pastebin.com/sR3JXnmZ

**Comment by spencermountain** [comment]
hey @Coord i just tried that text, and still no timeout.
Can you try to isolate it?
thanks

**Comment by spencermountain** [comment]
let me know if you can find it, thanks.
