### ISSUE TITLE
Mismatch between v12 release notes and source code. (compromise-entities)

### ISSUE THREAD

**Issue by RexChiu** [spencermountain/compromise#641]
The v12 release notes states that there is a breaking change of `.people()` and `.places()` being moved out to their own plugin `compromise-entities`.

However I see a commit that reverts that change in v12: https://github.com/spencermountain/compromise/commit/4b6af0d708d23af087314b867ba029a71575da1f

Which one is correct?

**Comment by spencermountain** [comment]
ah, thanks @RexChiu - the wiki is wrong.
fixed it!
cheers
