### ISSUE TITLE
doc.json() is not a function

### ISSUE THREAD

**Issue by DimaMayd** [spencermountain/compromise#653]
Can't figure out how to save or output the file via this function. Seems like the problem of compatibility, though I am so sleepy that I do not know what to do.

`nlp(`Wayne's World, party-time, excellent!! 🎸`).json({offset:true})[0]`
This line, just like in documentation, won't work.

Help!

**Comment by spencermountain** [comment]
hey @DimaMayd are you running v12? This changed a couple weeks ago, and the documentation has been updated

here's an example of it working, cheers
https://runkit.com/spencermountain/5dfa5f4475cce3001921e650

**Comment by DimaMayd** [comment]
> hey @DimaMayd are you running v12? This changed a couple weeks ago, and the documentation has been updated
> 
> here's an example of it working, cheers
> https://runkit.com/spencermountain/5dfa5f4475cce3001921e650

The problem is I get the following error:
`nlp(...).json is not a function. `

I use browserify to run the program, though the error happens even when I create local server and run my code on it.

bundle.js essentially is the code from my main file, converted via the browserify extension to support nodejs in the browser:
**main.js:**
```
var nlp = require('compromise');	
let data = nlp("Waynes World, party-time, excellent!!").json({offset:true})[0];
console.log(data);
```

![image](https://user-images.githubusercontent.com/36950530/71139753-c13fd680-2217-11ea-8495-175e9a3c56c3.png)

I just can't think of anything that solves my problem.
