### ISSUE TITLE
Not every dot is a period for a sentence.

### ISSUE THREAD

**Issue by issuefiler** [spencermountain/compromise#657]
https://github.com/spencermountain/compromise/blob/5163649736d4ef1657a1e198b4c776457a851892/src/01-tokenizer/index.js#L45

https://github.com/spencermountain/compromise/blob/5163649736d4ef1657a1e198b4c776457a851892/builds/compromise.mjs#L3103

-----

```javascript
require("compromise")(".")
```

throws a `TypeError: Cannot read property 'id' of undefined`.

**Comment by spencermountain** [comment]
i'm glad you found this. I have it fixed on dev, and I was surprised nobody else saw it.
I just didn't wanna release it over the holidays.
Will try and release `12.3` in the next few days.
cheers

**Comment by Drache93** [comment]
Just a note on this one, setting the travis build to include current LTS node actually results in this error being thrown during build:

https://travis-ci.org/spencermountain/compromise/jobs/633820174?utm_medium=notification&utm_source=github_status

**Comment by spencermountain** [comment]
got this fixed in `12.3.0`, thanks for your patience!
