### ISSUE TITLE
out('tags') outputs numerical value's tags first

### ISSUE THREAD

**Issue by SankarshanDudhate** [spencermountain/compromise#658]
`var s = nlp('comes 19 after 18');
for( key in s.out('tags')[0] )  console.log( s.out('tags')[0][key] );`

This outputs 
`[ 'Cardinal', 'Value', 'NumericValue' ]                                                                                 
[ 'Cardinal', 'Value', 'NumericValue' ]                                                                                 
[ 'PresentTense', 'Verb' ]                                                                                              
[ 'Preposition' ]`

Clearly the order is different. Why so?

P.S. I have also noticed that out('tags') works differently now. In my old code, I used to use out('tags')[i] to get i'th word's tags but now it's a bit different as you can see above. It's not a big deal but I wonder why this changed.

**Comment by spencermountain** [comment]
hey @SankarshanDudhate yes, the order in a javascript object is not to be relied on, and there is no meaning to the order in `.out('tags')`.

You may want to [check out](https://observablehq.com/@spencermountain/compromise-json) `.json({bestTag:true})`
cheers!
