### ISSUE TITLE
Failure to parse .* with optional word

### ISSUE THREAD

**Issue by kelvinhammond** [spencermountain/compromise#675]
The following fails to parse correctly.
```javascript
nlp("remind me to wash clothes tomorrow").match("remind me to .* at? #Date+").debug()
```

**Comment by spencermountain** [comment]
hey, sorry about that @kelvinhammond we must have moved date tagging too aggresively over to the date plugin.

this should fix it:
```js
nlp.extend(require('compromise-dates'))

nlp('remind me to wash clothes tomorrow')
  .match('remind me to .* #Date+')
  .debug()
```
will add these words back to the default lex for 12.3
cheers

**Comment by kelvinhammond** [comment]
Thanks for the quick fix.

**Comment by kelvinhammond** [comment]
OK so I got this working,

I can just let the `at` say within the `#Date+` query as its matched as part of the `Date` which is good. I missed that.

So I don't think there are any issues.

I believe the changes in https://github.com/spencermountain/compromise/commit/d67eb0d85f1ac562cecc4602d86231ad409b442c should probably be rolled back.
