### ISSUE TITLE
Add support for HTML

### ISSUE THREAD

**Issue by ershov** [spencermountain/compromise#691]
Hi,
It would be useful to be able to use it on HTML pages.
The simplest solution would be to teach parser to recognize and skip HTML tags.
A more sophisticated solution would be able to recognize block/inline tags and add sentence splits or ignore the tag. This might fail dramatically depending on CSS though.

**Comment by thegoatherder** [comment]
@ershov you can use other node packages to extract the text from HTML easily and then pipe this into compromise. Similarly you could do this with PDF or any file type.

**Comment by ershov** [comment]
One of benefits of compromise if that it tags the words with offsets so that the content can be easily edited in-place.
For sure I can preprocess the source and feed it to compromise but it's a one way street.
If compromise could tag html directly, it would open a whole range of new possible applications.

**Comment by spencermountain** [comment]
hi Yury, yeah I agree this would be cool. I'm not actually sure how to do it.

If you're looking for a rich-text experience, you may want to check out [compromise-hightlight](https://spencermounta.in/compromise-highlight/) which uses codemirror for this txt-html mapping.

what's your application?
I think *often* about [this video](https://www.youtube.com/watch?v=UK42Hont3to)

**Comment by ershov** [comment]
Hi Spencer,
I have a pretty clean and neat idea how to do that but it's quite long to describe here. I wrote it in an email to you, please check it :)

That video is quite impressive.
I don't have an application yet but my idea is to make a browser extension to modify the web page words in a funny way.
In order to make it funny, the modifications must be meaningful, that's why the extension needs to "understand" the words at least to some extent.
So I need to

1. Understand the text
2. Identify the words to alter and the ways to do that
3. Locate the words in the original source and modify them

As you can see, that clearly needs to be a two-way interaction: not just feeding the text to a text processor but also being able to trace the words back to the source.

Compromise is really unique here, no other library can do it.

- Out-of-the-box, it can run on both server and client (and I am more interested in a standalone client).
- It is capable of referring the words back to the source.
- It's extremely lightweight and fast, zero external dependencies.

So I actually have no choice what to use :)

**Comment by ershov** [comment]
By the way, I have figured out the way to do that without any modifications to the library.

What I can do is - pre-process HTML and replace the tags by spaces so that the source text length does not change.
But then I would also need to replace html entities which would break it anyway.

Also, because Compromise does some text normalization before parsing it, the offsets sometimes can be inaccurate.

**Comment by spencermountain** [comment]
hey Yury, sounds like a really neat project, and a tricky problem.
Thank you for your email, let me respond here.

I've wanted to do this for a long time too - it's such a wicked problem, and a serious issue with the web right now.

There have been a number of browser extensions written using compromise to edit a page's text, but from what I've seen, all manage to either A) trip-up on a  random `<b>` tag, or B) implement some kind of offset-based stitcher, like you have.

I'd like to know more about the offset problems you've seen - it shouldn't normalize anything unless you ask it to!

I understand your idea about getting compromise to ingest an AST, or some more granular tokens.
It's been proposed before, and I've often considered it. The current tokenization-level has been chosen carefully, and the word-vs-space-vs-punctuation decisions are made to simplify both internal use (looping through recursive graph is hard!) and the external API.

It may be sensible to offer this sort of thing as a wrapper, or a plugin, to map offsets for people - either parsing html in some way, or allowing a custom tokenization layer. if you can think of a way to do it, i'd love to work with you on this.

I'd like to keep compromise a 'text-in' tool right now, but man, would I love a better way to change text on a webpage. It's a problem burning to be solved.
cheers

**Comment by thegoatherder** [comment]
Would it make sense to use a tool like [jsdom](https://www.npmjs.com/package/jsdom) to parse the HTML and then recursing through its data structure to perform the match and replace?

**Comment by spencermountain** [comment]
hey - yeah. the issue is that inter-sentence (or inter-word!) tags would need to be mapped backwards in an sure-to-be-awkward way:
```
let html = `i am the very model of a <b>modern</b> major general`
let txt = jsdom.parse(html)
let doc = nlp(txt)
doc.replace('a modern major', 'justOneWord')
```
even if you had some really granular offset information, retaining some notion of the initial tagging or formatting would be really hard.

**Comment by ershov** [comment]
Hey guys,

I guess, my solution is not as universal as I thought at this stage.
Apparently it's not covering `replace()` case. A more quirky example would be trying to replace the same text in a html like `"model of a <b>modern major general</b>"`.
What it does cover is mapping of words back into positions in the source text.
While replacement of the word sequences would not work, replacement of single words should be fine. I understand that it might be just one corner case which is useful to myself.

Regarding jsdom, yes, it looks like a good replacement of browser's tools (and I don't need it when running in browser).
But correct usage of it is not straightforward.

Just scanning through the text nodes is not good enough because it can break the sentences and words relationship.
In order to convert HTML to plain text, the library needs to understand what effect each tag has on the text around it.
For example, `<b>` typically has zero width and should be processed as if there is nothing in place of it. `"m<b>a</b>jor"` would be converted to "major" rather then three sentences "m", "a", "jor".
`<div>` on the other hand would split the sentences regardless the whitespace around it.

Of course, the styles can change the behavior, that's another level of complexity which I am not considering now.

Also, you obviously need to handle correctly (ignore?) `<style>` and `<script>` elements and replace HTML entities with unicode characters. You wouldn't want to be interpreting the stylesheet as a human language or something like `&nbsp;` to be interpreted as a word and a semicolon after it.

So yes, while it's not a complete solution for handling HTML, there are definitely some common things that everyone who attempts to process HTML would need to do.

Right now I have two approaches in mind.

(1)
Preprocess the text before feeding it into Compromise in a way that would retain the positions of meaningful words while having it in a format that Compromise expects the text to go in. It will allow to correctly map the offsets.
For example, `"<div>one one one</div><div>little <b>dog</b> run</div>"` would be transformed into `"\none one one    __  \n    __  \nlittle    __dog __   run __    \n"`.
Things like `"m<b>a</b>jor"` would still need to mess with internal word representation: the length would need to be increased to fit the tags but the word itself would need to be stored as "major".
This solution looks cheaper at first but because it still needs to change a lot of internal data and there are currently no distinct layers for that, the code may end up pretty messy and hard to read and write.

(2)
Refactor the parsing and introduce more individual layers. They would be a lot more easier to interact with via plugins.
The source input lexer would generate a sequence of tokens with all attributes attached.
The stream of tokens could then be processed: some tokens might be glued together, some might split the sentence, some might be thrown away.
Eventually it will end up in the same structure as it is now: a list of sentences of list of words.
This approach involves more initial refactoring but eventually it will end up in a cleaner code and more powerful library.

While at first I was tempted to use the first approach, now I lean towards the second one.
And it's more fun and more joy seeing the result.

I'm going to prepare a prototype and see where it could go.

**Comment by spencermountain** [comment]
hey @ershov that sounds great.
if you choose to do #2, i could add support for this sort of thing in compromise:
```js
let str='a modern major general. vegetable and mineral.'
// whatever custom tokens you'd like
let myTokens = str.split(/\. /g).map(str=>str.split(/ /g))
//[["a", "modern", "major", "general"], ["vegetable", "and", "mineral."]]
nlp(myTokens).json()

```
something like that?
ideally, if it kept some kind of format, it could pass-through metadata like original offset, or whatever.
would something like that be helpful?

**Comment by spencermountain** [comment]
um, also just thought of this, which could aid in # 2 -  [.fromJson()](https://observablehq.com/@spencermountain/compromise-constructor-methods)
```js
  let doc = nlp('a modern major general. vegetable and mineral.')
  let data = doc.json()
  
  //... ok, load this data as a new doc object
  let doc2 = nlp.fromJSON(data)
```
i guess you could set custom tokens, using that json format, and pop it into a compromise object that way?!
bit of a funny path, but that may work!

**Comment by spencermountain** [comment]
keep in mind, if you stray too-far from the default tokenization, things can be mis-tagged internally - if you do `['paris', '<div>', 'hilton' ]` it may not get tagged as a `Person` anymore, etc.

let me know if I can help further.

**Comment by Drache93** [comment]
> keep in mind, if you stray too-far from the default tokenization, things can be mis-tagged internally - if you do `['paris', '<div>', 'hilton' ]` it may not get tagged as a `Person` anymore, etc.
> 
> let me know if I can help further.

Maybe solved with a way to overload what goes in to pre/post?
Callback during the tokenisation or match to throw certain things into pre/post?

**Comment by Drache93** [comment]
@spencermountain @ershov 
Had a play with pushing html tags into pre/post:

```ts
import nlp from '.'

const doc = nlp('<div>one one one</div><div>little <b>dog</b> run</div>')

const startHtmlTag = /<\w+>/
const endHtmlTag = /<\/\w+>/

// Remove html tags from term and push them into pre/post
// @todo Add a while loop?
const updateTerm = (t: nlp.Term) => {
  const start = startHtmlTag.exec(t.text)
  const end = endHtmlTag.exec(t.text)

  console.log(start, end)

  if (start) {
    t.pre += start[0]
    t.set(t.text.substring(start[0].length, t.text.length))
  }

  if (end) {
    t.post += end[0]
    t.set(t.text.substring(0, t.text.length - end[0].length))
  }
}

doc.uncache() // allow us to play with pool safely

// Go through all terms and fix them
doc.list.forEach(p => {
  p.terms().forEach(t => {
    if (t.text.includes('><')) {
      const split = t.text.split('><')

      const left = t.clone().set(split[0] + '>')
      left.reduced = left.clean
      updateTerm(left)

      const right = t.clone().set('<' + split[1])
      right.reduced = right.clean
      updateTerm(right)

      // HELPER NEEDED IN COMPROMISE - split a term in 2
      // @ts-ignore
      const pool = doc.pool()

      const tPrev = pool.get(t.prev)
      const tNext = pool.get(t.next)

      left.prev = t.prev
      left.next = right.id
      right.prev = left.id
      right.next = t.next

      tPrev.next = left.id
      tNext.prev = right.id

      pool.remove(t.id)

      pool.add(left)
      pool.add(right)

      // @ts-ignore
      p.length += 1

      return
    }

    updateTerm(t)
  })
})

doc.cache()

doc.debug()
console.log(doc.text()) // same as input
```

**Comment by spencermountain** [comment]
hey this is clever!
so in my understanding, this is @ershov (1) concept.

could it handle spaces in html tags? like `hello<div class="asdf sdf">world</ div> ` that?

**Comment by Drache93** [comment]
Probably somewhere between 1 and 2.
I put the HTML and looked at what was mis understood and can be done with current version.

Upgrading the regex used would cover HTML tags better (so classes etc, nothing yet). Spaces will probably result in more terms, so likely need a pre processer like #1 to avoid that...
Nice thing about pre/post is it keeps everything compromisey and just hides what we don't care about.

**Comment by Drache93** [comment]
More play, turns out using encode/decode uri is a nice way to protect the html.
I encoded it, did my manual splitting, then decoded it before doing nlp stuff.

```ts
import nlp from '.'

const cleanPlugin: nlp.Plugin<
  {
    splitTerms(this: nlp.Document, target: string): nlp.Document
  },
  {}
> = (Doc, world, _, Phrase) => {
  Phrase.prototype.splitTerms = function(this: nlp.Phrase, target: string, doc: nlp.Document) {
    doc.uncache() // allow us to play with pool safely

    const terms = this.terms()

    for (let i = 0; i < terms.length; i++) {
      const t = terms[i]

      const index = t.text.indexOf(target)

      if (index >= 0) {
        const targetEnd = index + target.length
        const left = t.clone().set(t.text.substring(0, targetEnd))
        left.reduced = left.clean

        const right = t.clone().set(t.text.substring(targetEnd, t.text.length))
        right.reduced = right.clean

        // HELPER NEEDED IN COMPROMISE - split a term in 2

        const tPrev = this.pool.get(t.prev)
        const tNext = this.pool.get(t.next)

        left.prev = t.prev
        left.next = right.id
        right.prev = left.id
        right.next = t.next

        if (tPrev) {
          tPrev.next = left.id
        }
        if (tNext) {
          tNext.prev = right.id
        }

        if (t.id === this.start) {
          this.start = left.id
        }

        this.pool.remove(t.id)

        this.pool.add(left)
        this.pool.add(right)

        this.length += 1
      }
    }

    doc.cache()
  }

  Phrase.prototype.updatePrePost = function(reg: RegExp) {
    // Remove html tags from term and push them into pre/post
    // @todo Add a while loop?

    this.terms().forEach(t => {
      let m = reg.exec(t.text)

      if (!m) {
        return
      }

      if (m.index === 0) {
        t.pre += m[0]
        t.set(t.text.substring(m.index))
      } else {
        t.post += m[0]
        t.set(t.text.substring(0, t.text.length - m[0].length))
      }
    })
  }

  Doc.prototype.splitTerms = function(target: string) {
    this.list.forEach(p =>
      //@ts-ignore
      p.splitTerms(target, this)
    )

    return this
  }
}

const _nlp = nlp.extend(cleanPlugin)
const reg = /<\/?[\W\w\=\"]+>/

//const doc = nlp('<div>one one one</div><div>little <b>dog</b> run</div>')
const input = encodeURI('hello<div class="asdf sdf">world</ div>')
const doc = _nlp(input).splitTerms(encodeURI('>'))

doc.list.forEach(p => {
  p.terms().forEach(t => {
    t.text = decodeURI(t.text)
  })

  // @ts-ignore
  p.updatePrePost(reg)
})

doc.debug()
console.log(doc.text()) // same as input

```

```
=====
  -----
  ｜ 'hello'    - Noun, Singular
  ｜ 'world'    - Noun, Singular

```

**Comment by spencermountain** [comment]
just cleaning up issues - help welcomed on this going forward
