### ISSUE TITLE
Plugin tag's collision

### ISSUE THREAD

**Issue by amprodes** [spencermountain/compromise#694]
Hi, I am having this error in my plugins;

node_modules/compromise/builds/compromise.js:935
    return str.charAt(0).toUpperCase() + str.substr(1);
               ^
TypeError: str.charAt is not a function

I think there is a collision with existing tags, because it crash also with the word "dime" in english is "tell me" but also is a currency, if I do this "dime" : ['bla',bla2'] bum same error but if i do this "dime" : "whatever" it works and print ['currency','whatever'], anyway code to reproduce the issue; 

`
var nlp = require('compromise')

nlp.extend((Doc, world) => {

world.addWords({
    "mi" : ['Possessive', 'FirstPerson', 'Singular', 'Poss1stPerson'],
  //"mi" : 'Possessive',
    "mis" : ['Possessive', 'FirstPerson', 'Plural', 'Poss1stPerson'],
  //"mis" : 'Possessive',
    "dime" :  ['Verb', 'FirstPerson','Infinitive', 'PresentTense']
   })
})
           let text = 'hola mi nombre es Andree'
          //text2 = "dime la hora"
 
            let doc   = nlp(text), 
                result  = doc.out('tags')
                console.log(result)`

**Comment by amprodes** [comment]
https://runkit.com/amprodes/5e3352d93e97e4001cc959b0

**Comment by spencermountain** [comment]
thanks Andree, fix will be released as part of v13 in the next few days.
cheers

**Comment by amprodes** [comment]
thanks bro! switching to dev branch!
