### ISSUE TITLE
Bug? toNegative() is not a function anymore

### ISSUE THREAD

**Issue by jochemstoel** [spencermountain/compromise#698]
Hi umm,
Did something change in a recent update, am I overlooking something stupid or is this a bug? In the [examples](https://nmotw.in/compromise/) and [documentation](https://nmotw.in/compromise/) on the internet, the method _toNegative_ is used to render a negative sentence but when I literally copy paste the example it throws an error because the method does not seem to exist. 
```bash
npm i compromise
```
```js
const nlp = require('compromise')
var doc = nlp('London is calling')

console.log(
    doc.toNegative() // TypeError: doc.toNegative is not a function
)
// trying sentences() first
console.log(
    doc.sentences().toNegative() // TypeError: doc.sentences(...).toNegative is not a function
)
```

This is weird because I think this used to work.

**Comment by spencermountain** [comment]
hey Jochem, yes as of [v12](https://github.com/spencermountain/compromise/wiki/v12-Release-Notes) sentences has been moved to [a plugin](https://observablehq.com/@spencermountain/compromise-sentences).

you can still call `doc.verbs().toNegative()` without a plugin
cheers
