### ISSUE TITLE
.extend() not working with ES6's import statement

### ISSUE THREAD

**Issue by alexcheninfo** [spencermountain/compromise#699]
Sorry if this has already been asked, but I couldn't find the answer anywhere.

Basically, doing this works:

```
import nlp from 'compromise'
```
This too:

```
const nlp = require('compromise')
nlp.extend(require('compromise-ngrams'))
```

But this:

```
import nlp from 'compromise
nlp.extend(require('compromise-ngrams'))
```
Makes TSLint throw this error:

> Property 'ngrams' does not exist on type 'DefaultDocument'.

What's the proper way of extending Compromise in an ES6 way?

Note: This is my `tsconfig`:

```
"compilerOptions": {
  "module": "commonjs",
  "target": "es6",
  "outDir": "out",
  "sourceMap": true,
  "rootDir": "src",
  "strict": true,
  "esModuleInterop": true // this makes my first example work
},
```

**Comment by Drache93** [comment]
Hi @alexcheninfo!

That currently is the only ES6-ish way to require in a one liner. The fully ES6 method would be:

```js
import nlp from 'compromise'
import ngrams from 'compromise-ngrams'

nlp.extend(ngrams)
```

`"esModuleInterop": true` is default in tsconfig. Is using that causing any issues for you?

**Comment by alexcheninfo** [comment]
Thanks for helping.

As you can see in this screenshot, I copy-pasted your code, but VS Code is still saying that there's a problem:

https://ibb.co/cyw5hyR

My project only has a `tsconfig` and a `tslint`. The tslint is this:

```
{
  "rules": {
    "no-string-throw": true,
    "no-unused-expression": true,
    "no-duplicate-variable": true,
    "curly": true,
    "class-name": true,
    "semicolon": false,
    "triple-equals": true
  },
  "defaultSeverity": "warning"
}
```
The `tsconfig` is the one above. (`esModuleInterop: true` makes `import nlp from 'compromise'` work.)

**Comment by Drache93** [comment]
Ah right my bad, yeh the typings don't get updated on the original file. So full usage is:

```js
import nlp from 'compromise'
import ngrams from 'compromise-ngrams'

const nlpEx  = nlp.extend(ngrams)

nlpEx('test is test').ngrams({ min: 1 })
```

Fyi, you can paste images directly into the github text box when writing a message :).

**Comment by alexcheninfo** [comment]
That did it. Thanks! Your suggestion worked even without the `compromise-numbers` package.

Seems like if you want to use `import`, you have to do const `nlpEx = nlp.extend(extension_name)`.

(And thanks, I didn't know you could drop images here!)

**Comment by Drache93** [comment]
Thanks, for the feedback - will make a PR with updated Readme. So far the readme doesn't include typescript specific stuff.
