### ISSUE TITLE
Unrecognised verbs 

### ISSUE THREAD

**Issue by mariaejejej** [spencermountain/compromise#711]
I found that the verb **retire** and **unpublish** doesn't transform it in its **gerund** form.

**Examples of running**
`nlp('publish unpublish expire duplicate').verbs().toGerund().all().text()`
It returns -> " publishing unpublish expire duplicating"

**Comment by spencermountain** [comment]
will add your fix to the next release, `13.1.1`.
thanks

**Comment by mariaejejej** [comment]
It still doesn't work, it does not recognize 'unpublish' and 'expire' as a verb so it cannot conjugate.

**Comment by mariaejejej** [comment]
verb1 is the output of: **nlp('expire').match('#verb');**
verb2 s the output of: **nlp('duplicate').match('#verb');**
As you can see on Doc list on the verb expire the Array has no elements and on the verb duplicate it has 1 element
`verb2
Doc {list: Array(1), from: Doc, world: World, _cache: {…}, …}
list: Array(1)
0: Phrase {start: "duplicate-roKQhAV", length: 1, isA: "Phrase", pool: Pool, cache: {…}, …}
@each: (...)
[]: (...)
firstObject: (...)
hasArrayObservers: (...)
lastObject: (...)
length: 1
__proto__: Array(0)
found: (...)
from: Doc
list: Array(1)
0: Phrase {start: "duplicate-roKQhAV", length: 1, isA: "Phrase", pool: Pool, cache: {…}, …}
@each: (...)
[]: (...)
firstObject: (...)
hasArrayObservers: (...)
lastObject: (...)
length: 1
`

`verb1
Doc {list: Array(0), from: Doc, world: World, _cache: {…}, …}
list: Array(0)
@each: (...)
[]: Array(0)
firstObject: (...)
hasArrayObservers: (...)
lastObject: (...)
length: 0
__proto__: Array(0)
found: (...)
from: Doc
list: Array(1)
0: Phrase {start: "expire-KcJZjke", length: 1, isA: "Phrase", pool: Pool, cache: {…}, …}
@each: (...)
[]: Array(1)
firstObject: (...)
hasArrayObservers: (...)
lastObject: (...)
length: 1
`

**Comment by spencermountain** [comment]
hey @mariaejejej it is not released yet.
I'll leave this open until it is.
If you want to run it locally, you'll need to run `npm run pack` after changing the word-lists in `./data`
cheers

**Comment by spencermountain** [comment]
should be in now
cheers
