### ISSUE TITLE
Allow tagColor specification

### ISSUE THREAD

**Issue by AurielleP** [spencermountain/compromise#718]
When using the debug feature after running a large set of tag insertions and matching, its really difficult to see the tags i'm looking for - Is there a way to respect a color definition on a tag?

e.g.: 
```
tags: {
    SomeTagName: {
        isA: ['CustomTag'],
        notA: ['Noun'],
        color: 'yellow',
    }
}
```

**Comment by spencermountain** [comment]
i like that!
happy to add this.

**Comment by spencermountain** [comment]
if anyone wants to take a crack at this, it should be pretty straightforward to add [over here](https://github.com/spencermountain/compromise/blob/master/src/World/tags/inference/index.js)

**Comment by spencermountain** [comment]
hey, this works now in `13.1.1`
available colors are `green|red|blue|magenta|cyan|yellow|black`
nice idea.
cheers
