### ISSUE TITLE
How does .match() differ from simple .replace(); How to use match option list with phrases

### ISSUE THREAD

**Issue by islalobo** [spencermountain/compromise#723]
Trying to parse transcription results for instances when the phrase representing the punctuation and replace it with the correct formatting.

I am wondering how `.match()` differs from a simple search and replace

This is an example at an attempt to use match.

```
  javascript
  _punctType(results) {
    switch (results.match('[<punctuation>(period|comma|exclamation mark|question mark)]', 'punctuation').text()) {
    case 'period':
      return periodRegex;
    case 'comma':
      return commaRegex;
    case 'exclamation mark':
      return exclamationRegex;
    case 'question mark':
      return questionRegex;
    default:
      break;
    }
  }
```

In this example use `.match()` I am not able to get multi-word phrases to be correctly recognized.

**Comment by spencermountain** [comment]
hey Alanna, yeah it doesn't look like compromise will recognize that syntax in the match statement.

You can see the examples of [the match syntax here](https://observablehq.com/@spencermountain/compromise-match-syntax) and examples of .replace() [here](https://observablehq.com/@spencermountain/compromise-insert)

i would write your example more like this:
```js
if(doc.has('@hasComma')){
  return 'comma'
}
if(doc.has('@hasPeriod')){
  return 'period'
}
//etc
```
cheers

**Comment by islalobo** [comment]
Hey @spencermountain 

That won't work because the document doesn't have a comma or period, it has the word 'comma' and the word 'period'

Do you have other suggestions for this unique case?

**Comment by spencermountain** [comment]
ohhh, sorry i misunderstood.
yeah, the multiple-word inside of `( )` is pretty awkward right now.
you may have better luck with `.lookup()`:
```js
let doc=nlp('i used a question mark and nothing else, period.')
doc.lookup(['comma','question mark','period']).out('array')
```
https://runkit.com/spencermountain/5e612505ecbc3d00138ed3ad
cheers

**Comment by islalobo** [comment]
Thanks! How do these methods, .lookup and .match, differ from a simple javascript .replace method?

**Comment by spencermountain** [comment]
no problem.
lookup checks-against the parsed and normalized form of the terms, so it will guard against punctuation, contractions and other shenanigans in the text.
it can also be much faster, when working with large # of lookups or texts.

but yeah, if you write some safe regular expressions, you can use a simple javascript replace too
