### ISSUE TITLE
Doesn't extract 'pm' with dates() - assumes 'am'

### ISSUE THREAD

**Issue by Bwvolleyball** [spencermountain/compromise#724]
The `dates()` plugin doesn't seem to extract `pm` with a timestamp - it seems to always assume 24hr time / `am`.
This library seems super cool, I wish I knew how to use it better - nice work!

Minimal reproduction example:

```typescript
import nlp from 'compromise';
import nlpSentences from 'compromise-sentences';
import nlpDates from 'compromise-dates';
import nlpNumbers from 'compromise-numbers';

// ... //

private parser = nlp.extend(nlpSentences).extend(nlpDates).extend(nlpNumbers)

// ... //

const r = this.parser('Last Updated: 02/28/2020 03:00 pm ').debug().dates().format('{month} {date-ordinal} {year} {time}').debug().out('array');
console.log(r);
```

Outputs:
Debug log #1:
```
"Last Updated: 02/28/2020 03:00 pm "

'Last'    -  Adjective
'Updated'  -  ProperNoun, Noun, Singular
'02/28/2020'  -  Date
'03:00'   -  Time, Date
'pm'      -  Noun, Singular, Time, Date
```
* it recognizes pm as a Date, but then proceeds to drop it when the dates are asked for 🤔 

Debug log #2:
```
"February 28th 2020 3:00am "

'February'  -  Month, Date, Singular, Noun
'28th'    -  Date, Time
'2020'    -  Year, Date, Noun, Singular, Time
'3:00am'  -  Time, Date
```

Final output array:
```
["February 28th 2020 3:00am"]
```

Is there a link / reference to the formatting language I can use with compromise as well?

**Comment by spencermountain** [comment]
thanks Brandon, happy to take a look at this.
The actual time-parsing is being done in [spacetime](https://github.com/spencermountain/spacetime), and should be able to handle that time format, but it looks like the right terms are not being sent-in.

i should say, compromise-dates is pretty early still, and has a lot of weaknesses. Lots to come.
cheers
