### ISSUE TITLE
Missing api.json file

### ISSUE THREAD

**Issue by daedalus28** [spencermountain/compromise#738]
In #610, @spencermountain mentioned that there is an `api.json` file that could be used to generate a functional version of the library. What happened to it?

On a related note, I've basically completed what I think would be a decent starting point for compromise-fp here:
https://runkit.com/daedalus28/compromise-fp

All that needs to be done is filling in the `methods` json blob. That can be done by hand, but if this work was already done, it'd be great to use it as a starting point. Also, would you want this to be a separately published `compromise-fp` lib? Or would you want a PR to this repo? Aside from the giant json blob, the whole thing ends up barely a dozen lines of code 😄

**Comment by spencermountain** [comment]
oh hey! that's neat!
yeah, we lost the api.json file in v12, we now have a [typescript types file](https://github.com/spencermountain/compromise/blob/master/types/index.d.ts) and the readme file.

You could probably just eyeball the 7 files in [./Doc/methods](https://github.com/spencermountain/compromise/tree/master/src/Doc/methods) too, to see em all.

Let me know if I can do anything to help. I can add a link to the project once it's complete, or whatever you prefer.
cheers!
