### ISSUE TITLE
gets stuck when I send the character "t------------------------------------t"

### ISSUE THREAD

**Issue by manjeet13** [spencermountain/compromise#739]
So I have a chat app that uses compromise for resolving entities internally from user messages. During some testing we found that when we send something like "t------------------------------------t", the library never responds. It is getting stuck somewhere.
I think this has more to do with "-" character because you can replace "t" with any other character or string and it still gets stuck.

Any idea what this could be?

**Comment by spencermountain** [comment]
whoa, thank you. This definetly sounds like a regex bug.

**Comment by manjeet13** [comment]
I don't know if this helps but this seems to be happening in the latest versions. For now we have switched to an older version of this lib (11.4.0) and it works fine

**Comment by spencermountain** [comment]
hey @manjeet13 I haven't been able to reproduce this, do you know which specific methods you're calling?
https://runkit.com/spencermountain/5e88997e9f7a3c001aa33f14
I tried a couple different versions
thanks!

**Comment by manjeet13** [comment]
yeah so this is not happening in the latest version, I think it was some intermediate version we were using previously. I'll close the issue, thanks for super quick response and apologies for getting back so late.
