### ISSUE TITLE
Punctuations and match multiple

### ISSUE THREAD

**Issue by NICK7Z** [spencermountain/compromise#742]
Hi Thank you for this wonderful package, but I was trying to delete question marks or all the punctuation in the text, I tried match '?' and '#punctuations', they didn't work, I wonder how I can do that?

Also, what should I do if I want to match and delete multiple stuff in one text?

**Comment by spencermountain** [comment]
hey @NICK7Z sorry for the delay. This is a good question.
right now there's only some [limited ways](https://observablehq.com/@spencermountain/compromise-match-syntax#@methods) to query punctuation from a match statement

in your case, you can use `@hasQuestionMark` and others.
```js
let doc = nlp(`who is on first?`)
doc.match('@hasQuestionMark').post(' ')
doc.trim() //remove any trailing spaces
doc.text()
//"who is on first"
```
https://runkit.com/spencermountain/5e95f96f16db1f0013719f6c

cheers
