### ISSUE TITLE
multiple matches

### ISSUE THREAD

**Issue by NICK7Z** [spencermountain/compromise#746]
Hi what if I want to use .has(), but I have multiple words to put in there? Thanks

**Comment by spencermountain** [comment]
hi @NICK7Z you can use `(optional|voluntarty|volitional)` syntax as described [here](https://observablehq.com/@spencermountain/compromise-match-syntax)

you can also use multiple `has()` statements in an OR.
cheers

**Comment by NICK7Z** [comment]
Hi,

You mean I can do nlp(text).has("word1|word2|word3")? like this? or
nlp(text).has(word1).has(word2).has(word3)?
I'm sorry I am pretty elementary at coding.

thanks

**Comment by spencermountain** [comment]
either could work:
```js
nlp(text).has('(word1|word2|word3)')

//or
let doc = nlp(text)
doc.has('word1') || doc.has('word2') || doc.has('word3')
```

**Comment by NICK7Z** [comment]
Thank you very much!
