### ISSUE TITLE
Current dataset is extremely small

### ISSUE THREAD

**Issue by niftylettuce** [spencermountain/compromise#760]
Hi @spencermountain - excellent work here.

I was curious if you had plans to automate the scraping of Wikimedia's dataset and dictionaries that they provide to the public (per language) as downloadable tarball files?

This would vasty expand the accuracy of this project.

At a brief glance, I noticed a basic name of "Elon" wasn't included in the male name dataset.

**Comment by spencermountain** [comment]
thanks, i'd be happy to increase the coverage of our person names dataset, though the goal of the project is to maintain a small filesize.
I don't know which dataset you're referring to - but I'm happy to discuss this and prs are welcome
