### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by maletor** [spencermountain/compromise#770]
It seems to me that compromise doesn't support fixing simple spelling mistakes? Is there a workaround? Would you suggest feeding the text through a spell checker first?

**Comment by spencermountain** [comment]
hi Ellis, you're correct. Interpreting the text has been hard-enough that adding a 'maybe they meant' layer was just too-tricky.
I've always wanted compromise to be able to handle loose slang and informal input, but ya, the idea has always been that the text is correct.
cheers
