### ISSUE TITLE
offset information for term[0] is clobbered by offset information for the Doc as a whole

### ISSUE THREAD

**Issue by JaredReisinger** [spencermountain/compromise#771]
_(Using v13.3.1)_

```javascript
> nlp('hello world').json({ offset: true })

[{
  text: 'hello world',
  terms: [
    {
      text: 'hello',
      tags: [Array],
      id: 'hello-QHp27op',
      pre: '',
      post: ' ',
      offset: { index: 0, start: 0, length: 11 }  // <====== notice the length, it's the same as the doc's length below
    },
    {
      text: 'world',
      tags: [Array],
      id: 'world-GYTaM1w',
      pre: '',
      post: '',
      offset: { index: 1, start: 6, length: 5 }
    }
  ],
  offset: { index: 0, start: 0, length: 11 }  //<====== same as term[0]!
}]
```

The problem stems from https://github.com/spencermountain/compromise/blob/master/src/Doc/methods/output/_offset.js#L42-L43, where the doc-level offset infomation is "assigned from" term[0].  This isn't a copy of the data, it's the same underlying object.  Thus, when line 43 sets the length for the Doc's offset, it is _also_ setting the length on term[0]!

I have a fix locally that uses `Object.assign()` to create a new Doc-specific offset object.

**Comment by spencermountain** [comment]
whoa! good find!
