### ISSUE TITLE
dates bug on help pages

### ISSUE THREAD

**Issue by thegoatherder** [spencermountain/compromise#782]
[This page](https://observablehq.com/@spencermountain/compromise-dates?collection=@spencermountain/nlp-compromise) is outputting the following error for all examples:

```
ReferenceError: process is not defined
```

![image](https://user-images.githubusercontent.com/389668/94554434-fcb10c00-0251-11eb-865c-326ddacbde27.png)

**Comment by spencermountain** [comment]
yikes, thank you.

**Comment by spencermountain** [comment]
fixed in `1.2.0`. woopwoop
