### ISSUE TITLE
quotations in .topics()

### ISSUE THREAD

**Issue by EranBoudjnah** [spencermountain/compromise#783]
For the following sentence:
"Japan \'Twitter killer\' pleads guilty to murders"

The debug output is:
```
=====
  -----
  ｜ 'Japan'    - ProperNoun, Singular, Noun, Organization
  ｜ 'Twitter'  - Organization, Singular, ProperNoun, Noun, Term
  ｜ 'killer'   - Noun, Singular
  ｜ 'pleads'   - Noun, Plural
  ｜ 'guilty'   - Adjective
  ｜ 'to'       - Conjunction
  ｜ 'murders'  - PresentTense, Verb
```

As a topic, you get `japan twitter`. You don't get Japan on its own. The quotes are ignored. I tried single quotes, double quotes and even a hyphen. No clue helps identify Twitter Killer as a separate expression, and Japan as the country.

**Comment by spencermountain** [comment]
hey Eran, this is a good find. There's a lot going wrong here.
.topics() should definitely recognize quotations and not select phrases that span them.

'topics' is a really tricky thing - i'm not sure what would happen if 'scare quotes' or short "double quotations" would end up in those results. Certainly, knowing Twitter is an organization helps, in this case.

At min, we should get 'japan', and definetly not 'japan twitter' - I can look, but I think it's getting co-erced by things like 'boy scouts of america'.
good bug.

**Comment by spencermountain** [comment]
hey Eran, this is now better in `13.6.0`
.nouns() will split by quotation, so will split Japan Twittter
pleads is now a verb too.
not sure if the results are perfect yet - let me know if you have any suggestions
thanks

**Comment by EranBoudjnah** [comment]
Brilliant! Thank for for maintaining this awesome project 👍
