### ISSUE TITLE
Custom expressions with lower case preposition not detected.

### ISSUE THREAD

**Issue by EranBoudjnah** [spencermountain/compromise#784]
For the sentence:
`What to stream this weekend: Birds of Prey, The Walking Dead: Word Beyond and more highlights`

With the following terms:
```
const knownTerms = [
    "Birds of Prey",
    "The Walking Dead",
    "Word Beyond"
];
```

Calling ` document.lookup(knownTerms);` results in:
```
[ 'The Walking Dead.', 'Word Beyond' ]
```

Note "Birds of Prey" is not caught.

However, if I replace `of` with `Of`, "Birds of Prey" is returned.

**Comment by spencermountain** [comment]
hey @EranBoudjnah this seems to work for me
https://runkit.com/spencermountain/5f788b5bc952bf001acaad75
