### ISSUE TITLE
Change numbers but preserve the whole text

### ISSUE THREAD

**Issue by rafamen8** [spencermountain/compromise#791]
Hi! I have the next problem: I have a sentence like this, for instance:

two hundred and five plus one hundred and twenty two

And I would like to obtain this: 205 plus 122.

But, if I use the numbers().toNumber, it just takes the 205 and 122, deleting the "plus". Is there any way to do this? Thanks in advance!

**Comment by spencermountain** [comment]
hey @rafamen8 yeah, you should be able to convert the numbers in the document, then refer back to the document,
```js
let doc = nlp('two hundred and five plus one hundred and twenty two')
doc.numbers().toNumber()
console.log(doc.text())
```
lemme know if i've misunderstood the question
cheers
