### ISSUE TITLE
Number range tagging

### ISSUE THREAD

**Issue by Jakeii** [spencermountain/compromise#795]
Number ranges seem to be tagged strangely resulting in things this not working:
```js
nlp('1-2').numbers().out('array'); // => []

nlp('1-2').contractions().expand().numbers().out('array') // => []

nlp('1-2').contractions().expand().numbers().out('array') // => []

```

Using the debug i can see that the numbers in a number range aren't tagged with `#Value`, they are tagged with `#Number`, but that is not used on 'single' numbers?

```js

nlp('1').debug()
// '1'       -  Cardinal, Value, NumericValue

nlp('1-2').debug();
/*
"1-2"
compromise.mjs:7687    '[1]'     -  Number, Cardinal, NumberRange, Contraction
compromise.mjs:7687    '[to]'    -  Conjunction, NumberRange, Contraction
compromise.mjs:7687    '[2]'     -  Number, Cardinal, NumberRange, Contraction
*/

**Comment by spencermountain** [comment]
whaaaaaa!
ahh, what a good catch. 
Fixed on dev. WIll release in a few days.
cheers

**Comment by Jakeii** [comment]
sorry @spencermountain, there's still a slight issue with this!

```js
nlp('1-2').terms().out('array') \\ => ["1-2", "", ""]

nlp('1-2').match('#NumberRange').out('array') \\ => ["1-2", "", ""]

nlp('500-600 grams').match('#NumberRange #Unit').out('array') \\ => ["grams"]
```

**Comment by Jakeii** [comment]
Do you have any pointers for me to take a crack at this?

**Comment by spencermountain** [comment]
hey @Jakeii - sorry for the delay.
yeah, this is a tricky one, with how contractions are handled internally, and how sloppy the `.out('array')` output is.


Good news is, I think it's still behaving as expected. You can see a clearer output with `.json()`
```js

let arr = nlp('1-2').terms().json({ reduced: true, terms:false })
console.log(arr)
/*
[
  { text: '1-2', reduced: '1', },
  { text: '', reduced: 'to',  },
  { text: '', reduced: '2', }
]
*/
```
Maybe we should change the defaults for how we output things. I agree it's pretty-awkward right now.

Maybe `.out('array')` should be deprecated, or the empty values should be filtered out- what do you think?
reopening this issue

**Comment by Jakeii** [comment]
Thanks for the insights! But I think the main issue is how it works with matching, these seems unexpected: 
```js
nlp('1-2 gram').match('#NumberRange #Unit').text() \\ " gram"

nlp('1-2 gram').splitAfter('#NumberRange').json({ reduced: true, terms:false })
/*
"[
  {
    "text": "1-2",
    "reduced": "1"
  },
  {
    "text": "",
    "reduced": "to"
  },
  {
    "text": "",
    "reduced": "2"
  },
  {
    "text": "gram",
    "reduced": "gram"
  }
]"
*/
```
Have to do stuff like
```js
nlp('1-2 gram').match('#NumberRange+ #Unit').text() \\ "1-2 gram"
\\ or
nlp('1-2 gram').match('#NumberRange #NumberRange #NumberRange #Unit').text() \\ "1-2 gram"
```
which seems unintuitive

**Comment by spencermountain** [comment]
yeah, that's right. you'll have to use `'#NumberRange+ #Unit'`, as it is a sequence of terms, under-the-hood.

I've removed the empty results from `.out('array')`, and will try adding implicit words to json responses by default, to avoid further confusion
cheers

**Comment by Jakeii** [comment]
cool sounds good! 
One last question, how does it work for other contractions? I only ask because of a situation in a project of mine where capturing a number range with a single tag would be useful.

```
"don't worry"
compromise.mjs:7689    '[do]'    -  Infinitive, PresentTense, Verb, Auxiliary
compromise.mjs:7689    '[not]'   -  Negative
compromise.mjs:7689    'worry'   -  Infinitive, PresentTense, Verb
```

both of these work:
```js
nlp('don\'t worry').match('#Verb #Verb').text()
"don't worry"

nlp('don\'t worry').match('#Verb #Negative #Verb').text()
"don't worry"
```

**Comment by spencermountain** [comment]
the syntax is [@hasContraction](https://observablehq.com/@spencermountain/compromise-match-syntax)

**Comment by Jakeii** [comment]
ok thanks

**Comment by spencermountain** [comment]
empty results are now removed from `.out('array')` in `13.8.0`
If you have any ideas for how this syntax could be improved, let me know. There's some tech-debt in there that shouldn't be exposed in the api like that - thanks for your patience with this. 
cheers
