### ISSUE TITLE
Support (~one~|~two~) in soft-matches

### ISSUE THREAD

**Issue by mohsinather-gnowit** [spencermountain/compromise#797]
Issue 1: Multi softmatches are not working i.e
cacheDocss.match('(~ look ~|~ other ~)') is not working 

Issue 2: If multiple sentences are given for caching it throwing error on push 
ie
let cacheDocss = nlp("I'm seraching for Amanda Huggin. She is amazing . She is strong and most intelligent amongst others. Companies are looking for her to offer job.");
cacheDocss.cache({ root: true })

However, second issue is fixed by adding 
 if(words[t.reduced].length) on line 7113 in compromise,js file. I haven't spent much time on it so i'm not sure is this the best fix or not.

**Comment by spencermountain** [comment]
ah, thank you @mohsinather-gnowit good finds. I'm glad you've taken an interest in the soft-match functionality.
will take a look at fixing these issues this week.
cheers

**Comment by spencermountain** [comment]
hey @mohsinather-gnowit i've fixed the runtime error on dev, and will release it next week.
The `(~one~|~two~)` issue is a little bit more complicated, and for now you may need to split them into multiple match statements.
Will let you know when there's a release.
cheers

**Comment by mohsinather-gnowit** [comment]
Thank you so much and BTW great work. I love this package and it saved my alot of time

**Comment by spencermountain** [comment]
that multi-sentence issue is now fixed on `13.8.0`
thanks for your help.
WIll keep this open for `(~foo~|bar))`
cheers
