### ISSUE TITLE
inject correct past tense for verbs

### ISSUE THREAD

**Issue by panKt** [spencermountain/compromise#800]
Hi, I have set of verbs that compromise don't have correct **PastTense** conjugations, how can I still inject correct ones to be used?
For example verbs like: 
```
allow      PastTense: 'allew'
patrol     PastTense: 'patroled'
guide      PastTense: 'guode'
```
etc...

```javascript
  const doc = nlp('allow')
  doc.tag('verb')
  doc.verbs().conjugate()          // PastTense: 'allew'
  doc.verbs().toPastTense().text() // allew
```

So having correct corresponding PastTense version for those words, how can I use it in lexicon or something to make it use corrected PastTense?
Thanks :)

**Comment by spencermountain** [comment]
Hey @panKt thanks for the great examples, I'm happy to fix them in the next release- ideally before the new year. Cheers

**Comment by panKt** [comment]
@spencermountain those examples are just few of them. Thing is I'm working with large text and have to do various modifications that also include converting to past tense. As I'm progressing more through the text I find more and more of such examples. Once I'm done with it all I'll provide a list of my findings with incorrect & corrected past tense per word, plural/single modifications, etc...

But for now I need a way to be able to make **compromise** use corrected versions of PastTense from my list that I already have. I tried replacing it in lexicon with no luck, I tried the `nlp.plugin` approach - but it does not work in `compromise v13`, etc...
Could you please give an example how can I make compromise use my own conjugations for those words I found that have incorrect PastTense?

**Comment by spencermountain** [comment]
amazing!
That would be very, very useful.
There is a secret undocumented way to set custom conjugations - let me pull it up:

```js
const doc = nlp('patrol')
doc.tag('verb')
doc.world.irregulars.verbs.patrol = { PastTense: 'patrolorama!' }
console.log(doc.verbs().conjugate())
/*[
  {
    PastTense: 'patrolorama!',
    Gerund: 'patroling',
    PresentTense: 'patrols',
    Infinitive: 'patrol',
    FutureTense: 'will patrol'
  }
]
*/
```
cheers!
