### ISSUE TITLE
.sentences().toPastTense() also converted verbs after "to"

### ISSUE THREAD

**Issue by jiehan1029** [spencermountain/compromise#804]
Hi! I just started using this library and was not sure if what I got is a bug or my misuse:

Original Copies:
```
const copy1 = "On average, you take 11 hours to provide feedback when requested."
const copy2 = "But you take longer to give feedback to him."
```
Processing:
```
import compromiseSentences from 'compromise-sentences'
import nlp from 'compromise'
nlp.extend(compromiseSentences)

const toPastTense = (input) => {
  return doc.sentences().toPastTense().text()
}

console.log(toPastTense(copy1))
console.log(toPastTense(copy2))
```
Expected: 
```
On average, you took 11 hours to provide feedback when requested.

But you took longer to give feedback to him.
```
Received: 
```
On average, you take 11 hours to provide feedback when requested. (why no change?)

But you took longer to gave feedback to him. (give=>gave shouldn't happen)
```

Was I using the wrong API? Thanks in advance for any help!

BTW versions I'm using:
```
    "compromise": "^13.7.0",
    "compromise-sentences": "^0.1.1",
```

**Comment by spencermountain** [comment]
hey JieHan - yep this looks like a bug. You're doing everything right.
Happy to fix it. 
* 'on average' is tagged as a verb
* Looks like the subclause 'when requested' is confusing our subject-verb parser.
* 'took longer to give' should be recognized as past-tense
cheers

**Comment by ryancasburn-KAI** [comment]
@spencermountain was looking through old issues to see if anything might have been fixed with the things we've been doing this week. Came across this one that is already fixed on master. Propose to close?
