### ISSUE TITLE
'Anyhow' tagging

### ISSUE THREAD

**Issue by alexcheninfo** [spencermountain/compromise#805]
If you write something like this:

```
const text = `Anyhow, some text.

He some text.

Man some text.`

const result = nlp(text).if('^#Noun').out('array')
console.log(result)
```

You will get:

`[ 'Anyhow, some text.', 'He some text.', 'Man some text.' ]`

I'm confused. _Anyhow_ is an adverb and _He_ is a pronoun. Only _Man_ is a noun. Does _noun_ mean something different to `compromise`?

Note: I'm using `compromise 13.8.0`

**Comment by spencermountain** [comment]
Hey alex - .if() returns any sentence with the match, youll want .match()
Cheers

**Comment by alexcheninfo** [comment]
Oh, I see. Thanks for the quick reply!

**Comment by alexcheninfo** [comment]
@spencermountain Thanks for the quick reply. But even if I use `.match()`, I get:

    [ 'Anyhow,', 'He', 'Man' ]

I was expecting to only see `Man` in the array (since the others aren't nouns). Am I misunderstanding something?

**Comment by spencermountain** [comment]
you're right it shouldn't be a noun.

**Comment by alexcheninfo** [comment]
Most dictionaries list "anyhow/anyway" as an adverb: 

https://dictionary.cambridge.org/dictionary/english/anyhow.
https://www.collinsdictionary.com/dictionary/english/anyway

I think `compromise` has a different tagging system than dictionaries? What are adverbs regarded as right now? I think anyhow/anyway should go there.

**Comment by spencermountain** [comment]
yeah, adverb sounds good to me. 'he said it anyhow' ~ 'he said it carefully'
You can see our current lexicon [here](https://github.com/spencermountain/compromise/tree/master/data)

**Comment by alexcheninfo** [comment]
@spencermountain So there's no `adverb` folder?

**Comment by spencermountain** [comment]
https://github.com/spencermountain/compromise/blob/master/data/misc/adverbs.js

**Comment by alexcheninfo** [comment]
@spencermountain Wow, that looks great. It's a new addition? It didn't exist before?
