### ISSUE TITLE
.has method no longer works

### ISSUE THREAD

**Issue by AurielleP** [spencermountain/compromise#813]
I just upgraded to the most recent version - and it appears as though everywhere we used `.has('#Some #Tags')` or `.has('(#One|#Of|#These|#Tags)')` not longer returns true unless i change it to `.match('(#One|#Of|#These|#Tags)').found`

Is there something I'm missing that changed? This is a very large breaking change for us - but if thats the only way Ill go through and update it everywhere

**Comment by spencermountain** [comment]
no, that has not changed.
if you find an issue please provide an example, or read the changelog.
thanks
