### ISSUE TITLE
published compromise-sentences has out-of-date peerDependency on compromise

### ISSUE THREAD

**Issue by JaredReisinger** [spencermountain/compromise#818]
The compromise-sentences@0.1.1 plugin has a peer dependency on compromise of `^12.*.*`, but compromise has been published as `13.10.0`.

The peer dependency has been updated here on GitHub to use compromise `>=12.0.0`, but this has not been published to npm.  Should it be?

Thanks!

**Comment by spencermountain** [comment]
ahh, thank you Jared. I will fix this today.

**Comment by spencermountain** [comment]
hey, bumped the release to `compromise-sentences@0.2.0`. That should do it!
thank you, again.
