### ISSUE TITLE
Past tense or noun?

### ISSUE THREAD

**Issue by chiay** [spencermountain/compromise#823]
Hi there. I had a chance to try the library, and I found that it outputs a different result with the following code. 

`nlp('A girl hit a boy.').json()`

The word "hit" in this sentence is suppose to be verb (past tense) instead of noun. However, changing the first determiner or adding one word in front of "hit" gives the correct result.

**Comment by spencermountain** [comment]
ah! Thank you @chiay - this is a good catch.

Oof, looks like 'a girl hit' is catching the tagger meant for 'a tv show'.
Will fix this week. Please let me know if you find anything else.
cheers

**Comment by spencermountain** [comment]
this is now fixed on `13.10.1 `
cheers
