### ISSUE TITLE
Match accented characters

### ISSUE THREAD

**Issue by mohsinather-gnowit** [spencermountain/compromise#835]
Match is not working for accented characters i.e
text = "Québec is in canada"

it not matching "Québec"

**Comment by spencermountain** [comment]
thanks @mohsinather-gnowit - you're right, this should match normalized and non-normalized forms
sounds like a bug.
cheers

**Comment by retorquere** [comment]
`'Poincare\u0301.'` is recognized as `{text: "Poincare", pre: "", post: "\u0301." }`
