### ISSUE TITLE
.urls() not working for https://en.m.wikipedia.org

### ISSUE THREAD

**Issue by museystem31** [spencermountain/compromise#836]
Hi, I noticed the following issue.

**Input**
`nlp('visit https://en.m.wikipedia.org').urls().out('array')`

**Expected Output**
`['https://en.m.wikipedia.org']`

**Actual Output**
`[]`

**Comment by spencermountain** [comment]
oh, looks like it's stumbling on the double-subdomain.
Thanks @museystem31 happy to fix this for the next release.
cheers

**Comment by axaysushir** [comment]
Can I look at it? How to contribute on this? This is my first try to open source.

**Comment by spencermountain** [comment]
hey @axaysushir of course! welcome
i beleive it's probably [this regular expression](https://github.com/spencermountain/compromise/blob/master/src/02-tagger/01-init/data/startsWith.js#L11) here - maybe it needs to allow a period in some place.

if you clone the repo, you should be able to change that regex and see changes immediately.
if you run `npm run test` you can make-sure all the existing tests still pass
thanks for your help!

**Comment by axaysushir** [comment]
Ya sure I will do it and make pull request for that

**Comment by axaysushir** [comment]
If i use this Regex it matches all URL's including `https://en.m.wikipedia.org`.
 `/^[a-z0-9./].+\.(com|net|gov|org|dev|ly|edu|info|biz|ru|jp|de|in|uk|br)/`

But when i try to run npm run test, it shows some error in console like `Error: Cannot find module 'pure-md5'` or `Error: Cannot find module 'chevrotain'`. 

And how can i test this fix in local environment, means how to run this project locally?

**Comment by spencermountain** [comment]
oh, sorry about that - that sounds like dependencies in the plugin tests that haven't been installed.
`npm run plugins:install` installs all of those, or otherwise,  `npm run test main`  just runs the main ones.
Apologies, i should put these instructions somewhere.
cheers

**Comment by axaysushir** [comment]
Ok! man i do it and make PR

**Comment by axaysushir** [comment]
![image](https://user-images.githubusercontent.com/51092842/117024709-dc7d8a00-ad17-11eb-99c0-22fc8838545f.png)
I get this 1 failed test when running `npm run test main`. What's the reason for this. 

I checked my regex and it matches various strings. 
![image](https://user-images.githubusercontent.com/51092842/117025291-69c0de80-ad18-11eb-9c8e-9299308b03c7.png)

**Comment by spencermountain** [comment]
hmm. good question.
maybe it is something in the string encoding, passing through compromise.
feel-free to make a pr for this, I can take a look
thanks!

**Comment by axaysushir** [comment]
Thanks! I raised a PR for this changes
