### ISSUE TITLE
Functions modify original doc (In place)

### ISSUE THREAD

**Issue by AlexanderButyaev** [spencermountain/compromise#842]
Hello,

I admit that I'm new in compromise and may have missed out on something.
I've noticed that many functions modify the original doc object in place (which I did not expect...):

```javascript
const doc = nlp("Kid was playing soccer");

const verbs = doc.verbs().toInfinitive(); // this will change doc's text

doc.text(); // returns "Kid play soccer"
```

I'm curious is it a feature or a bug? Won't it be more reasonable to return verbs as an array, which you can process later BUT leave doc as is for any further analysis?
Thanks

**Comment by spencermountain** [comment]
hey @AlexanderButyaev - yeah, this has been a long quandry of this library, and the current mutable setup is as-designed.
This is covered a little-bit [here](https://observablehq.com/@spencermountain/compromise-tutorial-2)

In general, the document object has all the parsed and tagged term metadata, and stores them internally as a linked-list.
You can 'zoom-in' indefinetly, and change things, then 'zoom-out' and see the changes.
this is particularly useful with `.match('...').tag('Foo')` patterns, but also find/replace and other heavy use-cases.

i agree that mutable libraries can be tricky - 'a footgun', and i've considered bundling immutable datastructures.
For the mean time, you can use `.clone()` to avoid some tricky-business, and take the perf-hit overhead that you'd have from an immutable system.
cheers

**Comment by AlexanderButyaev** [comment]
Makes sense! Thanks!
