### ISSUE TITLE
doc.durations().get() returns different results second time it is executed

### ISSUE THREAD

**Issue by AlexanderButyaev** [spencermountain/compromise#843]
Hello,

I'm trying to extract the time duration from the input text and found out that results differ for two .get() functions (which might be caused by doc object been changed by .durations().get(), ([842](https://github.com/spencermountain/compromise/issues/842))

```javascript
const doc = nlp("set timer for three minutes and twenty seven seconds");

doc.durations().get();
// >[ { minute: 3, second: 27 } ]

doc.text();
// >'set timer for three minute and twenty seven second'
// doc was changed - minute and second as SINGULAR

doc.durations().get();
// >[ { minute: 3 } ]
```

Next I tried simple example with singular "second" in the input and it failed to detect:

```javascript
const doc = nlp("set timer for one second");
doc.durations().get();
// >[]
```

I believe it treats "second" not as a noun but as a 2nd.
It is possible to work around this however if doc is changed by .get() (WOW)  it gets a whole lot messier.

Is there anything I can do to not create a card house for workarounds?
Thanks!

**Comment by spencermountain** [comment]
whoa! this looks like a bug.
yeah - the date-plugin is still new. This should not be happening.
happy to fix this. you may be able to guard-against it with a `.clone()` call, right now

**Comment by spencermountain** [comment]
hey Alexander, this is now working in v14.
cheers
