### ISSUE TITLE
esm version of `compromise-tokenize`

### ISSUE THREAD

**Issue by Hypercubed** [spencermountain/compromise#845]
Hello,

I would like to submit a PR to add a esm version of `compromise-tokenize` (in fact code is done).  However, it's my opinion that libraries should publish uncompressed source and let the consumer minify in most cases.  I would like to propose the adding following build files:

```
compromise-tokenize.js             # currently this is minified and no unminified version is published
compromise-tokenize.min.js
compromise-tokenize.mjs
compromise-tokenize.min.mjs
```

If that sounds resonable a PR will follow shortly.

**Comment by spencermountain** [comment]
hey Jayson, thanks, i'd love your help with this. i'm curious about that - why do you want the esm to be uncompressed?
I was thinking about esm use in the browser, via the script tag.
cheers

**Comment by spencermountain** [comment]
i'll admit a lot of the esm stuff is over my head, and I haven't kept up to date with what's what.
I know some people are using esm in ./src - and encouraging others to. This would be the missing version you're looking for, right?

**Comment by Hypercubed** [comment]
I am using the esm version (`compromise.mjs`) in deno (TypeScript).  I think most TypeScript users will want to import the uncompressed esm version and then let their build tools do any minification.

I'm really intertested in getting a `compromise-tokenize.mjs`, not sure how you feel about changing `compromise-tokenize.js` to be uncompressed and adding `compromise-tokenize.min.js`.  It could be considered a breaking change.

**Comment by Hypercubed** [comment]
One more point... the reason I want to use `compromise-tokenize.mjs` rather than `compromise.mjs` is I would like to start without any word defintions and add my own as needed.  I have't yet tested doing this.

**Comment by spencermountain** [comment]
i have a breaking version planned for late-august, and can include this change in it then.
cheers
