### ISSUE TITLE
Matching a collection of questions for an FAQ bot

### ISSUE THREAD

**Issue by FarazPatankar** [spencermountain/compromise#852]
Hey, this kinda doesn't belong here but I didn't notice a discussions tab so thought I'd try my luck. I am working on an FAQ bot and originally used the `natural` library. I recently came across `compromise` and it seems pretty cool.

Is there a way for me to identify whether the input from a user was close to a pre-populated list of questions? And then based on how close the input was, send that specific answer? For example:
```js
const questions = {
  "free-plan": {
    "questions": [
      "Is there a free plan",
      "Free plan limits?",
      "What are the usage limits for the free plan?"
    ],
    "answer": "The free plan allows you to conquer the world!"
  },
  "backups": {
    "questions": [
      "Can I backup my data?",
      "Do you support DB backups?"
    ],
    "answer": "Not at the moment, but very soon!"
  },
  ...
}
```

And then the implementation would be something along these lines:
```js
bot.on("message", async msg => {
  // check if tone is interrogative
  if (isInterrogative(msg.content)) {
    // find match from list above and respond
    handleQuestion(msg);
  }
}
```

This is how my current implementation with `natural` works but very open to suggestions.

**Comment by spencermountain** [comment]
hey Faraz, yeah natural is pretty awesome, and probably a good tool for this application.
To do this in compromise, it would involve writing-out templates in the [match-syntax](https://observablehq.com/@spencermountain/compromise-match-syntax) - like `(can|should|may) i (backup|save) . data`
this gives you more control over the types of things it matches, but doesn't have any of the statistical cleverness that natural does
cheers

**Comment by spencermountain** [comment]
i setup the discussions tab - thanks for the headsup

**Comment by FarazPatankar** [comment]
Yep, that's what I thought as well but just wanted to be sure. Regarding the match syntax, can I pass the user input and see some sort of percentage match to my created templates?

Basically, I'd like to compare the input to every template I've written out, and then if the incoming message has at least a 75% match, the bot responds with the answer for that template?

**Comment by spencermountain** [comment]
yeah, there is some [fuzzy matching](https://observablehq.com/@spencermountain/compromise-fuzzy-matching?collection=@spencermountain/nlp-compromise) - but not the %-matching results, as you described.
would be a cool feature though!
cheers

**Comment by FarazPatankar** [comment]
Yep. Perhaps I should stick with `natural` for this project but `compromise` is pretty cool and I might give it another shot in the future.

Thanks for the quick replies btw. 😄
