### ISSUE TITLE
toInfinitive incorrectly returns "turne" for the verb "turned"

### ISSUE THREAD

**Issue by scpedicini** [spencermountain/compromise#857]
Steps to reproduce:
`nlp("Mary turned the key.").verbs(0).toInfinitive().out()` 

Output: "turne" instead of "turn"

In the meantime, is it possible for me to add a custom override for the verb "to turn" to fix this specific edgecase?

**Comment by spencermountain** [comment]
thank you. will address in the next release

**Comment by scpedicini** [comment]
Hey Spencer, 

Thanks. is there any way for me to add a custom override for the verb "to turn" to fix this specific edgecase? I could always replace it post-compromise, but just wondered if compromise provides a means to add a custom rule for something like this.

**Comment by spencermountain** [comment]
coming in the next version!
late-august.
cheers

**Comment by spencermountain** [comment]
if you wanted to fork/build until then, popping a fix [right here](https://github.com/spencermountain/compromise/blob/master/src/transforms/toInfinitive/_transform.js#L149) should do the trick

**Comment by jurijsk** [comment]
same true for `designed`

**Comment by spencermountain** [comment]
as of v14:
```js
console.log(nlp("Mary turned the key.").verbs(0).toInfinitive().text())
// Mary turn the key
console.log(nlp("Mary designed the key.").verbs(0).toInfinitive().text())
// Mary design the key
```
let me know if you spot any more
thanks
