### ISSUE TITLE
Feature Request: Using replaced terms in replacement text

### ISSUE THREAD

**Issue by Magnogen** [spencermountain/compromise#863]
Seems simple on the surface, but it might be a little difficult to implement, idk

Essentially, something like:
```
let doc = nlp("She sells seashells on the seashore");
doc.replace("#Pronoun #Verb", "#1 #0");
console.log(doc.text());
// outputs "sells She seashells on the seashore"
```

it could also do things like:
```
let doc = nlp("Do you want to build a snowman?");
doc.replace("#Determiner #Noun", "#0 bigger #1");
console.log(doc.text());
// outputs "Do you want to build a bigger snowman?"
```

Would be very helpful, and tbh I'm new to this so there might be a way to do it already. Thanks for your time!

Edit: I wasn't sure what to use for the replacement terms, so I went with #index-of-word-in-replacement-text , as you might want to replace a string with multiple of the same type or something. I'd welcome any other ways of doing this though :)

**Comment by spencermountain** [comment]
This is a lovely idea. I also like the syntax. I'm happy to do this. I'll add it to v14.

**Comment by Magnogen** [comment]
Awesome! Thank you so much!

**Comment by spencermountain** [comment]
not ready yet, but this is working on dev
```js
let doc = nlp('i am george and i live in France.')
doc.replace('i am [#Person+] and i live in [.]', '$0 is from $1')
doc.text()
// 'george is from France'
```
such a good idea. thank you again.

**Comment by Magnogen** [comment]
You gotta love eating lumps of wood

**Comment by spencermountain** [comment]
this is live in v14, but I haven't tested it very hard. Please let me know if you see any issues
cheers
