### ISSUE TITLE
isFuture - detect future sentence tense

### ISSUE THREAD

**Issue by YonatanHanan** [spencermountain/compromise#867]
Hi!

NOT a real issue, just a question :)

I wrote this code that detects if the sentence is speaking about the future.
```javascript
const isFuture = (document: nlp.Document) => {
  let isFuture = false;
  // console.log(document.text());

  document.verbs().forEach(verb => {
    // console.log();
    // console.log(verb.text());

    // get the terms
    const terms = verb
      .termList()
      .map(term => term.text)
      .filter(term => term.length > 0);

    const conjugates: NLPConjugate[] = (nlp(verb.text())
      .verbs()
      .conjugate() as unknown) as NLPConjugate[];

    // find future
    const futureConjugates = flatten(
      conjugates.map(conjugate => [conjugate.Infinitive, conjugate.FutureTense])
    );

    // check if is future
    const futureTerms = terms.filter(
      term =>
        futureConjugates.filter(conjugates => conjugates.includes(term))
          .length > 0
    );
    console.log({ terms, futureTerms, futureConjugates });

    if (futureTerms.length > 0) {
      isFuture = true;
    }
  });

  return isFuture;
};
```

do you think it is ok? is there a better option?

**Comment by spencermountain** [comment]
hey Yonatan, this is really clever solution, and I know looping through sub-matches like this is super awkward process right now.
nice work!
yeah - I'm trying to improve this stuff as we speak. `.verbs()` gets you some verb-phrases, but will drop the ball in some cases like `he will, if it was raining, wear his coat`.

english future tense is weird. some people say english _doesn't have_ a future tense. Your example will match 'will x' but may not match 'going to x'. 

v14 has some tense-detection, and may help you. It will get released in september. I can let you know when it is
cheers

**Comment by spencermountain** [comment]
hey Joe, this is a lot easier now, in v14
thanks for your patience
https://runkit.com/spencermountain/62e18337bed62300084fa88c
cheers
