### ISSUE TITLE
Single Verbs and Long Adjectives

### ISSUE THREAD

**Issue by jermlab** [spencermountain/compromise#869]
Hey, this is a cool program.

I'm basically looking to convert lists of words and ran into a couple of issues. 
1. nlp("walk").Verbs().toPastTense().text() --> "walk"

2. nlp("experienced").adjectives().toSuperlative().text() --> "experiencedest"

I could work around 1. by make a sentence "You " + "walk," but I'm not sure what to do about 2. 

Anyway, great work.

**Comment by spencermountain** [comment]
hey @jermlab yep #2 looks like a bug - happy to fix it.

for #1, you can co-erce your list of terms into a verb:
```js
nlp("walk").tag('Verb').verbs().toPastTense().text()
```
thanks for the issue
cheers

**Comment by spencermountain** [comment]
ah, good find. what's happening is the verb-conjugator thinks it's an Imperative - like 'please walk!'
and is refusing to conjugate it.
will add this to v14 - thanks for the heads-up

```js
nlp("walk").tag('PresentTense').verbs().toPastTense().text()
//walk
```

**Comment by jermlab** [comment]
Great. Looking forward to it!

**Comment by spencermountain** [comment]
fixed now in v14
thanks!
