### ISSUE TITLE
Adjectives like "worn" tagged as "Singular/Noun."

### ISSUE THREAD

**Issue by alexcheninfo** [spencermountain/compromise#870]
For example, if you type "A worn dress" into the textarea in https://compromise.cool/, "worn" will be tagged as "Singular" (Noun).

In that example, "worn" is an [adjective](https://www.google.com/search?q=worn+define&oq=worn+define&aqs=chrome.0.69i59j0i22i30l9.1058j1j7&sourceid=chrome&ie=UTF-8).

Is this a mistake/bug, or it's intentional?

**Comment by spencermountain** [comment]
hey alex, yep this looks like a bug. Thanks for letting me know.
if you'd like, you can coerce it [with a lexicon](https://observablehq.com/@spencermountain/compromise-lexicon), for now
cheers!

**Comment by alexcheninfo** [comment]
Thanks for the fast reply! Even with bugs like this, compromise is still the best NLP library out there!

**Comment by alexcheninfo** [comment]
@spencermountain That's awesome! Keep up the good work.
