### ISSUE TITLE
How to detect most emphasized topic in a sentence?

### ISSUE THREAD

**Issue by aiavci** [spencermountain/compromise#873]
### Summary
The topics() method returns an array of topics detected in a sentence. My question is. Is there a way to detect the most emphasized topic out of the list that is returned?

**Comment by spencermountain** [comment]
hey Ali, i'm afraid there isn't - that's a pretty personal task, based on the use-case. Many have had some success using [tfidf](https://monkeylearn.com/blog/what-is-tf-idf/) - which is where I would turn, to rank the results of .topics()
cheers!
