### ISSUE TITLE
"it is easy to forget" tagged maybe not right

### ISSUE THREAD

**Issue by nguyenthanhsonbs** [spencermountain/compromise#875]
About "it is easy to forget", it parses "it(Pronoun) is(PresentTense) easy(Verb) to(Conjunction) forget(Infinitive)"
I think "easy" should be an adjective
"it is easy", it works fine

**Comment by spencermountain** [comment]
i agree! thank you.
I will add this to v14, where fixes like this are currently underway
cheers

**Comment by sohushare** [comment]
thanks spencermountain, btw compromise is the best library i've found until now
