### ISSUE TITLE
Tags don't appear to save/persist

### ISSUE THREAD

**Issue by deoates** [spencermountain/compromise#887]
```
let nlp = require("compromise");

let doc = nlp("red")
doc.tag("Color");

let doc2 = nlp("red potato novel");

let test = doc2.match("#Color").text();

console.log(test);
```

The above code snippet returns an empty string instead of red, which is the expected behavior. 

Color is also missing from `Object.keys(nlp("").world.tags)`

**Comment by spencermountain** [comment]
hey david, I think what you're trying to do would be solved by using a [custom lexicon](https://observablehq.com/@spencermountain/compromise-lexicon)
```js
  let myWords = {
    'red':'Color'
  }
  let doc = nlp('The apple is red', myWords) //add words as a 2nd param
  return doc.json()
```
cheers
