### ISSUE TITLE
Some units not being recognized

### ISSUE THREAD

**Issue by Codezilluh** [spencermountain/compromise#889]
Hello, I have stumbled upon what might be an issue. I know I can fix it on my end by tagging certain words, but I feel that maybe it should be addressed globally. The issue is that some `units` (such as "in," "ft," and "m") are not being identified as units when preceded by a number.

 These do not work:
`"12 in wide"
/ "12 in. wide"
/ "12-in wide"`
`"1 ft wide" / "1 ft. wide" / "1-ft wide"`

These do work:
`"4 mi wide" / ...`
`"67 mm wide" / ...`

For my use case, I want to extract units from the text and I am not too interested in the value tag (other than extracting units from it). I would like to see more units added (including recognizing non-abbreviated units, like "inches"). I might check out the code and see what I could add once I get back home.

**Comment by spencermountain** [comment]
hey @Codezilluh - thanks. Yeah - units are super-hard. The library really sucks at them.

On one hand anything is a unit - '12 books wide'
but on the other hand, even major units like 'k' are just flat-out ambiguous. I'm not sure if we should tag '12 in wide' as a unit, by default, for example. I went too-far, then I have scaled them back. 

Good news is your timing is good. The numbers plugin is entering main in v14, which is on the dev branch. It's gotten cleaned-up a bit, so if you wanted to change its default behaviour, or add some kind of strong-mode, now is a good time.

Maybe the easiest thing would be to list a few-dozen tests, so we can figure out what the behaviour should be. Open to ideas.
thanks!

**Comment by spencermountain** [comment]
hey @Codezilluh the ft examples work now, out of the box in 14.4.0

the 'in' example is ambiguous, so you'll have to tag it manually:
```js
txt = "12 in wide"
txt = "12 in. wide"
txt = "12-in wide"
doc = nlp(txt)
doc.match('#Value [in]', 0).tag('Unit')
doc.debug()
```
cheers
