### ISSUE TITLE
Add support for cryptocurrencies in numbers plugin

### ISSUE THREAD

**Issue by siddharthlatest** [spencermountain/compromise#893]
This is a feature request to add support for recognizing popular cryptocurrencies, given that support for recognizing money already exists through the numbers plugin.

Would it be as easy as adding something here? Lmk if it makes sense and any thoughts on how to add would be great:  https://github.com/spencermountain/compromise/blob/master/plugins/numbers/src/money/data/currencies.js

**Comment by spencermountain** [comment]
hey @siddharthlatest - you can add any currencies you'd like with [a custom lexicon](https://observablehq.com/@spencermountain/compromise-lexicon), like this:
```js
let myWords = {
  'flubCoin': 'Currency'
}
let doc = nlp('i bought 8 flubcoin', myWords) //add words as a 2nd param
doc.debug()
```
there are some hard-coded things, like `$4` that we could add any unicode characters to support alternative currencies.

to be honest, the `.money()` function needs some work. Right now it simply wraps `.numbers()`, but should handle currencies more fully.
let me know if you have any more questions
cheers
