### ISSUE TITLE
First name being marked as Verb instead of Person

### ISSUE THREAD

**Issue by jeff4e** [spencermountain/compromise#894]
I have a sentence giving me odd results and wanted to see if there's a work around I can apply or if a bug fix is needed.

**Input**
```Erin walks to Bob.```

**Result**
```Erin``` is being tagged as a ```Verb``` instead of a ```Person```

```
{
    "text": "Erin",
    "clean": "ering",
    "reduced": "ering",
    "root": null,
    "implicit": null,
    "pre": " ",
    "post": " ",
    "tags": {
        "Gerund": true,
        "PresentTense": true,
        "Verb": true
    },
    "prev": null,
    "next": "walks-qfIOITO",
    "id": "ering-lgQmgDR",
    "isA": "Term"
}
```

**Desired Result**
```Erin``` is marked as a ```Person```

**Code Example**
```
let characters = {
 "Erin": "Person"
}

let res = nlp("Erin walks to Sally.", characters)

```

**Comment by spencermountain** [comment]
hey Jeff, thanks for the issue, and sorry for the delay. 
This is fixed now on dev branch, and will be included in the v14 release.
cheers

**Comment by spencermountain** [comment]
if you need a quick fix, you could do this:
```js
let characters = {
 "Ering": "Person"
}
```
a sloppy regex interprets it like 'walkin' or 'talkin'.
cheers

**Comment by gauravgandhi1315** [comment]
> if you need a quick fix, you could do this:
> 
> ```js
> let characters = {
>  "Ering": "Person"
> }
> ```
> 
> a sloppy regex interprets it like 'walkin' or 'talkin'. cheers

This fix works for me.

**Comment by spencermountain** [comment]
hey @jeff4e  this is fixed in [v14](https://github.com/spencermountain/compromise/releases/tag/14.0.0) 
thanks for the heads-up
