### ISSUE TITLE
compromise-dates challenging case: "The Deadline on Wednesday, February 23,2022 at 4:00pm."

### ISSUE THREAD

**Issue by lukelu0520** [spencermountain/compromise#897]
Dear compromise friends,

Thanks for creating such nice tool. Recently we got below challenging sentences from real world, trying to parse dates but fail:
> The Deadline on Wednesday, February 23,2022 at 4:00pm.

Using doc.dates().text() we got:
> on Wednesday, February at 4:00pm

The case is not grammarly perfect, 23 should be 23rd and the comma between 23 and 2022 needs a space. But human typing are often not perfect. So far we have no idea how to overcome the problem.

Does it require a complicate neural network out the scope of compromise ?

Hope to hear your expertise.

--Luke

**Comment by thegoatherder** [comment]
Try preparing your text with regular expressions to fix common punctuation issues - you can do a cleansing pass before you give the text to compromise.
