### ISSUE TITLE
[suggestion] Add const nlp = require('compromise') as first example

### ISSUE THREAD

**Issue by jzombie** [spencermountain/compromise#900]
When reading through the examples, it wasn't immediately known to me (other than via assumption) that the nlp variable was the main export until reading some of the examples and then stumbling upon the line in a subsequent example.

```js
const nlp = require('compromise')
```

A suggestion would be to include this in the first example, as a quick start.

----

Shown below is how far down the README this was used, after previous examples showed the nlp variable being used.

![2022-03-15_05-49](https://user-images.githubusercontent.com/1139657/158371911-81fe6674-21f5-4323-b38e-659c89f9ed75.png)

**Comment by spencermountain** [comment]
good point! reworking the readme for v14, your timing is good.
would love some feedback on that, next week.
cheers

**Comment by jzombie** [comment]
Sure, hopefully I'll see the notification, otherwise will try to remember to circle back here and comment.

I'll be using this library a bit over the next few weekends for a hackathon I'm participating in doing some speech transcription normalization, so this topic should stay pretty fresh in my mind.

**Comment by spencermountain** [comment]
hey, let me know if you have any qualms or feedback on the [updated readme](https://github.com/spencermountain/compromise#readme)
cheers

**Comment by jzombie** [comment]
The README looks good.  Had some parsing issues, where it was incorrectly identifying a lot of words as nouns, and got a lot of verbs that were not verbs, just using the base library with no plugins.
