### ISSUE TITLE
compromise-speech not available

### ISSUE THREAD

**Issue by jzombie** [spencermountain/compromise#906]
I'm trying to follow along with this README example and can't find compromise-speech on npm or in your GitHub repos.

![2022-04-09_18-03](https://user-images.githubusercontent.com/1139657/162595642-5745dabd-fe02-42a4-bdf7-815365243a2d.png)

**Comment by spencermountain** [comment]
hey, sorry about that, it's available now at [compromise-speech](https://www.npmjs.com/package/compromise-speech)
and on github [here](https://github.com/spencermountain/compromise/tree/master/plugins/speech)
i'll fix the readme links in the next release
cheers

**Comment by spencermountain** [comment]
hey @jzombie this should be fixed in 14.1.0
thanks!
