### ISSUE TITLE
Unexpected result from normalize when compromise, numbers and dates are imported 

### ISSUE THREAD

**Issue by lukelu0520** [spencermountain/compromise#909]
Dear compromise friends,
```
const nlp = require('compromise')
nlp.extend(require('compromise-numbers'))
nlp.extend(require('compromise-dates'))

let text = 'open hour 2-3pm';
console.log( nlp(text).normalize().out('text') )
```

I got "**open hour 2-3PMto 3 pm**"

There is an unexpected "to 3pm" added. Hope to hear your expertise on the root cause and a solution.

Best,
--Luke

**Comment by spencermountain** [comment]
hey @lukelu0520 - sorry about that. Looks like this is fixed in [v14](https://github.com/spencermountain/compromise/releases/tag/14.0.0) -
https://runkit.com/spencermountain/625707751dffec0008d0e8cd
let me know if you see any other funny business, after an update
cheers
