### ISSUE TITLE
Babel CJS error when building my app with latest compromise version

### ISSUE THREAD

**Issue by jeffmiko** [spencermountain/compromise#910]
Compromise version 13.10.6 works fine, but newer versions of compromise throw the error below when building/serving my Vue JS app.

`* compromise in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/views/comments.vue?vue&type=script&lang=js`

**Comment by spencermountain** [comment]
hey @jeffmiko you may want to try today's relesese, 14.1.1 

i made a typo in package.json path that may have caused this. otherwise, i'll need more information about the error to help you. v14 is using esmodules, but you should be able to use existing cjs/babel setups
let me know
cheers

**Comment by jeffmiko** [comment]
thanks @spencermountain this new version did fix my issue. I can now import 'compromise' and my code builds. I did notice the same CJS errors when trying to import 'compromise/one' when I tried even with this new version.
