### ISSUE TITLE
Compromise package.json is invalid

### ISSUE THREAD

**Issue by trevorlinton** [spencermountain/compromise#911]
compromise `main` field in the package.json points to `src/index.js` which is an invalid path (it was removed/moved(?) in v14).

Our testing framework (`jest`) keeps returning a module cannot be loaded as it's trying to load the file in the `main` field here: https://github.com/spencermountain/compromise/blob/master/package.json#L6.

Going back to v13.11.4 fixed the issue for me.

**Comment by spencermountain** [comment]
Ah, sorry Trevor. That is sloppy of me. 
I'll fix this today

**Comment by spencermountain** [comment]
fixed in `14.1.1`
thanks for the heads-up
