### ISSUE TITLE
Failed to import plg from 'compromise-speech'  for using syllable

### ISSUE THREAD

**Issue by IAM5K** [spencermountain/compromise#913]
While implementing in angular, 
`import plg from 'compromise-speech'
nlp.extend(plg)

let doc = nlp('Milwaukee has certainly had its share of visitors..')
doc.compute('syllables')
doc.places().json()`
/*
[{
  "text": "Milwaukee",
  "terms": [{ 
    "normal": "milwaukee",
    "syllables": ["mil", "wau", "kee"]
  }]
}]
*/

plg is not found also to make nlp working,
`
var nlp = require('compromise')` is used. import is not working in typescript/ angular.
Please help, I urgently need to implement 
`doc.compute('syllables')`.
Thanks in advance

**Comment by spencermountain** [comment]
hi Sandeep, you should be able to use either `require` or `import` in your project, but probably not both at the same time.
```js
var nlp = require('compromise')
var plg = require('compromise-speech')
nlp.plugin(plg)
```

or

```js
import nlp from 'compromise'
import plg from 'compromise-speech'
nlp.plugin(plg)
```

read more about the details of this [here](https://dmitripavlutin.com/ecmascript-modules-nodejs/)
cheers
