### ISSUE TITLE
missing Plugin type

### ISSUE THREAD

**Issue by yesean** [spencermountain/compromise#918]
Hi, I'm migrating to compromise v14, so I've replaced `compromise-ngrams` with `compromise-stats`, but I'm using typescript and can't get it to build. I'm getting this error:
```
$ tsc
node_modules/compromise-stats/index.d.ts:4:30 - error TS2724: 'nlp' has no exported member named 'Plugin'. Did you mean 'plugin'?

4 declare const nlpNgrams: nlp.Plugin<
                               ~~~~~~


Found 1 error in node_modules/compromise-stats/index.d.ts:4

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems there used to be a [`Plugin` type](https://github.com/spencermountain/compromise/blob/a49cfae80d294f224bd08e2560faf348b9935cc4/builds/types.d.ts#L126) in the `nlp` namespace a while back, but it got removed in the latest version?

**Comment by spencermountain** [comment]
hey Sean, yeah sorry about this. v14 required a re-write of the typefile, and I haven't figured out how to support the plugins properly yet - are you good at this stuff? I'd love a hand
cheers

**Comment by jfemia** [comment]
Isn't the main problem with plugins and types that there needs to be a way to extend the `View` interface itself for plugins that want to add new methods? e.g. so I can do this:
```
import stats from 'compromise-stats'
nlp.plugin(stats)
nlp('something').ngrams({...}) // ngrams is a stats function, but typescript doesn't know it's now a method on View
```

In which case it seems to me as a not-particularly-expert Typescript generics user that the plugin typings should export method interfaces separately, and the `nlp` method typing be given a generic parameter to allow the specified interfaces to be merged with `View`.

I did a little experiment with the type definitions and came up with this method of using plugins:
```
import stats, { StatsMethods } from 'compromise-stats'
nlp.plugin(stats)
const doc = nlp<StatsMethods>('text') // returns type Three & StatsMethods
doc.ngrams({}) // type of ngrams() is correct
```

If you had multiple plugins you'd just construct your doc with all the plugin types you wanted
```
const doc = nlp<SomePluginMethods & SomeOtherPluginMethods & etc...>('text')
```

Does that sound like a reasonable API? I've put my small typing changes in a branch in this commit here - let me know if you want a PR or have a different direction in mind https://github.com/jfemia/compromise/commit/411f0e6889410cdb2994f3418b66d82817d59522
