### ISSUE TITLE
Apostrophe in custom word prevents matching

### ISSUE THREAD

**Issue by msjonker** [spencermountain/compromise#932]
I'm developing a custom lexicon of plant names, which include "Queen Anne's lace" and "baby's breath", however when a word in my custom lexicon includes an apostrophe, it doesn't seem to match. Is there something I need to do to force it to use the custom lexicon?

Additionally, I was looking through compromise's default lexicon and it seems like words in there with apostrophes aren't matching, either:

`
nlp("Starbucks is a great restaurant.").match("#Organization").out("array")`  //  ✅ 
`nlp("Applebee's is a great restaurant.").match("#Organization").out("array")`  //  ❌
https://github.com/spencermountain/compromise/blob/52fb03e7a26e8caed08bf04d893b0044aab4c538/data/lexicon/nouns/organizations.js#L275

**Comment by spencermountain** [comment]
hey Matt, this is a good point.
You want it to match only when it's possessive, right? ie _'queen anne lace'_ should not match.

i'll take a look for 14.4
cheers

**Comment by spencermountain** [comment]
for reference:
```js
let lex = {
  'Queen Anne\'s lace': 'Flower'
}
let doc = nlp(`Queen Anne's lace`, lex)
doc.match(`#Flower`).debug() //empty
```

**Comment by msjonker** [comment]
Yeah, for my use-case, I'd expect it to only match if it were the exact set of words, so not "_queen anne lace_".

Thanks for looking into it!

**Comment by spencermountain** [comment]
hey @msjonker this is tagging now in 14.4.0
it just throws-away the apostrophe, when creating the lexicon. if you want to ensure it's a Possessive, you can do something like:
```js
doc.match('queen (anne && #Possessive) lace').tag('Flower')
```
cheers

**Comment by msjonker** [comment]
Sorry, for the late reply; I was on vacation last week.

This solution looks great! I was working on a PR that evaluated matching the `normal` form of the term first, then falling back to the `machine` form of the term, but this seems like a much better solution.

Thanks!
