### ISSUE TITLE
.Wikipedia() in documentation leads to unaccessible Observable notebook

### ISSUE THREAD

**Issue by Utopiah** [spencermountain/compromise#946]
From README.md link to https://observablehq.com/@spencermountain/compromise-wikipedia yet it seems not to be public. I searched from https://observablehq.com/collection/@spencermountain/nlp-compromise but also nothing on compromise-wikipedia.

**Comment by spencermountain** [comment]
hey Fabien, thank you. I'll try to make it today.
cheers
