### ISSUE TITLE
Is there any way to add verbs / correct verb conjugations?

### ISSUE THREAD

**Issue by kabirverman** [spencermountain/compromise#949]
for example, `nlp('blow').verbs().toPastTense()` will yield "blown" when really what I'm after is "blew", meanwhile if I conjugate "blew" I get `{Infinitive: "bly", PastTense: "blew", PresentTense: "blies", FutureTense: "will bly"}`.

I've already looked into plugins and it doesn't seem like there's a way to modify or add to the verb list. Is there a way that I'm missing?

**Comment by spencermountain** [comment]
hey @kabirverman - sorry for the delay.

This got buried during a big rush to release v14 - this winter we refactored how conjugation is done. 
Here's how you can do it currently, but obviously this needs to improve, and be documented, somewhere.
```js
let doc = nlp('we swim')
let obj = doc.world.model.two.models.toPast
Object.assign(obj.exceptions, { swim: 'swum' })
console.log(doc.verbs().toPastTense().text())
// we swum
```
oof, i'm gonna try and add some sugar to this, for the next release. thanks!

**Comment by spencermountain** [comment]
(i'll look at the 'blew' conjugation, too)

**Comment by kabirverman** [comment]
thanks! it may not be pretty, but the fact that it can be done at all is great!

**Comment by spencermountain** [comment]
.plugin() now supports a 'irregulars' property:
```js
nlp.plugin({
  irregulars: {
      // co-erce verb transformations
      get: {
        pastTense: 'gotten',
        presentTense: 'gets',
        gerund: 'gettin'
      },
      // same for adjectives
      sly:{
        comparative:'slyer',
        superlative:'slyest'
     }
})
```
as documented [here](https://observablehq.com/@spencermountain/compromise-plugins)
thanks for the heads-up
cheers
