### ISSUE TITLE
Ignored tests

### ISSUE THREAD

**Issue by thegoatherder** [spencermountain/compromise#974]
I'm in the process of writing a new API method `/src/1-one/change/api/whitespace.js` for PR into Compromise. I want to add tests for the method also. 

I noticed that there are numerous tests named `*.ignore.js` - some of which have coverage for functions in `whitespace.js` - I'm just wondering if there's any background info for why these tests have become ignored?

**Comment by spencermountain** [comment]
i don't remember.

**Comment by spencermountain** [comment]
feel free to enable any that are still relevant!

**Comment by thegoatherder** [comment]
Haha, must have been one of those days…!!
I’ll re-enable some in the PR
