### ISSUE TITLE
How to remove a term from document by term id

### ISSUE THREAD

**Issue by thegoatherder** [spencermountain/compromise#976]
Is there any method that will remove a specific `term` from a document, given its term `id` ?

```javascript
{
  text: "it",
  pre: "",
  post: " ",
  tags: {
  },
  normal: "it",
  index: [
    0,
    0,
  ],
  id: "it|00100000B",
}
```

How can I remove term with `it|00100000B` from the doc and leave all other terms with `text: it` intact?

**Comment by spencermountain** [comment]
now in `14.7.0`:
```js
doc.not([{id:"it|00100000B"}])
```
cheers

**Comment by thegoatherder** [comment]
@spencermountain  amazing! Thanks!!
