### ISSUE TITLE
Compromise providing stopwords

### ISSUE THREAD

**Issue by SpiffGreen** [spencermountain/compromise#985]
Just a suggestion though, wouldn't it be nice if compromise provides stopwords even if not within the main library.
Its somehow a very hectic process gathering these things for use.

**Comment by spencermountain** [comment]
hey Spiff - ya, you should be able to build this from the word lists [in ./data/lexicon](https://github.com/spencermountain/compromise/tree/master/data/lexicon) - particularly [prepositions](https://github.com/spencermountain/compromise/blob/master/data/lexicon/misc/prepositions.js), [conjunctions](https://github.com/spencermountain/compromise/blob/master/data/lexicon/misc/conjunctions.js), and [pronouns](https://github.com/spencermountain/compromise/blob/master/data/lexicon/nouns/pronouns.js)
cheers

**Comment by spencermountain** [comment]
hey! this is very clever.
thank you.
