### ISSUE TITLE
How to fix the error for tokenizing (getting lemmatized version of sentence) in German?

### ISSUE THREAD

**Issue by lofti198** [spencermountain/compromise#988]
Hi! Thank you for you cool library! Getting the error for the code:
`import nlp from "compromise";

// Set the language to German
nlp.plugin(nlp.german);

// Define a function for lemmatization
const lemmatize = (sentence) => {
  // Tokenize the sentence into individual words
  const tokens = nlp.text(sentence).tokens();
  // Lemmatize each word and return the result as an array
  return tokens.map((token) => token.lemma());
};

// Test the function with a German sentence
const result = lemmatize("Ich bin der Hund, der bellt.");
console.log(result);
// Output: ["ich", "sein", "der", "Hund", ",", "der", "bellen", "."]`
![image](https://user-images.githubusercontent.com/42960488/210040055-e832f4e7-e677-423d-9d35-cf0135cb2905.png)

What am  I missing?

**Comment by spencermountain** [comment]
hey @lofti198 - sure you can do tokenization with german compromise. 
This is how I would do it.
```js
import nlp from 'de-compromise'

let tokens = nlp("Ich bin der Hund, der bellt.").json()
console.log(tokens)
```
There are a few issues with your example. Did you find some old compromise docs somewhere? Please use the documentation on [de-compromise](https://github.com/nlp-compromise/de-compromise)
cheers
