### ISSUE TITLE
Possible typo on a city name

### ISSUE THREAD

**Issue by purplnay** [spencermountain/compromise#989]
https://github.com/spencermountain/compromise/blob/e4b2c8d7e5409c112f58085d8b41f225470de700/data/lexicon/places/cities.js#L493

You may be meaning [Reims](https://en.wikipedia.org/wiki/Reims) instead of Reimes?
I couldn't find anything about a city named Reimes in Europe.

**Comment by spencermountain** [comment]
Oops! Thank you.

**Comment by spencermountain** [comment]
released in 14.8.2 
thanks!
