### ISSUE TITLE
Missing .extend() types

### ISSUE THREAD

**Issue by evenfrost** [spencermountain/compromise#991]
When I try to use `.extend()` in v14 in TypeScript project:

```ts
import nlp from 'compromise';
nlp.extend(/* */);
```

it gives me an error:

```
Property 'extend' does not exist on type 'typeof nlp'.
```

A quick look at types shows that when importing `compromise`, its types are taken from `types/three.d.ts`, which doesn't contain a definition of the `extend` method, and only `types/one.d.ts` contains it.

**Comment by evenfrost** [comment]
I see now from the code that `.extend()` is just an alias for the `.plugin()` method. Would be also useful to have this reference somewhere in Readme.

**Comment by spencermountain** [comment]
hey good catch Aliaksei - yeah, there's been some thrash over the years. 
Is there a good typescript way to declare aliases? I've always liked doing that -  i figure it's generous to make the api less brittle. 
for now i've added extend as a copy of plugin on dev branch
please let me know if you find any other weirdness - I'm not a typescript guy and I don't have much confidence that things are currently perfect.
cheers

**Comment by evenfrost** [comment]
Thanks for the quick reply. I think for this case it's completely good to just define the function as you did. :)
